### ISSUE TITLE
MSS310 Do not show current power usage

### ISSUE THREAD

**Issue by swampylee** [albertogeniola/meross-homeassistant#101]
I think this might be a known issue but since the latest update I don't get any power readings for any of the 4 x MSS310 smart plugs I have (UK).

This is using version 20200622.1 that appeared in HACS yesterday/today

**Comment by albertogeniola** [comment]
Please update to the latest version (v1.0.0) which fixes the problem and introduces various improvements. Please follow update instructions [here](https://github.com/albertogeniola/meross-homeassistant#updating-from-legacy-versions).
