### ISSUE TITLE
No current consumption for mss310

### ISSUE THREAD

**Issue by jugla** [albertogeniola/meross-homeassistant#105]
Hello,
Thanks for this components !!

I have a MSS310.
If MSS310 was disconnected at time of reboot, upon plug reconnection, only "switch" is recognized. I.e. the sensor is not recognized --> it leads to not have consumption.

After reboot, it's ok.

**Comment by albertogeniola** [comment]
Hi @jugla , which version of the component do you refer to?

**Comment by jugla** [comment]
Hello,
The version was 20200622.1.
NB : the behaviour is slightly different with new version 0.4.X.X-alpha3 : I have consumption but not the switch

**Comment by albertogeniola** [comment]
Hi, could you please test the latest version, such as v1.0.0 and see if that is fixed?
