### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by pdgithub78** [albertogeniola/meross-homeassistant#107]
I'm receiving the following in hassio 0.112.4 and the latest version of meross installed via HACS

Log Details (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:120

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for meross_cloud doing I/O at custom_components/meross_cloud/__init__.py, line 60: http_devices = http_client.list_devices()

**Comment by albertogeniola** [comment]
Please update to the latest version available which fixes the problem.
