### ISSUE TITLE
Meross Integration fails starting

### ISSUE THREAD

**Issue by pgdg71** [albertogeniola/meross-homeassistant#113]
Hi,
once installed, the Meross Integration isn't able to find any devices.

Log error:
Dettagli registro (ERROR)
Logger: custom_components.meross_cloud
Source: custom_components/meross_cloud/__init__.py:144
Integration: Meross Cloud IoT (documentation)
First occurred: 6:17:29 (4 occurrences)
Last logged: 6:18:17

Error occurred. ------------------------------------- Component version: 0.4.0.0 Device info: <Unavailable> Error Message: "An exception occurred while setting up the meross manager. Setup will be retried..."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/__init__.py", line 144, in async_setup_entry
    await manager.async_device_discovery()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 232, in async_device_discovery
    enrolled_devices = await asyncio.gather(*tasks, loop=self._loop)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 282, in _async_enroll_new_http_dev
    payload={})
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 516, in async_execute_cmd
    if not self._mqtt_client.is_connected():
AttributeError: 'Client' object has no attribute 'is_connected'

**Comment by albertogeniola** [comment]
Hi @pgdg71 ,

this is due to a wrong requirement entry on the low-level MerossIot python library, which uses python paho-mqtt>=1.3.1 while **is_connected()** method is available only from paho-mqtt v1.5.0. I'll update the low-level Python library and fix this bug in the next release (hopefully 0.4.0.1).

Thanks for reporting this bug.

**Comment by albertogeniola** [comment]
Hi @pgdg71 ,

can you please test the **alpha** release v1.0.1 which addresses this issue and let me know if that's fixed?

**Comment by pgdg71** [comment]
Hi,
it seems fixed. The 2 valves have been.automatcally configured. The logs are clean also 

Many thanks!
