### ISSUE TITLE
Log messages - loop?

### ISSUE THREAD

**Issue by GHSTUDIO1** [albertogeniola/meross-homeassistant#118]
Log Details (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: July 22, 2020, 9:42:28 PM (1 occurrences)
Last logged: July 22, 2020, 9:42:28 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for meross_cloud doing I/O at custom_components/meross_cloud/__init__.py, line 60: http_devices = http_client.list_devices()

**Comment by albertogeniola** [comment]
Hi @GHSTUDIO1 : which version of the component are you using?

**Comment by GHSTUDIO1** [comment]
close this issue.....it apparently was due to having code from two different versions.  When I cleaned things up and now have only one version, this message went away.
