### ISSUE TITLE
Only one configuration of Meross is allowed

### ISSUE THREAD

**Issue by GHSTUDIO1** [albertogeniola/meross-homeassistant#119]
I only have one entry for Meross in my config file....but I get this log message (note: I have two Meross garage door openers).

Logger: custom_components.meross_cloud.config_flow
Source: custom_components/meross_cloud/config_flow.py:90
Integration: Meross Cloud IoT (documentation)
First occurred: July 22, 2020, 9:42:28 PM (1 occurrences)
Last logged: July 22, 2020, 9:42:28 PM

Only one configuration of Meross is allowed.

**Comment by dervogt** [comment]
could it be that you have one copy manually deployed in a non-standard folder name in your custom_components folder? or possibly stacked subfolders ? This had happened to me sometime ago and I just had to remove one of the custom_components by wiping it off the drive

**Comment by GHSTUDIO1** [comment]
I've found that HACS doesn't uninstall your code correctly which is why I had the duplicate.......and if I uninstall it completely, HACS doesn't install the latest version correctly.....yes, it puts it into custom components, but it first shows as "waiting for re-boot....and then when you reboot, it isn't added as an integration.
