### ISSUE TITLE
New device not recognized

### ISSUE THREAD

**Issue by wsw70** [albertogeniola/meross-homeassistant#124]
I just received two MEROSS plug strips and wanted to add them to HA:

- configured one plug on the MEROSS app
- added your repository to HACS
- added the MEROSS component
- it sees 1 equipment and everything works

I then added the second plug strip to the app (OK), the app correctly manages the strip but **it does not show up in the HACS component** (after about an hour).

- I rebooted HA
- I made sure that the option to add new devices is on. Just to make sure I disabled it, and then reenabled (hoping that this would trigger a pull on the device list)

I am not sure where to go next and whether this is an issue with the "device update" part of the component of if I missed something :)

**Comment by albertogeniola** [comment]
Can you provide the HW versions of both the strips? Which one is not showing up in HA?

**Comment by wsw70** [comment]
Ah, sorry for that - after some time (2 or 3 hours I think) it finally appeared in HA. I was a bit surprised because the first one was visible immediately but I ordered two more strips and I will check.

Thank you for following-up!

**Comment by wsw70** [comment]
As a follow-up: I added a new strip and it showed up immediately. The previous one must have been a glitch.

Thank again for the plugin!
