### ISSUE TITLE
power consumption entity

### ISSUE THREAD

**Issue by arifroni** [albertogeniola/meross-homeassistant#128]
Hello

Is there any way I can get consumed power value (kWh) entity in HA? at the moment I am using the following, but half of the time my switch is turned off, with zero value the calculation is somehow not correct.

```
  - platform: integration
    source: sensor.tv_led_mss310_power_sensor_w_0
    name: tvled_energy_spent_integration
    unit_prefix: k
    round: 2
```

**Comment by xvolte** [comment]
I got the same question.
I can see the current Wattage, however when i try to put it on a graph to show 24 hours, it only show the current state/value.

Is there a way to log the sensor value like every 1 minutes or so ?

**Comment by albertogeniola** [comment]
Hi guys,
that is out of the scope for this component. You should leverage other components or integrated HA functionalities.
