### ISSUE TITLE
Integration not found: meross_cloud

### ISSUE THREAD

**Issue by MaurizioB84** [albertogeniola/meross-homeassistant#13]
Hello,
I try to install into a docker container (classic HA installations no hassio) but when I try to restart the HA I received this error:
Integration not found: meross_cloud
pi@raspberrypi:~/.homeassistant/config/custom_components/meross_cloud $ ls -ltr
totale 40
-rw-r--r-- 1 pi   pi   2578 ago 17 18:54 switch.py
-rw-r--r-- 1 pi   pi   3111 ago 17 18:54 sensor.py
-rw-r--r-- 1 pi   pi    264 ago 17 18:54 manifest.json
-rw-r--r-- 1 pi   pi   3583 ago 17 18:54 light.py
-rw-r--r-- 1 pi   pi   6612 ago 17 18:54 __init__.py
-rw-r--r-- 1 pi   pi   4746 ago 17 18:54 cover.py
-rw-r--r-- 1 pi   pi   1203 ago 17 18:54 common.py
drwxr-xr-x 2 root root 4096 ago 17 18:57 __pycache__

can you please help me?

**Comment by albertogeniola** [comment]
Hi Maurizio,
In order to reproduce the error, could you please tell me the exact installation steps you followed for the custom component installation?

**Comment by MaurizioB84** [comment]
Hi Alberto,
1- create custom_components directory
2- copy the downloaded file into it
3- configure secrets
4- configure yaml file

**Comment by albertogeniola** [comment]
Alright, seems ok. Can you specify the OS version, python version and
docker version you are using? So far I was unable to reproduce the error on
a Linux Ubuntu VM...

**Comment by MaurizioB84** [comment]
docker-compose version 1.24.1, build 4667896 on raspbian (PI3)
Python 2.7.16

**Comment by albertogeniola** [comment]
Could you try using python3?

**Comment by Srmessiha** [comment]
Hello Alberto,
Thank you very much for this plugin.
I have the same issue: Integration not found: meross_cloud
I am running hassio on PI3+ 
ver 0.97.2
the path for meross_cloud directory is: hassio/config/custmo_components/meross_cloud (where I have also HACS and it works with no problem)
configuration.yaml has been modified
![image](https://user-images.githubusercontent.com/45798852/63651304-48c18100-c721-11e9-8428-7f78b6ce3586.png)
However, when I use CHECK CONFIG, I get:
Configuration invalid
Integration not found: meross_cloud
Any idea how to correct this issue?

Also, does your plugin support Meross 3 way switch MSS550?

Thanks in advance

**Comment by Srmessiha** [comment]
Ok, I figured it out. Restarting HA from the HA was not enough, I had to physically disconnect the power, wait for a few minutes and then connect it again. Then everything worked perfectly.

**Comment by whittssg** [comment]
@Srmessiha Thanks so much for this comment.. I had tried everything to get this work on hassio to no avail but after pulling the power it worked first time :)

**Comment by Smoz** [comment]
@Srmessiha worked for me!

**Comment by Rare5808** [comment]
Nice! thanks for the help
