### ISSUE TITLE
[question] is meross-homeassistant throttling the calls to the MEROSS cloud?

### ISSUE THREAD

**Issue by wsw70** [albertogeniola/meross-homeassistant#130]
I am investigating the strange behaviour of my lights, all of them being connected to a MEROSS strip. The full description is at https://community.home-assistant.io/t/what-could-be-the-reason-for-delays-in-successive-events/223837/7?u=wojwoj but in essence:
- when I toggle the switch of a single entity of a group - the toggle is instantaneous
- when I toggle the whole group - there are visible delays.

Please see https://imgur.com/w2MPNck for an animated demo.

I was wondering whether your component would be throttling the calls to the cloud, leading to such a behaviour?

**Comment by albertogeniola** [comment]
Hi @wsw70 ,

that is how it works by design, due to the software architecture of the component. The master switch "propagates" differently to sub-switches and you should expect 0.5~1 seconds delay. That is not a matter of API throttling.

**Comment by wsw70** [comment]
Thanks @albertogeniola for the answer.

Would you be so kind and elaborate a bit on that? The thing is that I see an immediate reaction when I trigger
- one specific switch from HA. 
- switches quickly via the MEROSS app

It is only slow (per my animated gif) when all of them are switched by HA (either via the switch in Lovelace, or via AppDaemen which makes a set of quick  requests for all the switches on the strip).

It looks like as if the requested were queued up and then actually sent to the API with some delay. Is this right?
If so - what is the reason behind this?

I am really curious as I really appreciate your component very much and would like to understand its design and its consequences.

**Comment by albertogeniola** [comment]
> It looks like as if the requested were queued up and then actually sent to the API with some delay. Is this right?
> If so - what is the reason behind this?

It's not. The command sent to the device tells it to shut everything off. In general, the meross plugin sends the command and waits the server to send back the "ack" or the "status changed" event. When switching the master switch, all the switches change their state, and each one sends an event back. Thus, the server is sending back 3 distinct events, that are somehow received on the client (Homeassistant) sequentially. 

I hope I made it clear.

**Comment by wsw70** [comment]
> When switching the master switch ...

Yes, if switching the master switch I agree. But I send the request to each of the sockets (of the strip) independently. I never use the master switch.

**Comment by albertogeniola** [comment]
In that case, the new async architecture of the component will queue the requests (there is only a single connection against the Meross MQTT broker, so messages are sent one by one). A delay between a call and the next one is only added in particular cases, when the polling frequency (we are talking about sensors here, not actuators) goes above a certain threeshold, to prevent flooding. If your goal is to switch off all the sockets on the same strip, you should rely on the switch 0 (master switch), which will actually send a single command and will cause multiple event notifications being emitted by the broker (but the action happens on the strip like as it was atomic).
