### ISSUE TITLE
Meross MSS425F

### ISSUE THREAD

**Issue by SebastienVanRintel** [albertogeniola/meross-homeassistant#131]
Hi Alberto,

I see that MSS425**E** is supported but I can't find any references to MSS425**F**.
Is MSS425**F** also supported by the HA component?

Thank you for all the hard work.

Kind regards,
Sébastien

**Comment by chpego** [comment]
Hello Sébastien,
It seems to work, I managed to integrate my MSS425F plug I bought a few days ago. All the 4 sockets + the USB socket + all the sockets are controllable from HA.
Maybe @albertogeniola can add this reference (MSS425F) in supported device
Anthony

**Comment by albertogeniola** [comment]
Hi Anthony,

Good to hear that. Thanks for the report.

Alberto

**Comment by SebastienVanRintel** [comment]
Hi Anthony,

Thank you for verifying.

Sébastien
