### ISSUE TITLE
Unable to prepare setup for platform meross_cloud.sensor: Platform not found (cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).

### ISSUE THREAD

**Issue by coolguymatt** [albertogeniola/meross-homeassistant#133]
I upgraded to the 0.115 beta, and the meross_cloud integration gives this error:

```
Log Details (ERROR)
Logger: homeassistant.setup
Source: setup.py:280
First occurred: 8:12:17 AM (1 occurrences)
Last logged: 8:12:17 AM

Unable to prepare setup for platform meross_cloud.sensor: Platform not found (cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
```

I do not have any meross sensors (just a garage door opener) and my devices work perfectly.

**Comment by albertogeniola** [comment]
HI @coolguymatt ,

thanks for the spot. I've prepared a fix for the next version of the component

**Comment by albertogeniola** [comment]
Can you try version 1.0.1 (Pre Release)?

**Comment by coolguymatt** [comment]
Same issue with v1.0.1rc

**Comment by albertogeniola** [comment]
I see. However 0.115 is still in beta and it's unclear how will it evolve. Let's wait for the 0.115 release first.

**Comment by totalitarian** [comment]
Is this why my sensors won't appear. I can see my smart plugs but not the power sensors such as

`sensor.washing_machine_mss310_power_sensor_w_0`

I'm running 0.115

**Comment by roger-rainey** [comment]
I know that home-assistant has removed UNIT_PERCENTAGE and replaced it with PERCENTAGE. Older code has been changed to reflect it. I added UNIT_PERCENTAGE back into const.py and it works again but removing it is needed.

**Comment by iammurdock92** [comment]
updated to 1.0.2, all working now, thanks!
