### ISSUE TITLE
Integration does not show up after installing component

### ISSUE THREAD

**Issue by qvdm** [albertogeniola/meross-homeassistant#135]
Installed meross-homeassistant via HACS.  Restarted Home Assistant.  The only log entry is:
2020-09-15 22:05:21 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for meross_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

The Meross component is not available under integrations.  

Any suggestions for where to start debugging the issue would be appreciated

**Comment by lincolnaleixo** [comment]
same here

**Comment by Marcossi** [comment]
same here

**Comment by Mega-Touk** [comment]
I have the same problem. it was working on my previous install but since I wiped my raspberry pi to restart from fresh, meross wont show up on the integration list.

I installed via HACS

**Comment by Mega-Touk** [comment]
It is working by manual setup via configuration.yaml like this

```
meross_cloud:
  username: meross_username
  password: meross_password
```

even if this method has been deprecated since b4d24505ebeeec9bac2ca4f89bcb39d38996bed7

**Comment by lincolnaleixo** [comment]
After the new update, I was able to integrate without any problem!

**Comment by albertogeniola** [comment]
I am glad you solved it!
