### ISSUE TITLE
The current power does not work

### ISSUE THREAD

**Issue by diazdeespada** [albertogeniola/meross-homeassistant#139]
Since the last update, the sensor disappeared, but the attribute associated with the switch shows the reading after a boot and is not updated

**Comment by BenLaeft** [comment]
Same problem here :(

**Comment by BenLaeft** [comment]
Any news ?

**Comment by albertogeniola** [comment]
Hi, can you try the [latest development ](https://github.com/albertogeniola/meross-homeassistant/releases/tag/1.0.4-dev1) release and tell me if that still happens?

**Comment by BenLaeft** [comment]
Hello Alberto,

Sure I can try, but sorry as a newbie, I don't know how to install this release ?
Can you precise how to proceed ?

**Comment by BenLaeft** [comment]
I updated with HACS from 1.0.0 to 1.0.3 avec power sensor seems to work again.
Thanks

**Comment by albertogeniola** [comment]
Glad that works!
