### ISSUE TITLE
[Suggestion] Added custom name for plug as friendly_name

### ISSUE THREAD

**Issue by ping-localhost** [albertogeniola/meross-homeassistant#14]
First of all, thank you very much for making this integration. It works great!

However, I would like to suggest adding the custom name I've set in the app as the `friendly_name` in Home Assistant. That way I know what exactly is connected to `switch.stekkerdoos_channel_0`, since I've set it in the Meross app already.

----

I would also like to suggest to use different icons (as everything is currently `mdi:flash`). In my [custom component](https://github.com/ping-localhost/meross-custom-component) (which is now archived, since I prefer using this one), I've used `mdi:usb` for the USB socket (channel 4 on the MSS425e), `mdi:power-socket` for all the sockets (channel 1, 2 and 3) and the regular `mdi:flash` for the whole plug itself (channel 0). [I used a basic type check to do this.](https://github.com/ping-localhost/meross-custom-component/blob/master/custom_components/meross/switch.py#L60)

**Comment by albertogeniola** [comment]
Hi @ping-localhost ,

I like your suggestion. Feel free to propose a pull-request if you know where to start.
