### ISSUE TITLE
White mode not working well

### ISSUE THREAD

**Issue by SLiK420** [albertogeniola/meross-homeassistant#140]
For my meross bulbs, I find I need to use the colour temperature slider to access white mode, there's no way to select it for automations. EG, I want to use a 5000k light for my office day mode, but when trying to create the automation, I can't get it to save white mode, when using the automation the lights default to an RGB version of white.

**Comment by tahlequawesome** [comment]
I have this as well, only since 1.0 update. My automations and scenes now ignore white settings and turn light (msl120b) on with a default cold bluish white. 
Prior to 1.0 update these same lights functioned normally.
Post 1.0 update I have a set of msl120j lights that do light up according to scene settings though.

**Comment by SLiK420** [comment]
> I have this as well, only since 1.0 update. My automations and scenes now ignore white settings and turn light (msl120b) on with a default cold bluish white.
> Prior to 1.0 update these same lights functioned normally.
> Post 1.0 update I have a set of msl120j lights that do light up according to scene settings though.

To further this, I have noticed this too. I realized that I tried to modify the scene that isn't working after updating to 1.0. The ones that are working haven't been touched since before the upgrade.

**Comment by wilflet1986** [comment]
I also have a pair of msl120j that I set to an incandescant white in scenes, save and then when it recalls its just the horible RGB "white"

**Comment by stetsonandblack** [comment]
Any news on this? I just go meross bulbs and I get the exact same behavior!

**Comment by cuddlah** [comment]
Same issue here, but not on all meross bulbs - only some of them.

**Comment by wnlowe** [comment]
Bumping with same issue on msl320cpr. Scenes only holding color from color selector, not temperature selector.
