### ISSUE TITLE
Too many requests - EMail from Meross Cloud

### ISSUE THREAD

**Issue by Biliskn3r** [albertogeniola/meross-homeassistant#141]
Hello, I updated the HA plugin when it was released a few days ago. However, today I got this Email.

Is there any way to decrease the polling time?

Thanks for all your work on this btw; great job.

![Annotation 2020-09-23 191910](https://user-images.githubusercontent.com/44535481/94053052-b97a1780-fdd1-11ea-8670-bff70c6562b6.png)

**Comment by yauyauwind** [comment]
Hi All,

I got the same issue, and now the account still suspended
Seem 1.02 trigger the meross suspend account, I roll back to 1.0 and wait Meross release my account LoL

Anyway, Thank you for your work~~

**Comment by albertogeniola** [comment]
Hi guys,

latest version of the component should address this issue. Update the HA component and then send an email to the meross cloud so that they unban your accounts.

**Comment by ferdinandovivacqua** [comment]
Hi all, I have the same problem, with the last component release. Is there any workaround?
