### ISSUE TITLE
Meross device unavailable 

### ISSUE THREAD

**Issue by fernando155** [albertogeniola/meross-homeassistant#143]
Good morning.

Yesterday meross tell me that I have 3 devices to update (3 smart plugs with meter reading). Since I update them, all meross devices went unavailable every few hours and I have to restart ha to start them again. 

Ha version 114.4
Meross last uodate available

**Comment by odisseo79** [comment]
I confirm the issue with latest Meross integration and HA version 0.115.3

Following the error in HA logs for one of the devices.


Logger: custom_components.meross_cloud.sensor
Source: custom_components/meross_cloud/sensor.py:321
Integration: Meross Cloud IoT (documentation)
First occurred: 02:40:53 (1 occurrences)
Last logged: 02:40:53
Error occurred. ------------------------------------- Component version: 0.4.0.1 Device info: Name: Lavastoviglie UUID: 18110514975236251a09342****** Type: mss310 HW Version: 2.0.0 FW Version: 2.1.15 Error Message: "An exception occurred"

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 536, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 321, in _sensor_async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/electricity.py", line 38, in async_get_instant_metrics
    result = await self._execute_command("GET", Namespace.CONTROL_ELECTRICITY, {'channel': channel})
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 196, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 527, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 540, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError

**Comment by MalagaInternet** [comment]
+1

**Comment by sk8er000** [comment]
I've got 7 mts100v3 and a mss425e but the mts100v3 becomes randomly unavaiable after a while, I i try to change the mode (for example from WARM to COOL) the devices connect again, same result if I reboot Home Assistant. The mss425e device seems to not be affected.

**Comment by weado** [comment]
+1

**Comment by ellite** [comment]
Same issue. All my Meross devices become unavailable after a couple of hours, restarting HA brings them back.

**Comment by ellite** [comment]
As a workaround, I added an automation to restart HA when Meross devices become unavailable. Seems to work well. Not ideal, but it works. Here's the code if anyone is interested.
`- id: '1601761506419'
  alias: Restart Home Assistant when Meross becomes unavailable
  description: ''
  trigger:
  - platform: state
    entity_id: climate.living_room_mts100v3
    to: unavailable
    for: 00:02:00
  condition: []
  action:
  - service: homeassistant.restart
    data: {}
  mode: single`

**Comment by tngarner** [comment]
+1 on this issue.

**Comment by djxplor** [comment]
Same issue here

**Comment by eruisi** [comment]
Same issue. Please provide a fix. Appreciate it. 
Meross app works totally fine.

**Comment by djxplor** [comment]
No issues in the last 18 hours following upgrade to HA 0.116.2 and Meross 1.03 both just released.

**Comment by eruisi** [comment]
Yes upgrading to latest version of HA and Meross fixed my issue. Thanks a lot
