### ISSUE TITLE
HomeAssistant - New version for LAN-only control

### ISSUE THREAD

**Issue by albertogeniola** [albertogeniola/meross-homeassistant#144]
## Why a LAN-local plugin?
As many of you guys have noticed, **Meross applies strong limitations** on API call rates. When polling aggressively the Mqtt broker (e.g. sensors polling), Meross will likely susped the user's account (#93, #141, #92, #109). **This is a killer for many use-cases**. Moreover, many users are also concerned about letting the meross device talk to the internet becoming - possibbly - attack vectors for their LAN. Lastly, there are some users who want to be able to control their meross device over the lan, without relying on a stable internet connection. 

In order to address all these problems, **I would like to rewrite the Meross Homeassistant** plugin so that they connect to the Homeassistant Meross Broker. 

## What has to be done?
Many things. First of all, the underlying library must be adapted/tested to only work with LAN-local mqtt broker. This means removing the HTTP Api functionalities that the current implementation uses. **Another important part of the project consists in the creation of an application** (Android) that allows the registration of the meross physical devices with the HA broker. 

## How long will it take?
Probably **several months**, but this also depends on the success this project gets: the more, the better.

## What can I do to help?
Firstly, alpha and beta testers will be very welcome. People who are not scared of breaking their HA installations are definetely the ones who can help. Of course, **any economical help (donations, sponsorships) motivates my work** and allows me to buy the required licenses, hardware and devices to be tested, not to mention the electricity bill that keeps the automated tested environment constanlty on. 

## Status
- [**MOSQUITTO CONNECTION**] I successfully configured a MSS210 plug to connect to a lan-local mosquitto MQTT broker. The plug does not preset itself with a client-certificate, but requires the server to use TLS and a CA/SERVER certificate (which is not validated in any way on the plug's side, that's simply ridicolous)
- [**HA BROKER CONNECTION**] The HA mosquitto broker either allows anonymous access (no user-password must be sent by the client) or HA-local users. The plug's client will always connect specifying as as username its mac-address and a password that is derived by the mac-address, the Meross userid and the Meross Key. This prevents anonymous access to work (as it's using explicit user-password) and at the same time, the user validation fails, as there is no HA user named with that MAC Address.
By adding the explicit user-password credentials for that plug, the connections succeeds. 
It would be unpractical to add credentials for every device that the user is willing to connect, thus we need to identify a way for making anonymous connection work even if username/password credentials are provided by the client.

**Comment by maxcanna** [comment]
Great great news! I can't wait to try it!

What about avoiding to develop an android app to speed up the process? The app could be replaced by a CLI tool to save time and be useful to more users (i.e. iOS users).

Just my 2 ct

**Comment by Biliskn3r** [comment]
As it is, i have a dev sandbox of my HA - so alpha test, here we come.

**Comment by dafonehacker** [comment]
Can I run a 'production' instance and a test instance on the same meross devices? Example: I have my main HomeAssistant that has to stay in a working state, but also have a test server on which I can run another HomeAssistant instance on which I can help testing the local LAN implementation... Can these be run side by side? Or do we have to modify the meross devices for the LAN implementation to work?

**Comment by JenniferHatches** [comment]
Happy to help test!

**Comment by lukejagger** [comment]
Happy to help too.  I am a developer, mainly C++, Java, some Javascript.   Or just to test an alpha version.

**Comment by coolguymatt** [comment]
Not sure if you have seen this?

https://wltd.org/posts/how-to-use-meross-smart-devices-as-cheap-offline-iot

**Comment by lukejagger** [comment]
Forgot to metion, I have a contact within Meross who has always been very responsive and helpful, if you need me to contact them I can.

**Comment by MaxCere** [comment]
I'm evaluating Meross purchasing as seems to be the only "Italian Friendly Plugs" out there...but relay on a CLOUD service is a stop for me for many resons. What is the status of this feature? I'm ready to help obviously with testing.

**Comment by albertogeniola** [comment]
Hi guys, 

I'm working on it by implementing the low-level library this component requires to talk with Meross Devices. The project is ongoing [here](https://github.com/albertogeniola/MerossIot/projects/2), in case you are curious.

**Comment by k1200s** [comment]
Will this LAN ONLY option require the Meross units to be HomeKit compatible?

**Comment by DeamBeam** [comment]
I would like to help you as a tester.

**Comment by dragon2611** [comment]
I currently have an MSS310 sitting on my desk that was part of a multipack, I also have a MOSQUITTO broker running in a docker container already as I use Zigbee2mqtt with home-assistant.

I'll need to reconfigure it to listen for TLS connections but that shouldn't be particularly difficult.

Regarding the cloud rate limits, I had a quick look at the code and it looked like communication with the meross cloud was over HTTP, I'm guessing that Meross won't allow the plugin to connect directly to their MQTT infrastructure as if they did it may be possible to subscribe to certian topics and avoid polling?

Until I have a bit more time to look into it further I don't know if the Plug exposes the required information over MQTT or if some of it is over a HTTP api.

**Comment by wsw70** [comment]
@dragon2611 

> I'll need to reconfigure it to listen for TLS connections but that shouldn't be particularly difficult.

I solved that by using caddy (https://caddyserver.com/) as a proxy (I use it for all my docker files) - the transformation from `ws://...` to `wss://` is automatic and the handling of certificates is seamless (built-into caddy)

**Comment by ChrisPiel70** [comment]
Hello Alberto,

tried to buy you some coffee yesterfday (over "Buy me a coffee" for the LAN-only Control Project but the site won't accept my MC. Is Paypal possible?

Keeep up the great work.
Regards
Chris

**Comment by dragon2611** [comment]
> @dragon2611
> 
> > I'll need to reconfigure it to listen for TLS connections but that shouldn't be particularly difficult.
> 
> I solved that by using caddy (https://caddyserver.com/) as a proxy (I use it for all my docker files) - the transformation from `ws://...` to `wss://` is automatic and the handling of certificates is seamless (built-into caddy)

The MQTT broker needs to support TLS for the merros device to connect.

I managed to get the MSS310 to connect to my broker although I seem to be very good at crashing it and causing a reset

https://theriom.com/homeautomation/2020/08/04/meross-switch-with-openhab.html seems to suggest sending a 0 or a 1 to the subscribe topic should switch it but if I do that I hear the relay click and then the plug reboots.

I do see some JSON messages present on the publish topic that could probably be read for the power consumption data, although I've not yet looked at parsing them to get the values we want.

**Comment by wsw70** [comment]
@dragon2611 

> The MQTT broker needs to support TLS for the merros device to connect.

You mean that the connection is done directly on the MQTT protocol and not through WS that could be proxified, right?

**Comment by dragon2611** [comment]
> @dragon2611
> 
> > The MQTT broker needs to support TLS for the merros device to connect.
> 
> You mean that the connection is done directly on the MQTT protocol and not through WS that could be proxified, right?

The Meross device is talking MQTT as to if it also has a websocket connection I don't know.

https://github.com/skullydazed/meross_mqtt_ha seems interesting although I can't seem to get it to work, it's connecting to the broker but doesn't appear to be doing much.

**Comment by dragon2611** [comment]
I followed the suggestion to reset and pair the plug using bytespider's utility, I'm not sure if meross_powermon set a shared key but either way it's working now, Just basic on/off no power info but still it's being controlled locally 👍

**Comment by wsw70** [comment]
@dragon2611 : have you had any problems with the cipher used by the MEROSS device? I get on my MQTT (TLS-enabled with a LE cert) 

```
609179089: New connection from 192.168.10.103 on port 8883.
1609179089: OpenSSL Error[0]: error:140270C1:SSL routines:ACCEPT_SR_CLNT_HELLO_C:no shared cipher
1609179089: Socket error on client <unknown>, disconnecting.
```
It seems that the cipher that is requested by the device is not part of the list offered by Let's Encrypt (but I can force some)

**Comment by dragon2611** [comment]
Nope, that said looking at the docs for https://github.com/bytespider/Meross it may be possible to make an insecure connection.

Also lets Encrypt doesn't control the ciphers, your configuration will.

**Comment by wsw70** [comment]
Thanks for the follow-up.

> Also lets Encrypt doesn't control the ciphers, your configuration will.
Yes, I meant mosquitto (my MQTT broker),  not LE)

> (...) it may be possible to make an insecure connection 
I tried to make an insecure connection but it failed (it set up a TLS one). I will look at that in detail tonight.

**Comment by dragon2611** [comment]
I don't think I set anything explicitly, this is my TLS listener

```

listener 8883
cafile /mosquitto/config/certs/mqtt_ca.crt
#capath
 
 require_certificate false
    use_identity_as_username false
    allow_anonymous true

    capath /mosquitto/config/certs/

# Path to the PEM encoded server certificate.
certfile /mosquitto/config/certs/mqtt.crt

# Path to the PEM encoded keyfile.
keyfile /mosquitto/config/certs/mqtt.key
```

**Comment by wsw70** [comment]
@dragon2611 thanks.

I had a look at the tcpdump traffic to the broker and the offered ciphers matched the ones that were requested. I gave up on LE and generated my own.

It worked, I managed to connect the plug and when manually changing its state (via the push button), I see it publishing an elaborate payload to the broker.

```
{
  "header": {
    "messageId": "155aca3b2d9c25d26671ab0448508c30",
    "namespace": "Appliance.Control.ToggleX",
    "method": "PUSH",
    "payloadVersion": 1,
    "from": "/appliance/2006176333738751801348e1e91fb91a/publish",
    "timestamp": 1609185006,
    "timestampMs": 148,
    "sign": "690f0ce6c3519d55ff9c83e81f54ba1a"
  },
  "payload": {
    "togglex": [
      {
        "channel": 0,
        "onoff": 0,
        "lmTime": 1609185005
      }
    ]
  }
}
```

How did you generate the payload you send to switch it on/off? While most of the fields seem straightforward, I belive that the  `sign` one must be calculated (at least I did not manage to make the plug react by sending the same)

**Comment by dragon2611** [comment]
That's the same error I had when I'd configured it with meross_powermon, I reset the plug and used https://github.com/bytespider/Meross leaving the shared key blank and then it worked.

Not srue if meross_powermon is setting the shared key if it's I have no idea what to.

**Comment by albertogeniola** [comment]
Hi guys, 
I've created a simple Android app which should help when pairing Meross devices with [custom MQTT brokers](https://github.com/albertogeniola/MerossIot/issues/162). Give it a try!

**Comment by albertogeniola** [comment]
Hi all, a new version of the APP is out: if you want to become a tester don't hesitate to apply! You can become a tester on Android by [visiting this link](https://play.google.com/apps/testing/com.albertogeniola.merossconf).

**Comment by wsw70** [comment]
> You can become a tester on Android by [visiting this link](https://play.google.com/apps/testing/com.albertogeniola.merossconf).

It seems (at least for me) that there is a problem with the visibility of the app:

![image](https://user-images.githubusercontent.com/1345886/124447791-01c35e80-dd82-11eb-976f-67fbb9467ad6.png)

(this says that the application is not available)

**Comment by albertogeniola** [comment]
Hi @wsw70 ,
you're right. The app needed to be opened to "public testing". I've just promoted it to the next stage, [you will find it here](https://play.google.com/apps/testing/com.albertogeniola.merossconf) as soon as the Google Play review process is completed. Please try again this afternoon!

**Comment by C0ntroller** [comment]
> [HA BROKER CONNECTION] The HA mosquitto broker either allows anonymous access (no user-password must be sent by the client) or HA-local users. The plug's client will always connect specifying as as username its mac-address and a password that is derived by the mac-address, the Meross userid and the Meross Key. This prevents anonymous access to work (as it's using explicit user-password) and at the same time, the user validation fails, as there is no HA user named with that MAC Address.
By adding the explicit user-password credentials for that plug, the connections succeeds.
It would be unpractical to add credentials for every device that the user is willing to connect, thus we need to identify a way for making anonymous connection work even if username/password credentials are provided by the client.

At the beginning I want to say I could be absolutely wrong. But the process to add the client will be over an app at any given point right? Or if you manage to get it running in HA only it will be by an python script. So if we could add users for the MQTT broker it works, right?

So first: Do we have to use the vanilla HA MQTT broker? Because if not you could add more users in the docker container without having an home assistant user named like the MAC. 

Second: If you can add users without the need to add them to HA you can modify the docker container further and get an microservice like an HTTP server running - that accepts requests to add users. For security there should may be a check if the input credentials really are username and derived password so noone can send random things there to get access to the MQTT (for whatever reasons). After the microservice received new user data, checked them and added them it maybe has to restart the MQTT server (but I really don't know if thats necessary).

Does this sound possible in any way?  @albertogeniola

**Comment by wsw70** [comment]
> Hi all, a new version of the APP is out: if you want to become a tester don't hesitate to apply! You can become a tester on Android by [visiting this link](https://play.google.com/apps/testing/com.albertogeniola.merossconf).

It's been some time I have not used the pairer but I need to have someone use it to reonfigure a few plugs.

When looking at the screenshots, it seems that there is not more a way to simply provide 
- a WiFi SSID
- the MQTT IP

to the device? (without any other integration, just have it communicate with the MQTT broker)

**Comment by dragon2611** [comment]
It could do that when I last used it (Which was within the past couple weeks) I think there was a button for manual, you may need to set account but just put a dummy value in,

Then goto pair on the menu, it should search for devices, once it's found one and asked for the Wi-Fi settings it should prompt you for MQTT settings.

**Comment by wsw70** [comment]
> It could do that when I last used it (Which was within the past couple weeks) I think there was a button for manual, you may need to set account but just put a dummy value in,
> 
> Then goto pair on the menu, it should search for devices, once it's found one and asked for the Wi-Fi settings it should prompt you for MQTT settings.

Ah; I just found a plug! I tried with the app I have installed (version 0.0.1-alpha4) and the connection is straightforward (just the wifi and MQTT). What I am afraid of is that it looks nothing like the one on Google Play (despite the right version).

I will (remotely) see what happens when my brother installs it and tries to reconfigure a plug on his side.

**Comment by silkyclouds** [comment]
Guys, It might sound stupid but with the latest version of MEross local broker, how do I enable TLS and listening on port 8883 ? I can't get my MSS310 to connect: (
