### ISSUE TITLE
Meross integration problems after a year of flawless operation

### ISSUE THREAD

**Issue by elijah286** [albertogeniola/meross-homeassistant#146]
After months of flawless operation, I’ve been having regular problems with the HA integration of Meross.

One of the door controllers will show as ‘unavailable’ in HA, even though everything works perfectly from the Meross app. It’s always only one of the two doors, but it’s random as to which one it is.

It will eventually come back by itself or I can force it to come back by rebooting HA and/or resetting the Meross plugin.

I’ve already tried the following:

1. Removing the Meross entities
2. Removing the Meross entities, renaming them in the Meross app, reconnecting them
3. Uninstalling/reinstalling/reconfiguring the doors via the HACS integration

I can’t say for sure, but I think these problems started after one of the many HA upgrades in the last month or so.

Any help or pointers would be appreciated!

**Comment by elijah286** [comment]
I'm running 1.0.2

**Comment by iMiMx** [comment]
Just started to see the same and starting to investigate - not using Unifi WiFi as well by any chance are you?  Just curious, as I updated the firmware on these recently.

Restarting HA seems to fix it for me, temporarily,

**Comment by elijah286** [comment]
No, I’m using the TP Link Deco APs with a hard wired backbone

**Comment by dafonehacker** [comment]
I have a similair issue, my garage door opener will sometimes become unavailable.  My smarr light switch that is connectes to the same account keeps working though

**Comment by dafonehacker** [comment]
I have a similair issue, my garage door opener will sometimes become unavailable.  My smarr light switch that is connectes to the same account keeps working though

**Comment by iMiMx** [comment]
It might be a fluke, so far, but yesterday I clicked 'Reinstall' on this plugin in HACS (1.0.2 version), then restarted Home Assistant. 

14 hours later, it hasn't (yet) gone to unavailable.

**Comment by bocaditos** [comment]
Hola. En el último HA sigue funcionando, pero en el log salta un error de que la entidad no funciona

**Comment by albertogeniola** [comment]
Hi @elijah286,
which version of Homeassistant are you runnig?

**Comment by tankqj** [comment]
I had the same issue two days in a row.  Only one of the Meross Garage doors would go to unavailable status.  It also seemed to happen every morning at 3 AM MT.  I would restart Home Assistant and it would come back.  I did the suggestion choosing Reinstall and rebooting HA.  Today it hasn't done it yet.

**Comment by elijah286** [comment]
just upgraded to 116.2 and still having the issue

**Comment by horego** [comment]
I'm on the newest version and have the same issue

**Comment by tankqj** [comment]
It came back again for me.  Again it went down at 3 AM.
![image](https://user-images.githubusercontent.com/33711337/96002343-3e1aed00-0df6-11eb-99c8-152b739b1565.png)

**Comment by juanpa669** [comment]
The same here, losing connection to Meross devices. Before and after the new version of Meross

**Comment by tobydriver** [comment]
Same here. New version of Meross and HA 116.2.

**Comment by eruisi** [comment]
I got "unavailable" too this morning, but I still feel upgrading HA/Meross
improve the situation a lot. Previously it becomes "unavailable" every
30mins or so.

Now it is once/twice every day.

**Comment by shra1976** [comment]
With 0.116.0 I had the issue then it was solved but today it became not available again with 0.116.2

**Comment by shra1976** [comment]
Still having problems! My devices still unavailable from Home Assistant. From app i could reach them. I've tryed to log off and then login again to the account in the app and now the device are unavailable on the app too. Anyone know what happens?

**Comment by DanoneKiD** [comment]
Hi, same issue for me.
All of my plugs become unavailable after a while.

```
Logger: meross_iot.manager
Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:665
First occurred: 16 octobre 2020 à 11:32:47 (94 occurrences)
Last logged: 18 octobre 2020 à 14:37:09

Timeout occurred while waiting a response for message b'{"header": {"from": "/app/68269-87427614929fd54cb99099b25e395a77/subscribe", "messageId": "edc53a14518e18b82eea2c3a3c9b9744", "method": "GET", "namespace": "Appliance.Control.Electricity", "payloadVersion": 1, "sign": "559acd3a6df1b54672fad4e5830bac8b", "timestamp": 1603024589}, "payload": {"channel": 0}}' sent to device uuid 1809015826590225180434298f165fc8. Timeout was: 5 seconds
Timeout occurred while waiting a response for message b'{"header": {"from": "/app/68269-87427614929fd54cb99099b25e395a77/subscribe", "messageId": "55291bc62d83279f9a42ef1184e4ff77", "method": "GET", "namespace": "Appliance.Control.Electricity", "payloadVersion": 1, "sign": "37cf17069a414653b8d1d232638f55b4", "timestamp": 1603024594}, "payload": {"channel": 0}}' sent to device uuid 1809015826590225180434298f165fc8. Timeout was: 5 seconds
Timeout occurred while waiting a response for message b'{"header": {"from": "/app/68269-87427614929fd54cb99099b25e395a77/subscribe", "messageId": "54857a052d461205c3046ea82c33cf65", "method": "GET", "namespace": "Appliance.Control.Electricity", "payloadVersion": 1, "sign": "bcf37b858ef935e2b4afe376c3955429", "timestamp": 1603024599}, "payload": {"channel": 0}}' sent to device uuid 1809015826590225180434298f165fc8. Timeout was: 5 seconds
Timeout occurred while waiting a response for message b'{"header": {"from": "/app/68269-87427614929fd54cb99099b25e395a77/subscribe", "messageId": "3e7e4a871eb0bd4942e0ffcf15611e01", "method": "GET", "namespace": "Appliance.Control.Electricity", "payloadVersion": 1, "sign": "357d54b77c03ba4ee0f4ad29284b4904", "timestamp": 1603024619}, "payload": {"channel": 0}}' sent to device uuid 1809015826590225180434298f165fc8. Timeout was: 5 seconds
Timeout occurred while waiting a response for message b'{"header": {"from": "/app/68269-87427614929fd54cb99099b25e395a77/subscribe", "messageId": "83f08f54ba5aba732f9d44e96d7a745e", "method": "GET", "namespace": "Appliance.Control.Electricity", "payloadVersion": 1, "sign": "429107767da36d90b0d4c305b1bccdac", "timestamp": 1603024625}, "payload": {"channel": 0}}' sent to device uuid 1809015826590225180434298f165fc8. Timeout was: 5 seconds
```

```
Logger: custom_components.meross_cloud.sensor
Source: custom_components/meross_cloud/sensor.py:285
Integration: Meross Cloud IoT (documentation)
First occurred: 16 octobre 2020 à 11:32:52 (26 occurrences)
Last logged: 18 octobre 2020 à 14:37:09

Error occurred. ------------------------------------- Component version: 0.4.0.5 Device info: Name: Bureau Julien UUID: 1809015826590225180434298f165fc8 Type: mss310 HW Version: 2.0.0 FW Version: 2.1.13 Error Message: "An exception occurred"
Error occurred. ------------------------------------- Component version: 0.4.0.5 Device info: Name: Bureau Marina UUID: 1809015687848525180434298f165f3c Type: mss310 HW Version: 2.0.0 FW Version: 2.1.13 Error Message: "An exception occurred"
Error occurred. ------------------------------------- Component version: 0.4.0.5 Device info: Name: Sèche linge UUID: 1809018489534725180434298f16607c Type: mss310 HW Version: 2.0.0 FW Version: 2.1.13 Error Message: "An exception occurred"
Error occurred. ------------------------------------- Component version: 0.4.0.5 Device info: Name: TV Salon UUID: 18071978762901251a0534298f1370a5 Type: mss310 HW Version: 1.0.0 FW Version: 1.1.18 Error Message: "An exception occurred"
Error occurred. ------------------------------------- Component version: 0.4.0.5 Device info: Name: Piscine UUID: 1801166197252825131634298f110ef1 Type: mss310 HW Version: 1.0.0 FW Version: 1.1.18 Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 663, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 285, in _sensor_async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/electricity.py", line 38, in async_get_instant_metrics
    result = await self._execute_command("GET", Namespace.CONTROL_ELECTRICITY, {'channel': channel})
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 207, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 654, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 667, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError
```

**Comment by MartnIV** [comment]
I'm also keeping having the issue with Home Assistant 0.116.4 and Meross IoT 1.0.3

**Comment by undy27** [comment]
Same issue here with HA 0.116.4. I don't know how to check which Meross integration version is running, but I think it's 1.03

**Comment by facaldoggi** [comment]
Same issue here with my garage door opener MSG-100. All good on the app side, but on HA randomly some of the devices go off-line. Need to restart HA to get them working again... for a while.

Keep up the good work!

**Comment by tahlequawesome** [comment]
For those of you with the MSG-100, when the device appears unavailable in HA and you open or close a door in the Meross mobile app does it become available for a while in HA without an HA restart? Mine does.

**Comment by elijah286** [comment]
Yes! Never noticed that until I tried it just now. Sure enough, the garage door showed up again as soon as I activated it from the meross app. 

Here’s a video in case it helps with debugging: 
https://www.icloud.com/sharedalbum/#B0mGSkLVwGmQkKn

**Comment by shra1976** [comment]
HA 0.116.4, and integration running 1.0.3. No entities found in HA. When logged in with HA the HUB MSH300 begins to disconnect  several times.

**Comment by elijah286** [comment]
Are we any closer to resolution? It’s becoming so frequent that I’m starting to seriously consider alternative garage door controllers

**Comment by undy27** [comment]
As a workaround, reloading the integration fixes the issue for me, temporary at least. Anyone knows how to make a script to automate the reload when an entity is unavailable (or at least, at a fixed time interval)?

**Comment by tankqj** [comment]
I had this working for almost an entire day while using v1.0.6-beta1 and now one of my garage doors went to "unavailable" state.  Here are the logs that occurred right before it went to this state:

`Logger: custom_components.meross_cloud.cover
Source: custom_components/meross_cloud/cover.py:65
Integration: Meross Cloud IoT (documentation)
First occurred: 3:03:29 AM (6 occurrences)
Last logged: 8:29:54 PM

Device Left Garage Door (msg100) - Main channel reported online event.
Device Right Garage Door (msg100) - Main channel reported online event.

Logger: meross_iot.manager
Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:632
First occurred: 3:03:34 AM (2 occurrences)
Last logged: 8:29:59 PM

Timeout occurred while waiting a response for message b'{"header": {"from": "/app/814330-83799fc4ae5f5c16a030236471738aad/subscribe", "messageId": "cf7474d31ca5a9e8ff1da30eb798ed72", "method": "GET", "namespace": "Appliance.System.All", "payloadVersion": 1, "sign": "9ecb8c6f084e7efcf159a04d52ecb045", "timestamp": 1607076209, "triggerSrc": "Android"}, "payload": {}}' sent to device uuid 2006048564537936100248e1e91e40f6. Timeout was: 5 seconds.
Timeout occurred while waiting a response for message b'{"header": {"from": "/app/814330-83799fc4ae5f5c16a030236471738aad/subscribe", "messageId": "5bf4687bb2b29b426071481514d0cdd7", "method": "GET", "namespace": "Appliance.System.All", "payloadVersion": 1, "sign": "d5824b29068b7be96f652967e9f63cd5", "timestamp": 1607138994, "triggerSrc": "Android"}, "payload": {}}' sent to device uuid 2006044869026036100248e1e91e3f52. Timeout was: 5 seconds.

Logger: custom_components.meross_cloud.cover
Source: custom_components/meross_cloud/cover.py:52
Integration: Meross Cloud IoT (documentation)
First occurred: 3:03:34 AM (2 occurrences)
Last logged: 8:29:59 PM

Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: Left Garage Door UUID: 2006048564537936100248e1e91e40f6 Type: msg100 HW Version: 3.5.0 FW Version: 3.1.15 Error Message: "An exception occurred"
Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: Right Garage Door UUID: 2006044869026036100248e1e91e3f52 Type: msg100 HW Version: 3.5.0 FW Version: 3.1.15 Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/cover.py", line 52, in async_update
    await self._device.async_update()
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/system.py", line 21, in async_update
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError`

**Comment by bvansluis** [comment]
> As a workaround, reloading the integration fixes the issue for me, temporary at least. Anyone knows how to make a script to automate the reload so it triggers when an entity is unavailable (or at least, at a fixed time interval)?

I was also looking at this but I haven't found a way to do so. Not sure if individual integrations can be reloaded....

**Comment by Muzza** [comment]
> Yes! Never noticed that until I tried it just now. Sure enough, the garage door showed up again as soon as I activated it from the meross app.

With one garage opener, this integration was working great, so I got a second for an automatic gate and now I have constant problems with one of them being offline (it alternates which one stops working). As soon as I login to the Meross App it comes online again in Home Assistant - every time.

**Comment by andornaut** [comment]
> As a workaround, reloading the integration fixes the issue for me, temporary at least. Anyone knows how to make a script to automate the reload so it triggers when an entity is unavailable (or at least, at a fixed time interval)?

This automation has been working pretty well for me. It retries every minute for up to an hour or until the state is not "unavailable":
```
- alias: Reload Meross when unavailable
  description: Reload the Meross Smart Garage Door service when the connection becomes unavailable. Retry every minute for 1 hours.
  trigger:
    - platform: state
      entity_id: cover.garage_msg100_main_channel
      to: unavailable
      for: 00:00:30
  action:
    - repeat:
        while:
          - condition: state
            entity_id: cover.garage_msg100_main_channel
            state: unavailable
          - condition: template
            value_template: "{{ repeat.index < 60 }}" # 1-indexed
        sequence:
          - service: homeassistant.reload_config_entry
            target:
              entity_id: cover.garage_msg100_main_channel
          - delay:
              minutes: 1
  mode: single
```
