### ISSUE TITLE
Integration Installed in HACS - But not available in HA

### ISSUE THREAD

**Issue by GazTheGeek** [albertogeniola/meross-homeassistant#150]
Warning - Newbie.

I have successfully installed the Meross integration into a new installation of Hassio on the Raspberry Pi 4. It is showing on the HACS integration page.

Following the instructions I am going to Configuration > Integrations > then + to add a new one. The Meross integration does not appear in the results. I can't figure what is wrong. Help please.
<img width="1647" alt="Screen Shot 2020-10-13 at 3 40 58 pm" src="https://user-images.githubusercontent.com/72774034/95816515-04e96b00-0d6b-11eb-94f1-d1ecde89174c.png">
<img width="1159" alt="Screen Shot 2020-10-13 at 3 41 28 pm" src="https://user-images.githubusercontent.com/72774034/95816523-0ca90f80-0d6b-11eb-8d0a-99ce7aa73235.png">

**Comment by chrisbl01** [comment]
Have you tried clearing your browser history and then adding the integration?  Works for me on HACS installs usually.  Sometimes even a simple refresh of the browser window does the trick.

**Comment by GazTheGeek** [comment]
Thanks chrisb01. That did it. My bad.
