### ISSUE TITLE
msg100: add feature SUPPORT_STOP

### ISSUE THREAD

**Issue by wivaku** [albertogeniola/meross-homeassistant#153]
Can you add the HA cover feature SUPPORT_STOP?  
https://developers.home-assistant.io/docs/core/entity/cover/#supported-features

I know there’s really just one button press, so open/close/stop all use the same impulse.  
But this way it is clearer what the actual effect is. 

Basically when pressing the button again while opening / closing, the garage door stops. 
When pressing the button once again then it closes.

**Comment by albertogeniola** [comment]
Hi @wivaku ,

are you able to "stop" your garage door using the Meross App?

**Comment by wivaku** [comment]
No not using the app. Meross support wrote:

> The MSG100 couldn't be able to control to open partially, or stop in half way. We appreciate your feedback and willing to forward your thoughts to our developers and hope we will have a such plan to add this feature in near future.

I was hoping the HA integration could support it anyway, as all the Meross device does is send pulses.
