### ISSUE TITLE
 MS100 Temp/Um sensor

### ISSUE THREAD

**Issue by Orion5512** [albertogeniola/meross-homeassistant#155]
Ciao; ho integrato in HA con HACS 2 valvole MTS100 e un sensore Temp/Um Ms100, le due valvole sono state integrate con successo mentre MS100 non appare tra i componenti integrati. Ad  ogni avvio di HA appare il seguente messaggio :
The following integrations and platforms could not be set up :meross_cloud.sensor Please check your config.
I'integrazione è su Hassio OS 3.12 e Home Assistant Core  version 0.105.5. Ho provato a cecare nel sito soluzione del problema, ma nessuno dei casi simili mi è stato di aiuto. Can You Help me please.

Hi; I have integrated in HA with HACS 2 MTS100 valves and a Temp / Um Ms100 sensor, the two valves have been successfully integrated while MS100 does not appear among the integrated components. The following message appears every time HA is started:
The following integrations and platforms could not be set up: meross_cloud.sensor Please check your config.
The integration is on Hassio OS 3.12 and Home Assistant Core version 0.105.5. I tried to find a solution to the problem on the site, but none of the similar cases helped me. Can You Help me please

**Comment by albertogeniola** [comment]
Hi @Orion5512,
Please translate your messages in english in order to allow other people to both help you and get helped by others. 
In your case, it looks like there is a problem with the HA integration when attaching a MS100 temperature/humidity sensor. 
In order to help us debugging the issue, we need to know:
1. The installed version of the meross_cloud component in your HA environment
2. The error logs that appear when you reboot your HA, as you can see from the screenshot below
![image](https://user-images.githubusercontent.com/4648843/98437234-f0399200-20e0-11eb-8fce-063b286296de.png)

**Comment by Orion5512** [comment]
Hi Alberto
The Installed version of the Meross_cloud is V1.0.3
this is the log :
2020-11-07 22:13:36 WARNING (MainThread) [homeassistant.loader] You are
using a custom integration for hacs which has not been tested by Home
Assistant. This component might cause stability problems, be sure to
disable it if you do experience issues with Home Assistant.
2020-11-07 22:13:36 WARNING (MainThread) [homeassistant.loader] You are
using a custom integration for shelly which has not been tested by Home
Assistant. This component might cause stability problems, be sure to
disable it if you do experience issues with Home Assistant.
2020-11-07 22:13:36 WARNING (MainThread) [homeassistant.loader] You are
using a custom integration for alexa_media which has not been tested by
Home Assistant. This component might cause stability problems, be sure to
disable it if you do experience issues with Home Assistant.
2020-11-07 22:13:36 WARNING (MainThread) [homeassistant.loader] You are
using a custom integration for meross_cloud which has not been tested by
Home Assistant. This component might cause stability problems, be sure to
disable it if you do experience issues with Home Assistant.
2020-11-07 22:14:00 WARNING (MainThread) [custom_components.meross_cloud]
===============================
Meross Cloud Custom component
Developed by Alberto Geniola
Low level library version: 0.4.0.5
-------------------------------
This custom component is under development and not yet ready for production
use.
In case of errors/misbehave, please report it here:
https://github.com/albertogeniola/meross-homeassistant/issues

If you like this extension and you want to support it, please consider
donating.
-------------------------------
List of devices reported by HTTP API:
- Smart Hub (msh300) - OnlineStatus.ONLINE
===============================
2020-11-07 22:14:00 ERROR (MainThread) [metno]
https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/1.9/
returned 203
2020-11-07 22:14:00 ERROR (MainThread)
[homeassistant.components.met.weather] Retrying in 15 minutes
2020-11-07 22:14:04 WARNING (MainThread) [meross_iot.device_factory] Device
Smart Hub (msh300, uuid 1912095963496926280448e1e9130bfd) reported ability
Appliance.Digest.Hub. Assuming this is a full-featured HUB.
2020-11-07 22:14:10 ERROR (MainThread) [homeassistant.setup] Unable to
prepare setup for platform meross_cloud.sensor: Platform not found (cannot
import name 'UNIT_PERCENTAGE' from 'homeassistant.const'
(/usr/src/homeassistant/homeassistant/const.py)).
2020-11-07 22:14:15 WARNING (MainThread) [homeassistant.setup] Setup of
hacs is taking over 10 seconds.
2020-11-07 22:14:20 WARNING (MainThread)
[homeassistant.components.frontend] Overwriting integration hacs
2020-11-07 22:14:24 WARNING (MainThread) [homeassistant.components.switch]
Setup of switch platform alexa_media is taking over 10 seconds.
2020-11-07 22:14:24 WARNING (MainThread) [homeassistant.components.sensor]
Setup of sensor platform alexa_media is taking over 10 seconds.
2020-11-07 22:14:24 ERROR (MainThread) [homeassistant.core] Error doing
job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py",
line 415, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists:
sensor.hacs. Platform hacs does not generate unique IDs
Many thank' in adavance

Il giorno sab 7 nov 2020 alle ore 10:07 Alberto Geniola <
notifications@github.com> ha scritto:
