### ISSUE TITLE
Detect I/O inside event loop

### ISSUE THREAD

**Issue by Bas-Man** [albertogeniola/meross-homeassistant#156]
From Hassio logs

Logger: homeassistant.util.async_
Source: util/async_.py:105 
First occurred: 1:28:36 PM (3 occurrences) 
Last logged: 1:28:36 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for meross_cloud doing I/O at custom_components/meross_cloud/__init__.py, line 43: manager = MerossManager(meross_email=config_entry.data.get(CONF_USERNAME), meross_password=config_entry.data.get(CONF_PASSWORD))
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for meross_cloud doing I/O at custom_components/meross_cloud/__init__.py, line 49: manager.start()

**Comment by albertogeniola** [comment]
Hi @Bas-Man :

which version of the component are you running?

**Comment by Bas-Man** [comment]
Hi,

I hope I have reported this in the right place. If I haven't. Sorry. 
I am using the latest release of hassio on a Pi 3.

**Comment by albertogeniola** [comment]
Ok about Hassio, but what version of Meros Component have you installed on your HomeAssistant?

**Comment by Bas-Man** [comment]
HI,
Sorry for the delay. I can't find a version number for the component. But I did find:
```yaml
requirements": ["meross_iot==0.3.2.5"]
```
This appears quiet old compared to this repo.
I will take a look at upgrading. Hopefully its a simple process 👍🏻

**Comment by Bas-Man** [comment]
Doing the upgrade appears to have resolved my issue. I will try to keep an eye on new releases. :)
