### ISSUE TITLE
no devices and no entities

### ISSUE THREAD

**Issue by shra1976** [albertogeniola/meross-homeassistant#157]
I've installed the release v1.0.4-alpha.1 but I can see only the Meross Manager API Stats in device tab and the entities is allways 0 API/s.

from the log I have:

>Dettagli registro (WARNING)
>Logger: custom_components.meross_cloud
>Source: custom_components/meross_cloud/__init__.py:54
>Integration: Meross Cloud IoT (documentation)
>First occurred: 8:43:08 (1 occurrences)
>Last logged: 8:43:08

>=============================== Meross Cloud Custom component Developed by Alberto Geniola Low level >library version: 0.4.0.6.post2 ------------------------------- This custom component is under development and not yet ready for >production use. In case of errors/misbehave, please report it here: https://github.com/albertogeniola/meross->homeassistant/issues If you like this extension and you want to support it, please consider donating. ----------------------------->-- List of devices reported by HTTP API: - Smart Hub (msh300) - OnlineStatus.ONLINE >===============================

So it sees the Smart Hub (msh300) but why I can't see any device in Home Assistant?
where am I wrong?

**Comment by shra1976** [comment]
I have this error in the log

Logger: meross_iot.manager
Source: /srv/homeassistant/lib/python3.7/site-packages/meross_iot/manager.py:441
First occurred: 19:01:27 (1 occurrences)
Last logged: 19:01:27

>Failed to retrieve abilities for device Smart Hub (1911087920368626280348e1e911473b). 
>This device won't be enrolled.

**Comment by albertogeniola** [comment]
Hi @shra1976 ,

did any previous version of this component work differently or this is the first time you are running this component?

**Comment by shra1976** [comment]
Hi Alberto thanks for your answer. I used a previous version on another installation of home assistant and it worked well all last summer but at the end of September it began to have problems. I updated your integration and it began not to discover devices. Meanwhile I setuped a clean installation of home assistant and installed the last version of the integration and it never loaded any device. Finally I installed the alpha version but the result is allways the same. Do you know what happened? How can I help you to discover the issue?

**Comment by albertogeniola** [comment]
Hi @shra1976,

can you please list all the devices connected to the smart hub? Can you see them from the Meross APP?

BR,
Alberto

**Comment by shra1976** [comment]
Hi @albertogeniola,
I have 6 valves MTS100 ver. 3 connected with the hub. Normally I can see them from the App.
When I connect your integration the Hub began to have a lot of disconnection from the net. It doesn't happen when I uninstall the integration.
Today I have new errors in the log:

>Logger: meross_iot.manager
>Source: /srv/homeassistant/lib/python3.7/site-packages/meross_iot/manager.py:651
>First occurred: 6 novembre 2020, 18:55:18 (1050 occurrences)
>Last logged: 10:12:14

>Uncaught push notification Namespace.SYSTEM_ONLINE. Raw data: {"online": {"status": 1}}
>Uncaught push notification Namespace.SYSTEM_ONLINE. Raw data: {"online": {"status": "2"}}
>Uncaught push notification Namespace.SYSTEM_ONLINE. Raw data: {"online": {"status": "1"}}

and: 

>Logger: meross_iot.manager
>Source: /srv/homeassistant/lib/python3.7/site-packages/meross_iot/manager.py:594
>First occurred: 6 novembre 2020, 18:54:52 (1051 occurrences)
>Last logged: 10:12:16

>Received a push notification (Namespace.SYSTEM_ONLINE, raw_data: {"online": {"status": 1}}) for device(s) (1911087920368626280348e1e911473b) that are not available in the local registry. Trigger a discovery to intercept those events.
>Received a push notification (Namespace.SYSTEM_ONLINE, raw_data: {"online": {"status": "2"}}) for device(s) (1911087920368626280348e1e911473b) that are not available in the local registry. Trigger a discovery to intercept those events.
>Received a push notification (Namespace.SYSTEM_ONLINE, raw_data: {"online": {"status": "1"}}) for device(s) (1911087920368626280348e1e911473b) that are not available in the local registry. Trigger a discovery to intercept those events.

and: 

>Logger: meross_iot.manager
>Source: /srv/homeassistant/lib/python3.7/site-packages/meross_iot/manager.py:610
>First occurred: 6 novembre 2020, 18:54:52 (1051 occurrences)
>Last logged: 10:12:16

>Received a push notification for a device that is not available in the local registry. You may need to trigger a discovery to catch those updates. Device-UUID: 1911087920368626280348e1e911473b

and: 

>Logger: meross_iot.manager
>Source: /srv/homeassistant/lib/python3.7/site-packages/meross_iot/manager.py:717
>First occurred: 6 novembre 2020, 18:54:57 (2695 occurrences)
>Last logged: 10:12:31

>Timeout occurred while waiting a response for message b'{"header": {"from": "/app/838479-251bfe8dc573044a598bb7a945f93959/subscribe", "messageId": "08b6878bc28c8ecb12d32a85d924a8d6", "method": "GET", "namespace": "Appliance.System.Ability", "payloadVersion": 1, "sign": "8eec4e2537f6bd5d88cafa3787c8b95a", "timestamp": 1604740280}, "payload": {}}' sent to device uuid 1911087920368626280348e1e911473b. Timeout was: 5.0 seconds.
>Timeout occurred while waiting a response for message b'{"header": {"from": "/app/838479-251bfe8dc573044a598bb7a945f93959/subscribe", "messageId": "4c7c03b8ddb0764d18fc97aea4f6aa42", "method": "GET", "namespace": "Appliance.System.Ability", "payloadVersion": 1, "sign": "a00591c59582575f08ba2f41b3750806", "timestamp": 1604740286}, "payload": {}}' sent to device uuid 1911087920368626280348e1e911473b. Timeout was: 5.0 seconds.
>Timeout occurred while waiting a response for message b'{"header": {"from": "/app/838479-251bfe8dc573044a598bb7a945f93959/subscribe", "messageId": "21f965528e7dccbc6feb1c6e664a8ea5", "method": "GET", "namespace": "Appliance.System.Ability", "payloadVersion": 1, "sign": "96caff012a11072180ffbc1feb9ec373", "timestamp": 1604740336}, "payload": {}}' sent to device uuid 1911087920368626280348e1e911473b. Timeout was: 5.0 seconds.
>Timeout occurred while waiting a response for message b'{"header": {"from": "/app/838479-251bfe8dc573044a598bb7a945f93959/subscribe", "messageId": "795d34fc2ae129d6ffcd61be4dcbd04c", "method": "GET", "namespace": "Appliance.System.Ability", "payloadVersion": 1, "sign": "b99e8aa6adef0c4a283efc750b4c26ab", "timestamp": 1604740341}, "payload": {}}' sent to device uuid 1911087920368626280348e1e911473b. Timeout was: 5.0 seconds.
>Timeout occurred while waiting a response for message b'{"header": {"from": "/app/838479-251bfe8dc573044a598bb7a945f93959/subscribe", "messageId": "b1b482d5d5476ff14ea1a89958d78fc2", "method": "GET", "namespace": "Appliance.System.Ability", "payloadVersion": 1, "sign": "c67656e238556205f442c7daeabbd442", "timestamp": 1604740347}, "payload": {}}' sent to device uuid 1911087920368626280348e1e911473b. Timeout was: 5.0 seconds.

and: 

>Logger: meross_iot.manager
>Source: /srv/homeassistant/lib/python3.7/site-packages/meross_iot/manager.py:441
>First occurred: 6 novembre 2020, 18:54:57 (2695 occurrences)
>Last logged: 10:12:31

>Failed to retrieve abilities for device Smart Hub (1911087920368626280348e1e911473b). This device won't be enrolled.

Thanks,
Marco.

**Comment by shra1976** [comment]
Hi @albertogeniola ,
I tried to connect the Smart Hub to internet throw another hotspot and all work properly. Now I can see the entities. I've to understand why if I connect the Smart Hub to my router it doesn't work. Everything else is connected to that router and work fine. Thanks for your support.

**Comment by damy7** [comment]
Hi !
I have some trouble with MSS425F plug.
Running on HA RP4, installed Meross IoT Cloud via HACS, and my plug only recognized as "device.tracker" seen Online or Offline. I don't have any "meross" in HA Integration. So I don't see my plug as plug :/

Thanks for your help 👍

**Comment by albertogeniola** [comment]
I am closing this issue as it seems related to the network setup/configuration of the user.
