### ISSUE TITLE
mts100v3 - wrong mapping HVAC_MODE_HEAT

### ISSUE THREAD

**Issue by KamikX** [albertogeniola/meross-homeassistant#159]
Hi Alberto, in file climate.py, line 134 is mistake in mapping,  map HVAC_MODE_HEAT to ThermostatV3Mode.CUSTOM https://github.com/albertogeniola/meross-homeassistant/blob/1668c2c772a1b3d654a5a2c3eddfb59bb158c90e/custom_components/meross_cloud/climate.py#L134 
BR,
Kamil

**Comment by albertogeniola** [comment]
Thanks for the great spot
