### ISSUE TITLE
Install of meross on Homeassistant VM on Synology

### ISSUE THREAD

**Issue by psjshep** [albertogeniola/meross-homeassistant#162]
I have a Synology 718+ disk station, running a Virtual Machine, with a pre-configured image (I believe it's called a Virtual Appliance) which was downloaded from the Home Assistant site - 
https://github.com/home-assistant/operating-system/releases/download/4.16/hassos_ova-4.16.ova

I have been using HA for about a year now & have acquired 2 x Meros MSS210 plugs.

I followed your manual install instructions but when I try to setup a new integration, I see the Merros_cloud but it doesn't fire up.

In the logfile, I see this 

Source: config_entries.py:535
First occurred: 14:59:28 (1 occurrences)
Last logged: 14:59:28
Error occurred loading configuration flow for integration meross_cloud: No module named 'custom_components.meross_cloud' 

Any pointers?
Thanks,
Phil

**Comment by psjshep** [comment]
any help at all?

Phil

**Comment by albertogeniola** [comment]
Hi @psjshep ,

from the log entry, it seems you do not have copied the meross_cloud folder where the system expects it. If you are unfamiliar with manual homeassistant component setup, please use HACS which really simplifies installation and updates of custom components on HA.

**Comment by psjshep** [comment]
I had a 2nd Home Assistant installation where I tested the integration... that had HACS installed... I could not get Meross Cloud to work... it is possible it was due to the attempt to originally install manually.

I went back to my main installation & only installed via HACS - this seems to have worked..... I will go back to my test VM & try to remove everything to do with HACS & Meross only...

I will keep you posted

Phil

**Comment by psjshep** [comment]
by removing meross manual install & HACS, rebooting after each phase, then adding HACS (+ reboot) then adding Meross_cloud & reboot, all is working....

I'm not sure if this is a docker anomaly but rebooting after each phase seems to have sorted it !

Phil

**Comment by albertogeniola** [comment]
Well done!
