### ISSUE TITLE
regular disconnection

### ISSUE THREAD

**Issue by herveaurel** [albertogeniola/meross-homeassistant#163]
Regularly, every 3 or 4 days, sometimes less, Meross is unavailable.  I have to restart Home Assistant every time.

**Comment by jacekpaszkowski** [comment]
Same for me, very unstable connection since update to v1.0.0+. I have only one device and it get unavailable very often
![image](https://user-images.githubusercontent.com/4264991/99307042-41baed00-2856-11eb-8fab-9cc9209d19ea.png)

**Comment by andreibobirica** [comment]
I have noticed that disconnection occurs mainly when there is a lack of internet. I always have to reload the integration.

**Comment by herveaurel** [comment]
Je n’ai plus le problème depuis quelques jours 😜👌🏼

**Comment by hdjweb** [comment]
I have the sale problem with meross mss425e

**Comment by RedFoxy** [comment]
me too!

**Comment by herveaurel** [comment]
damn, it starts again ... Meross offline.  forced to restart HA.  It’s always around 7:00 am (Feance).  Internet ok.  Nothing in the log.

**Comment by albertogeniola** [comment]
Hi guys,
the issue you are experiencing is mostly due to some Meross implementation that limits the requests per second that the component can possibly run. Latest release implements stronger API limiting logic while fixing some other issues with latest Homeassistant release. Could you please test version v1.0.4 and report back if that helps?

**Comment by tobydriver** [comment]
After upgrading to v1.0.4, all my MSS310 and MSS210 are unavailable.

Error occurred. ------------------------------------- Component version: 0.4.1.0rc4 Device info: <Unavailable> Error Message: "An exception occurred while setting up the meross manager. Setup will be retried..."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/__init__.py", line 140, in async_setup_entry
    await manager.async_device_discovery()
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 262, in async_device_discovery
    enrolled_devices = await asyncio.gather(*tasks, loop=self._loop)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 316, in _async_enroll_new_http_dev
    res_abilities = await self.async_execute_cmd(destination_device_uuid=device_info.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 578, in async_execute_cmd
    raise RateLimitExceeded()
meross_iot.model.exception.RateLimitExceeded


Logger: meross_iot.manager
Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:576
First occurred: 17:59:45 (15 occurrences)
Last logged: 18:00:05

Rate limit reached: over-limit percentage is 350.0% which exceeds the current 300 limit. The call will be dropped.
Rate limit reached: over-limit percentage is 400.0% which exceeds the current 300 limit. The call will be dropped.
Rate limit reached: over-limit percentage is 450.0% which exceeds the current 300 limit. The call will be dropped.
Rate limit reached: over-limit percentage is 500.0% which exceeds the current 300 limit. The call will be dropped.
Rate limit reached: over-limit percentage is 550.0% which exceeds the current 300 limit. The call will be dropped.

Back to v1.0.3, the plugs are OK.

**Comment by albertogeniola** [comment]
Hi @tobydriver ,

well... that was expected. As you see from the logs, the rate limiter is preventing you from being banned by Meross security team. May I ask you how many meross devices are you running on you Meross Account?

**Comment by tobydriver** [comment]
I have 8 MSS310 and 4 MSS210

**Comment by albertogeniola** [comment]
I see, then try the **v1.0.4-post1** that I've just released as pre-release version. That one, has 1000% API rate limit threshold: it still "slows down" the API requests and will only generate an exception if the requested API go over 1000% of the expected capacity (2 API calls per second). 

Keep us posted!

**Comment by tobydriver** [comment]
Now my devices are available on restart. Thanks @albertogeniola !

HA feels to be a little bit longer to restart. Is that due to the new version of Meross Cloud?
```
Logger: meross_iot.manager

Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:582
First occurred: 18:23:06 (334 occurrences)
Last logged: 18:29:07

Rate limit reached (RateLimitResult.GlobalLimitReached): api call will be delayed by 0.5 seconds
Rate limit reached (RateLimitResult.GlobalLimitReached): api call will be delayed by 1.0 seconds
Rate limit reached (RateLimitResult.GlobalLimitReached): api call will be delayed by 2.0 seconds
Rate limit reached (RateLimitResult.PerDeviceLimitReached): api call will be delayed by 0.5 seconds
Rate limit reached (RateLimitResult.PerDeviceLimitReached): api call will be delayed by 1.0 seconds
```

**Comment by tobydriver** [comment]
After 1h30 with v1.0.4-post1, my plugs are again unavailable.

**Comment by herveaurel** [comment]
> Après 1h30 avec la v1.0.4-post1, mes plugs sont à nouveau indisponibles.

😩😩😩

**Comment by albertogeniola** [comment]
Hi @tobydriver ,

can you please provide some logs?

**Comment by albertogeniola** [comment]
Closing as no logs have been provided

**Comment by tobydriver** [comment]
Hi,
Here are the logs : 
```
Logger: custom_components.meross_cloud.sensor
Source: custom_components/meross_cloud/sensor.py:288
Integration: Meross Cloud IoT (documentation)
First occurred: 6 décembre 2020 à 20:51:24 (2 occurrences)
Last logged: 1:07:50

Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: MyDeviceName UUID: MyDeviceUUID Type: mss310 HW Version: 1.0.0 FW Version: 1.1.18 Error Message: "An exception occurred"
Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: MyDeviceName UUID: MyDeviceUUID Type: mss310 HW Version: 2.0.0 FW Version: 2.1.16 Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 288, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/electricity.py", line 38, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError
```

and 

```
Logger: meross_iot.manager
Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:368
First occurred: 6:56:06 (58 occurrences)
Last logged: 8:38:20

Client has been disconnected, however auto_reconnect flag is set. Won't stop the looping thread, as it will retry to connect.
```

Switches never came back after disconnection. I had to restart HA.

Thanks :)
