### ISSUE TITLE
Unrecognized device: Meross Smart Lightstrip

### ISSUE THREAD

**Issue by JanZHH** [albertogeniola/meross-homeassistant#167]
I tried to integrate the Meross Smart Light Lightstrip which I bought recently.
Unfortunately, I am getting some errors in HA:

Logger: meross_iot.manager
Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:562
First occurred: 7:12:06 (16 occurrences)
Last logged: 7:27:47

Received a push notification for a device that is not available in the local registry. You may need to trigger a discovery to catch those updates. Device-UUID: 2006286191323351851148e1e922076e
Received a push notification for a device that is not available in the local registry. You may need to trigger a discovery to catch those updates. Device-UUID: 2006280604480951851148e1e921ef0b
Received a push notification for a device that is not available in the local registry. You may need to trigger a discovery to catch those updates. Device-UUID: 2008285263574490827348e1e92ec9b4

**Comment by albertogeniola** [comment]
Hi @JanZHH ,

The lightstrip is not yet supported by the HA component nor by the MerossIot low-level library.
