### ISSUE TITLE
Missing support for dedicated white LED (MSL120)

### ISSUE THREAD

**Issue by luistaboada** [albertogeniola/meross-homeassistant#17]
Hey, I just noticed that I could not achieve a strong white color through hassio in comparisson to meross native app. As you can see in this images:
[bulb comparisson](https://dl3.pushbulletusercontent.com/Y3E9c8fQlqrsujRJMQW1g5kCEAOL9qh9/meross_comparisson.png)
[meross app comparisson](https://dl3.pushbulletusercontent.com/VdRYN3gRB1tPM4UZgpmvRdID98rnzkLK/meross_comparisson_app.png)

My guess is that MSL120 has a led specific for white, and it has better brightness than using RGB.

I tried using the attribute "white_value" (Integer between 0 and 255 for how bright a dedicated white LED should be.) as seen [here](https://www.home-assistant.io/components/light/), but had no lucky.

Is it missing support for the dedicated white LED? If so, any way to help you to implement it?
Thanks!

**Comment by albertogeniola** [comment]
Linked to #9 .
