### ISSUE TITLE
Easy way to change meros cloud password 

### ISSUE THREAD

**Issue by vexorg3000** [albertogeniola/meross-homeassistant#176]
**Is your feature request related to a problem? Please describe.**
I changed my meross cloud password and now i can not find where to change it in the integration. All of my devices are now offline in Home Assistant
**Describe the solution you'd like**
A way to change the password used by the integration or documentation on how to do it

**Describe alternatives you've considered**
Tryed reinstalling the integration but this did not help

**Additional context**

**Comment by albertogeniola** [comment]
Hi @vexorg3000 ,

can you please post the **meross_cloud** section of your configuration.yaml (if any?)

**Comment by davidpesce** [comment]
I'm curious about this as well. I have an 0.118.5 installation with the latest meross_cloud and was seeing a notification that my config setting in configuration.yaml should be removed. Yet when I view the meross_cloud config, I don't see a way to change it. 

I also logged in via ssh to custom_components/meross_cloud and can't seem to find a file with my values.

Is there somewhere else I should look?

**Comment by vexorg3000** [comment]
Hi @albertogeniola , 
I just double checked and there is no config for it in the config.yaml.

Should there be ?
Cheers

**Comment by lcavalli** [comment]
Hi,
looking at https://developers.home-assistant.io/docs/config_entries_config_flow_handler/#reauthentication reauthentication due to updated password or expired tokens can be handled by the integration. The page also mentions .store/core.config_entries and in this file I can see my meross account credentials.
