### ISSUE TITLE
Invalid config error on 0.118.4: unable to install meross-iot 0.4.1.0rc7 package

### ISSUE THREAD

**Issue by AlainGH** [albertogeniola/meross-homeassistant#178]
Got this error since I upgraded to 0.118.4

**Your environment**
HomeAssistant version: 0.118.4
Hassio Version (if applicable):
Hardware environment: Pi 3B+

**Logs taken when the issue happened**

```
Logger: homeassistant.util.package
Source: util/package.py:95
First occurred: 16:40:39 (1 occurrences)
Last logged: 16:40:39
Unable to install package meross-iot==0.4.1.0rc7: ERROR: Could not find a version that satisfies the requirement aiohttp 3.6.2 (from aiohttp[speedups]) ERROR: No matching distribution found for aiohttp 3.6.2 
```

```
Logger: homeassistant.setup
Source: setup.py:138
First occurred: 16:40:39 (1 occurrences)
Last logged: 16:40:39
Setup failed for meross_cloud: Requirements for meross_cloud not found: ['meross-iot==0.4.1.0rc7']. 

```
**Edit:**
Error still present even after upgrading to HA 2020.12.0

**Comment by Nuftuf-code** [comment]
Hi - I previously installed this through HACS in Home Assistant v0.117.4 and everything worked great. 
I uninstalled then tried to reinstall again through HACS in v0.118.4 and now continually get this error. 
I am trying to install v1.05.
I have also tested in Home Assistant 1.0.0b2 and have the same problem. Would love to have this great Meross plugin working again in Home Assistant! 👍

**Comment by Nuftuf-code** [comment]
I managed to solve this on my setup. I had a script that upgraded pip on my home assistant server (docker build) to pip v20.3.3. This appears to have some breaking changes. I setup a fresh install of home assistant (using docker) and disabled the pip upgrade so pip remained on version 20.2.4. This fixed the issue, error went away and Meross plugin is now working! :-)

**Comment by AlainGH** [comment]
On upgrading to HA 2020.12.1 everything came back working itself. I noticed Pip was downgraded to 20.2.4
