### ISSUE TITLE
Devices becoming unavailable often

### ISSUE THREAD

**Issue by silviudc** [albertogeniola/meross-homeassistant#180]
**Describe the bug**
This happens at least once per day breaking all HA integrations for meross devices.
Looks to be timing out on some devices but not sure why all of them go offline and the only way to bring them back is to restart HA - can this be updated for them to just come back online without reboot (like tuya integration for example)

**Your environment**
HomeAssistant version: -- 0.118.5 --
Hassio Version (if applicable): -- 5.7 --
Hardware environment: -- pi4 --

**Logs taken when the issue happened**
```
2020-12-12 16:24:16 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/63513-5c8f2ad00fe8972ec8173244740c48e7/subscribe", "messageId": "c1cd3e84bc6c69e616a4d8c945d182e3", "method": "GET", "namespace": "Appliance.Control.Electricity", "payloadVersion": 1, "sign": "dadd08c2ab5e670fc2ad14ca249743fc", "timestamp": 1607790252, "triggerSrc": "Android"}, "payload": {"channel": 0}}' sent to device uuid 1801304134135025130834298f11356b. Timeout was: 5 seconds.
2020-12-12 16:24:16 ERROR (MainThread) [custom_components.meross_cloud.sensor] Error occurred.
-------------------------------------
Component version: 0.4.1.0rc7
Device info: 
	Name: Garden lights
	UUID: 1801304134135025130834298f11356b
	Type: mss310
	HW Version: 1.0.0
	FW Version: 1.1.18
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 322, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/electricity.py", line 38, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError
2020-12-12 16:24:22 WARNING (MainThread) [custom_components.meross_cloud.sensor] Device Garden lights (mss310) - power sensor (W, 0) reported online event.
2020-12-12 16:24:22 WARNING (MainThread) [custom_components.meross_cloud.sensor] Device Garden lights (mss310) - power sensor (A, 0) reported online event.
2020-12-12 16:24:22 WARNING (MainThread) [custom_components.meross_cloud.sensor] Device Garden lights (mss310) - power sensor (V, 0) reported online event.
2020-12-12 16:24:22 WARNING (MainThread) [custom_components.meross_cloud.switch] Device Garden lights (mss310) - Main channel reported online event.
2020-12-12 16:24:23 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Garden lights (mss310) - power sensor (W, 0): 0.0> as it was already added to registry once.
2020-12-12 16:24:23 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Garden lights (mss310) - power sensor (A, 0): 0.0> as it was already added to registry once.
2020-12-12 16:24:23 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Garden lights (mss310) - power sensor (V, 0): 225.6> as it was already added to registry once.
2020-12-12 16:24:27 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/63513-5c8f2ad00fe8972ec8173244740c48e7/subscribe", "messageId": "ee291ec7fd6a85571f53e868e2bc95c4", "method": "GET", "namespace": "Appliance.Control.Electricity", "payloadVersion": 1, "sign": "196d4eeef16b1e5a05c64ff92dc02e32", "timestamp": 1607790263, "triggerSrc": "Android"}, "payload": {"channel": 0}}' sent to device uuid 1801304134135025130834298f11356b. Timeout was: 5 seconds.
2020-12-12 16:24:27 ERROR (MainThread) [custom_components.meross_cloud.sensor] Error occurred.
-------------------------------------
Component version: 0.4.1.0rc7
Device info: 
	Name: Garden lights
	UUID: 1801304134135025130834298f11356b
	Type: mss310
	HW Version: 1.0.0
	FW Version: 1.1.18
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 288, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/electricity.py", line 38, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError
2020-12-12 16:24:27 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/63513-5c8f2ad00fe8972ec8173244740c48e7/subscribe", "messageId": "c99a7e3b14afc60de85572925decf9c7", "method": "GET", "namespace": "Appliance.System.All", "payloadVersion": 1, "sign": "94d1125f5065333650611687a929a8be", "timestamp": 1607790263, "triggerSrc": "Android"}, "payload": {}}' sent to device uuid 1801304134135025130834298f11356b. Timeout was: 5 seconds.
2020-12-12 16:24:27 ERROR (MainThread) [custom_components.meross_cloud.switch] Error occurred.
-------------------------------------
Component version: 0.4.1.0rc7
Device info: 
	Name: Garden lights
	UUID: 1801304134135025130834298f11356b
	Type: mss310
	HW Version: 1.0.0
	FW Version: 1.1.18
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/switch.py", line 57, in async_update
    await self._device.async_update()
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/system.py", line 21, in async_update
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError
```

**Comment by escaflown23** [comment]
Same issue here.

**Comment by silviudc** [comment]
Some more logs in case they might help:
```
2020-12-13 10:05:41 WARNING (MainThread) [custom_components.meross_cloud.switch] Device Upstairs Xmas Lights (mss310) - Main channel reported online event.
2020-12-13 10:05:41 WARNING (MainThread) [custom_components.meross_cloud.sensor] Device Upstairs Xmas Lights (mss310) - power sensor (W, 0) reported online event.
2020-12-13 10:05:41 WARNING (MainThread) [custom_components.meross_cloud.sensor] Device Upstairs Xmas Lights (mss310) - power sensor (A, 0) reported online event.
2020-12-13 10:05:41 WARNING (MainThread) [custom_components.meross_cloud.sensor] Device Upstairs Xmas Lights (mss310) - power sensor (V, 0) reported online event.
2020-12-13 10:05:41 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Upstairs Xmas Lights) before accessing its state. Failure to do so may result in inconsistent state.
2020-12-13 10:05:41 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Upstairs Xmas Lights (mss310) - power sensor (W, 0): None> as it was already added to registry once.
2020-12-13 10:05:41 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Upstairs Xmas Lights (mss310) - power sensor (A, 0): 0> as it was already added to registry once.
2020-12-13 10:05:41 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Upstairs Xmas Lights (mss310) - power sensor (V, 0): 0> as it was already added to registry once.
```

**Comment by userMak** [comment]
same issue here. I have only 6 light switches and most of the time 1-2 of them are unavailable. 
I hate Meross and my target is to replace them in the next months. I feel is better to throw them in the garbage instead of giving them as a gift. (Nothing to do with the fine work here)

**Comment by silviudc** [comment]
Too bad as I'm in the same boat, and I think I'll start to replace with sonoff slowly. Don't think I ever had it fail.
But meross was also working great for a long time, ever since a few HA revisions ago.

**Comment by krelltunez** [comment]
I've seen this as well, and is one of the reasons I haven't made any automations yet.  I've confirmed that when this happens, the device is still visible/controllable from within the Meross app.  So I do not think this is a Meross issue.  I'm actually quite impressed with the garage door openers - they were inexpensive and exactly what I was looking for.  I'm not sure why the sync to HA is so finnicky.  Happy to provide info or help troubleshoot as needed.

FYI, I am a relatively new user.  I only installed/set up my Meross devices on Dec 1.

**Comment by arpia49** [comment]
Same thing here. I'm happy to provide logs or information if needed.

**Comment by Crissup** [comment]
I'm having this exact problem at least once daily lately (up until a couple weeks back, it was occasionally).  And, as you indicated, I've been restarting HA each time.  Today, I decided to dig into it a bit deeper, hoping to find reliable log entries that I could trigger on in a script or cron job and bounce the device.  Ironically, my last log entries concerning my Meross devices were shorty after my last restart at 4:00am (I've scheduled a nightly restart just because of this issue), however, my History shows my Meross devices all went offline at 8:00am, and I found zero log file entries in any of the logs related to this.

As I was looking at my Meross integration Entities list, all showing the exclamation point in the circle, indicating a problem.  I decided to disable one of the entities.  I then went back into that particular entity and reenabled it, and suddenly all of my Meross devices came back online.  So, I'm guessing that reenabling the entity caused the Meross integration to kick off a different Python function and caused the main integration module to suddenly reenter a normal state.

**Comment by Crissup** [comment]
I see there's been a couple of tweaks to the code since my last update less than a month ago.  And, it appears the tweaks are aimed at fixing this issue.  I'm going to update my plugins and see if it makes a difference.

**Comment by wsw70** [comment]
I raised a similar issue at https://github.com/albertogeniola/meross-homeassistant/issues/183 (thanks @Crissup for pointing out that one) and the main difference is that I never had any consequences from this timeout. Specifically, I never had to restart HA.
I guess that the next run of the connection was simply successful.

I cannot tell about the frequency because until recently I was not looking at the logs very much (I moved all my automations to the excellent [pyscript](https://github.com/custom-components/pyscript) and started to look at the log then, when developing).

I would  say that I witness the Traceback every few days (I have about 10 MEROSS devices). 

The more annoying issue for me is https://github.com/albertogeniola/meross-homeassistant/issues/130 (the animated demo in my question shows it clearly) but once I got used to that I do not have particular problems.

**Comment by krelltunez** [comment]
I have 3 devices (garage door openers) - usually 1 or 2 goes offline.  They'll come back eventually (even without a reboot).  The devices remain online in the Meross app, so this definitely has to do with the connectivity between Meross and HA.

I'm hoping this can be fixed in a future update.

**Comment by wsw70** [comment]
@krelltunez 
> The devices remain online in the Meross app

Do they still work (i.e. respond to actual commands) in the MEROSS app when they are offline in HA? 
I found that the "online" status is sometimes loosely related to the actual capacity to reach the device (not specifically for MEROSS, this is a general comment)

**Comment by krelltunez** [comment]
> @krelltunez
> 
> Do they still work (i.e. respond to actual commands) in the MEROSS app when they are offline in HA?
> I found that the "online" status is sometimes loosely related to the actual capacity to reach the device (not specifically for MEROSS, this is a general comment)

Yes, they do.  Tested and confirmed.

**Comment by Crissup** [comment]
Status update on my install.  After updating to the latest Meross integration version, ensuring that I had the update with the "manager = MerossManager(http_client=client, auto_reconnect=True, over_limit_threshold_percentage=1000)" line in it, and running on HA v2020.12, things seem to be working well.  Prior to this, the integration was failing multiple times per day and would require a restart to fix.  Since the update, I had a problem with HA being extremely slow on Friday, forcing a restart (I do not currently believe this is related to the Meross integration).  At 3am on Sunday morning, I have a schedule restart of HA, and the Meross plugin previously would die shortly after a restart of the host.  This time, it came right back up.  

So, it's been less than a week, and I've restarted HA a couple times since the update, but the latest tweaks to the Meross plugin seem to have everything working fine under the latest HA updates.

**Comment by wsw70** [comment]
> After updating to the latest Meross integration version

What is the version of this integration? I see on my HACS (under the integration, then Information) 1.0.5 but I do not know whether this is the installed or the available version (installed, I guess).

**Comment by Crissup** [comment]
> > After updating to the latest Meross integration version
> 
> What is the version of this integration? I see on my HACS (under the integration, then Information) 1.0.5 but I do not know whether this is the installed or the available version (installed, I guess).


**HA Supervisor v2020.12.7**

Meross Integration, as reported by the log file...
===============================
**Meross Cloud Custom component
Developed by Alberto Geniola
Low level library version: 0.4.1.0rc7**

I'm not loading via HACS, I'm downloading and updating manually, in case that matters.  I looked at the last edits that had been made to the package, and then manually verified that they were in the package I downloaded from Github.

**Comment by wsw70** [comment]
@Crissup Thanks. I checked with the repo and I have the latest version (installed via HACS).

I guess that the 

    manager = MerossManager(http_client=client, auto_reconnect=True, over_limit_threshold_percentage=1000) 

line you refer to is https://github.com/albertogeniola/meross-homeassistant/blob/088f15764d1c50103e78a072b97fac4a9e06fc15/custom_components/meross_cloud/__init__.py#L124 ? (and it is present).

I had this morning for a short time the error but it went away on its own. I saw it too late to verify the status on the MEROSS app.

**Comment by Florian-Schmidt** [comment]
Duplicate of #125

**Comment by chris-jennings** [comment]
I found that when I removed all automations from the Meross devices then they would stop going offline. I moved two switches off the Meross app and instead use a local MQTT server and they were the only devices which had power monitoring automations. Since they have been removed the remaining Meross devices stay online and are reliable.

Either the problem is with how automations are implemented or perhaps the number of devices causes a problem.

**Comment by wsw70** [comment]
@chris-jennings

> I moved two switches off the Meross app and instead use a local MQTT server

Would you mind expanding a bit on that? How did you move to a lixal MQTT server?

**Comment by chris-jennings** [comment]
> Would you mind expanding a bit on that? How did you move to a lixal MQTT server?

I followed this thread [link](https://github.com/albertogeniola/MerossIot/issues/1) and also used the great tool from @bytespider [link](https://github.com/bytespider/Meross/tree/master/bin/src)

It took a little bit of work, and setting up your own self signed certificate using these instructions [link](https://gist.github.com/override80/f08c2f7299c9313ddf49bd273c512c8b).

Good luck!

**Comment by wsw70** [comment]
@chris-jennings : thank you. I have been discussing about that on another thread - the one you provided is very good.

I got stuck with sending the right payload to switch on/off, specifically the `sign` field. The error I was getting was that the signature is wrong (it must be an MD5 hash of something, I guess from the look of it)
I will read the thread in detail to see whether there is anything about that

**Comment by chris-jennings** [comment]
> I got stuck with sending the right payload to switch on/off, specifically the `sign` field. The error I was getting was that the signature is wrong (it must be an MD5 hash of something, I guess from the look of it)
I was stuck with that to, and then a read that the sign is determined from the message ID and timestamp. If you use the same messageID and timestamp everytime you don't have the problem.

In my case I just made all messages have the following:
```
messageId "92b375a381812638b91a859a9f158e52"
sign "615ed5b8142680212f01e3ee32b51a12"
timestamp 21
```

Seems to work. One day I might look at implementing the sign calculation as per [link](https://github.com/albertogeniola/MerossIot/issues/1#issuecomment-744667925) but I'm sure someone else will come up with a solution :)

**Comment by wsw70** [comment]
@chris-jennings thanks again for the info. Using your values (or any reported back on the `publich` topic) I do nto get any errors anymore.

But the switch does not change its state (it responds with a new ID, a new signature etc, but with the same payload)

Is the payload you are sending on the `subscribe` topic is something like:

```
{
  "header": {
    "messageId": "a2463abf91e0d12b166455fcc748d080",
    "namespace": "Appliance.Control.ToggleX",
    "method": "PUSH",
    "payloadVersion": 1,
    "from": "/appliance/2006176333738751801348e1e91fb91a/publish",
    "timestamp": 1609404717,
    "timestampMs": 980,
    "sign": "22612f1405fb4421c0cb05381fdde5b1"
  },
  "payload": {
    "togglex": {
      "channel": 0,
      "onoff": 0,
      "lmTime": 1609405010
    }
  }
}
```

Is the `payload` field correct? Is my understanding below correct?
- `channel`: the switch channel to send the message (0 for a single switch, then 0, 1, 2, ... for multiplug switches)
- `onoff`: 0 or 1 to set the state
- `lmTime` : looks like a timestamp. Should it be special (greater than something?) I made it a bit larger than the one from the switch response payload

**Comment by silviudc** [comment]
Just a note that might help people out, I was messing around with different wifi channels on my netgear router and before I had the 2.4g set to channel 11 and now I have changed it to channel 1 and disabling 20/40hz (forced to 40hz) and it's been a few days without the meross integration failing.
The local way of controlling the meross devices you guys are talking about above is very nice too hopefully I get some time to play around with it because I would prefer that over cloud control any day

**Comment by wsw70** [comment]
> can we use the home assistant mqtt addon for it?

This is something I would like to test today when I get back to the computer

**Comment by dominik-doll** [comment]
I have 2 Meross devices in my HA one Plug and Garage Door Opener.
The Plug never becomes unavailable - only the garage Door opener.
If the opener becomes unavailable this affects only HA - via Meross its available and can be controlled and its always connected to wifi. As soon someone opens the garage with the motor remote - it is available in HA again.

![Bildschirmfoto 2021-01-04 um 17 00 28](https://user-images.githubusercontent.com/35460627/103553911-6b83ae00-4eae-11eb-8eb6-72c78f67bc39.png)
![Bildschirmfoto 2021-01-04 um 17 00 15](https://user-images.githubusercontent.com/35460627/103553918-6d4d7180-4eae-11eb-84af-85ffd76e4cf9.png)

**Comment by krelltunez** [comment]
> If the opener becomes unavailable this affects only HA - via Meross its available and can be controlled and its always connected to wifi. As soon someone opens the garage with the motor remote - it is available in HA again.

I can confirm the same.  My garage openers go offline in HA intermittently (no rhyme or reason), but remain available in the Meross app.  If I operate the door via the Meross app OR via the garage door hardware, it is immediately visible in HA again.  It seems like the open/close sensor somehow refreshes the connection between Meross and HA.

**Comment by vomdth** [comment]
Same error:
![image](https://user-images.githubusercontent.com/31765858/103741079-bf021300-4ff8-11eb-8736-d80fb9906ac7.png)
That is really frustrating

**Comment by silviudc** [comment]
Ever since I changed my wifi channel to 1 and 40hz bandwidth about 1 week ago, the meross integration hasn't failed for me once and I still have about 3 meross plugs which keep losing connection due to poor reception but they do come back online on their own in HA without restarting (I do see these errors in the logs)
Maybe too soon call it but it certainly helped my setup.

**Comment by wsw70** [comment]
It may not be related at all but just in case I am adding my experience.

I moved my Meross devices to my loac MQTT (https://github.com/wsw70/meross-local-mqtt) and the setup is working (it is way less elegant than `meross-homeassistant` but uses a local MQTT and is independent of the Meross cloud).

It was working fine until an update of my docker host that triggered a restart of the docker containers, including the one that hosts my MQTT broker. Everything went smoothly (I use the broker for many things outside of HA) except that the Meross **power strips** did not reconnect on their own. When physically switched off and on they reconnected immediately. The single power plugs did not have the problem.

I will continue to investigate that and, again, it may have nothing to do with the case here but it looks like from a first glance that the strips (and maybe other equipment) may have issues when reconnecting to a lost MQTT server.

**Comment by dels78** [comment]
I too am experiencing this same problem and as mentioned above, if I open the garage door via the meross app or the stardard remote, the device becomes available again in HA.

**Comment by sirshorty** [comment]
Same issue here. Garage door control working fine via the app itself, but via HA it's constantly Offline. It even works via Homekit / Apple Home control so just seems to affected HA control.

**Comment by stu531** [comment]
Are people still having problems with Meross devices becoming unavailable?

I've had Meross gear working happily for a couple of years now and used HA for about 18 months with them, with no trouble. They've just started not working over the past week - wall switches, outdoor plugs, indoor plugs. I get the switches greyed out or, if they look available, say 'failed to call service switch'. No idea what's changed. I've tried moving the router around and changed wifi channel, but it hasn't made any difference. They work fine in the Meross app and the wifi signal strength is pretty much always near 100%. Pulling my hair out here - anyone any more ideas?

**Comment by wsw70** [comment]
> Are people still having problems with Meross devices becoming unavailable?

I had this problem and I think it was due to throttling on the Meross cloud side (wildly guessing).

I moved all my devices to my local MQTT and have absolutely no more problems. Besides this I am much more confident that this is a long-term solution as I am not dependent on a mechanism I do not control) (and its limitations).

**Comment by escaflown23** [comment]
> > Are people still having problems with Meross devices becoming unavailable?
> 
> I had this problem and I think it was due to throttling on the Meross cloud side (wildly guessing).
> 
> I moved all my devices to my local MQTT and have absolutely no more problems. Besides this I am much more confident that this is a long-term solution as I am not dependent on a mechanism I do not control) (and its limitations).

How did you do the migration to local MQTT?  I would like to follow the same path.

**Comment by wsw70** [comment]
> How did you do the migration to local MQTT?

Please see https://github.com/bytespider/Meross/issues/13#issuecomment-774434157.
Let me know if you have questions, this was a wild ride :)

**Comment by No-Smart** [comment]
Yes

**Comment by wsw70** [comment]
> Is this still an issue with v1.1.4?

For another data point - I never had this issue across all of my devices.

**Comment by No-Smart** [comment]
this is  the problem that block Meross Cloud, i reived  from MEROSSthis mail:

Dear Meross User,


This is Meross Customer Support Team contacting you!


We reach out to you due to a warning that just received from Meross Cloud Server, that your meross device was accessing the server with high frequency. We consider these behaviors abnormal and are concerned about the security of your devices. We might terminate the cloud services of these devices to avoid any further potential damage

 

Did you use any 3rd party API or plugin program? If so may we have some details about it? If you are sure that your devices are safe, NOT hacked, and are performing as expected. Please first lower your periodic request rate to NO more than one message every ten seconds and then send an email to support@meross.com. We will resume cloud service for you within 24 hours.

Should you have any information you would like to provide us with or would like to offer us any clarification, please contact us within as soon as possible.


We look forward to hearing back from you.


Have a good day!

 

Best Regards,

**Comment by wsw70** [comment]
> this is the problem that block Meross Cloud, i reived from MEROSSthis mail:

I may be misunderstanding something here - but the integration is for a local MQTT broker, not the Meross one.

**Comment by krelltunez** [comment]
I'm a bit confused as well.  I'm using the HACS integration.  I have not moved anything to MQTT (I wouldn't even begin to know how to do that).  I frequently have one or all of my Meross devices appear as unavailable in HA.  Note that when this happens, they are still available in the Meross app.  I have found a number of ways to bring them back in HA:

1. Using the Meross app to operate the switch, or operating the switch manually.
2. Reloading the integration through HA.

Unfortunately, there's no (easy) way to automate 2 above, yet.  I am hopeful that a future HA release will enable automating reloading of integrations.  For now, when I see them offline, I manually reload the integration.

FYI, I have no automations that involve the Meross switches, so I am not interacting with these switches very often.

I may be missing some of the points raised in this thread.  I'm very comfortable with HA, but basically a beginner when it comes to things like MQTT.

**Comment by wsw70** [comment]
> I have not moved anything to MQTT

I am sorry, I mixed up two integrations (I was having https://github.com/krahabb/meross_lan in mind and did not realize where the thread was). Forget what I wrote about local MQTT because apply here (local MQTT for Meross is wonderful, though, as it liberates you from the Meross cloud)

**Comment by Florian-Schmidt** [comment]
`Unfortunately, there's no (easy) way to automate 2 above, yet. `

@krelltunez What do you mean, you are talking about having many devices or where is it difficult?

**Comment by krelltunez** [comment]
> @krelltunez What do you mean, you are talking about having many devices or where is it difficult?

When this started happening, and I realized that reloading the integration would bring everything back online in HA, I set out to add an automation to reload the integration periodically.  Unfortunately, there's no (easy) way to do that, as there is no action for reloading integrations.  Some folks have figured it out for other integrations but the solutions are far beyond my skillset.

I only have 5 Meross devices so no issue with too many devices.

**Comment by Florian-Schmidt** [comment]
> I only have 5 Meross devices so no issue with too many devices.

I also tried to reload an integration automatically and didn't find an easy way to do this. Afterwards I tried to update an entity. Perhaps this helps as a workaround.

![CE344A02-CAA7-4BA9-AFCA-1FDFB9929C4E](https://user-images.githubusercontent.com/62351739/131375250-2c4faf41-ae0b-4508-bd60-1aa85cb276e8.jpeg)

**Comment by krelltunez** [comment]
I tried that and I believe it had no effect.  The automation I tried to create looked exactly like yours!

**Comment by krelltunez** [comment]
UPDATE:  @Florian-Schmidt that workaround may have worked.  Since implementing it, I've yet to have my devices become and remain unavailable.  In fact, they went offline 3 hours ago and the automations seem to have brought them back.  I'll keep an eye on this for a while and report back.

**Comment by novisys** [comment]
Same problems here !
I have 8 MS310 Plugs - usually 4 or 6 goes offline. They'll come back eventually (even without a reboot). The devices remain online in the Meross app, so this definitely has to do with the connectivity between Meross and HA.
Any Update for this frustrating issue ?

I'm hoping this can be fixed in a future update.

**Comment by Pangslinger** [comment]
I do have the same problem and restarting HA or replugging the devices did not help (this time, at least).
I believe it happend, when my router restarted and shuffled around IP-adresses. I was able to reenter the current IP-adress of a device and after reloading it works again. My solution will be to create static IP-adresses for all the meross devices within the router. That sucks but hopefully it will be a long-term solution.
