### ISSUE TITLE
incorrect values being reported

### ISSUE THREAD

**Issue by omega015** [albertogeniola/meross-homeassistant#188]
Unless I'm mistaken, either the wattage or the amps values are incorrect at lower consumption. At 2230W, 240v, Amps shows 11.04 which is about right taking power factor and slight variations into account. But at when its reporting 275W at 240v the amps shows 5.457 which is incorrect and either the wattage should be around 1000W or the amps should be around 1.2. 

Is this a software issue or hardware or simply just how meross report the values and nothing we can do? Or could it be that the values are being retrieved at different times so they are not lining up?

**Your environment**
HomeAssistant version: 2020.12.2
Hassio Version (if applicable): 2020.12.7
Hardware environment: Synology DSM, Docker 18.09.8

**Comment by omega015** [comment]
Forgot to mention the wattage being reported in home assistant seems to be inline with what the app reports at the time.

**Comment by albertogeniola** [comment]
Hi @omega015 ,

you cleverly pointed out that the value reported on the App is the same as the one reported on HomeAssistant. This basically means that the plug is misreading the value and there is little or nothing we can do on software level to adjust that. Values shown on HA are the ones reported by the plug itself.

**Comment by omega015** [comment]
Sorry to reopen, but is the plug/meross  reporting the current/Amps? As i don't see this information in the app, so wondered if this was just not being used by the app or if you are calculating current from voltage and watts?
