### ISSUE TITLE
Stop function for Merros Garage opener

### ISSUE THREAD

**Issue by manuelo1983** [albertogeniola/meross-homeassistant#19]
At the moment there is only the button for open and close, but there is no function to stop the garage door.

**Comment by guitarmanusa** [comment]
I'm not aware of even the Meross App being able to do this.  I don't think this is a functionality offered by the MSG100.

**Comment by albertogeniola** [comment]
Guitarmanusa is right: as far as I can tell, there is no such functionality on the MSG100 device. This, the library is unable to implement such request.
