### ISSUE TITLE
MQTT offline support

### ISSUE THREAD

**Issue by RedFoxy** [albertogeniola/meross-homeassistant#191]
It will be usefull to use Meross device offline, I found a way to connect Meross device on a local MQTT but I'm unable to use it by Home Assistant, I found different and valid solutions, like meross-powermon https://github.com/davidb24v/meross-powermon/ and Meross by bytespider https://github.com/bytespider/Meross, with both I was able to connect a Meross MSS530H to my WiFi and local mosquitto with TLS and anonymous configurations (more here: https://github.com/bytespider/Meross/wiki/MQTT and https://wltd.org/posts/how-to-use-meross-smart-devices-as-cheap-offline-iot#mcetoc_1eh3002vm2d), but after that I was unable to use it directly from Home Assistant, for two troubles:

- I need to use a different MQTT server for Meross because we are forced to use a anonymus connection so you can't use username and password for other device
- I tryed to use MQTT to turn on and off the switch but not successiful like:
/appliance/{ID of my Meross MSS530H}/publish ->{"payload":{"togglex":{"channel":1,"onoff":1}}}

Maybe will be easy to use python directly I don't know, but I'm sure that you have a lot of expirience with Meross so maybe you can add an offline support in your plugin

**Comment by albertogeniola** [comment]
Hi @RedFoxy ,

that's under development (#144) but it will take some time. At the moment we are developing the [low-level python library](https://github.com/albertogeniola/MerossIot/projects/2) for that, and then the plan is to bring this functionality on HA component.
