### ISSUE TITLE
Home Assistant Crashed when turn on/off lights using meross

### ISSUE THREAD

**Issue by mondotech9** [albertogeniola/meross-homeassistant#194]
When i turn on and turn off lights connected in meross hacs home assistant returns error: "Failed call to service homeassistant/turn_off"

HomeAssistant version:  2020.12.2
python version: 3.9.1 
Hardware environment: Raspberry p3

I am forced to reload meross hacs to repair this bug.

**Comment by heroxy2111** [comment]
Same Problem here, adding my log
[HA-Log Meross.txt](https://github.com/albertogeniola/meross-homeassistant/files/5849343/HA-Log.Meross.txt)
