### ISSUE TITLE
Status for garagedoor closing instead of closed

### ISSUE THREAD

**Issue by bvdkerkhof** [albertogeniola/meross-homeassistant#20]
After boot of HomeAssistant the meross plugin is telling me the Garagedoor is "Closed". When I open it, status changes to Opening. When the door is fully opened it still says Opening. When closing it back status changes to Closing. It will then stay at closing and not report back it is Closed.

The Meross app sends a message the garagedoor is closed, but never changes in HA. Not sure if this is possible but would be usefull to have it tell me if it is Closed instead of Closing.

**Comment by GeneralErrors** [comment]
I'm having the same, or similar, issue …

It appears this Opening/Closing status only occurs when using the controls through Home Assistant.  Using the controls through the Meross App or Widgets affects the status correctly.  However, once the controls in Home Assistant are used the status seems to stay broken only reporting Closing or Opening and staying as such until Home Assistant is restarted.

**Comment by mdscarrott** [comment]
Hi @albertogeniola 

I can confirm this is an issue as reported by @GeneralErrors , not just a feature request or enhancement.

If the garage door is also being controlled by the Meross app, or by a garage opening button, the status stops responding staying at 'opening' or 'closing' and the control arrows up and down do not change to reflect the logical next command. Basically it seems to lock up. The app still works fine though as expected and other integrations work through this like the smartthings integration so i don't think it is an issue at the Meross end.

Happy to provide more info as required - lease let me know what you need and where/how i find it for you from hassio. 

Great work on the integration, i bought you a beer yesterday to show my appreciation. 

Matt

Meross MSG100
Home Assistant 0.102.3
Hass.io supervisor: 192
HassOS 2.12

**Comment by rubin110** [comment]
Seeing the same issue. Once I've tiggered a close of the garage door I can't interact with it again until I restart Home Assistant.

**Comment by albertogeniola** [comment]
Hi guys. I've tried to reproduce the problem on a brand newly installed version of MerossIot component, bit it seems to work just fine. I'll try to keep it on for a while to see if the problem shows up after a bit. 
In the meantime, I'll need to gather more information about your devices. Which firmware version of the MSG100 are you using?

**Comment by GeneralErrors** [comment]
Just updated Home Assistant to the latest version (0.103.3) and still having the same issue.  

Firmware version for me is 3.1.7 on hardware version 3.0.0 and this issue affects all 3 openers I have.

Easy steps to reproduce for me is ... 
1. Start Home Asssitant
2. Open MSG100 from Home Assistant Lovelace UI 
 - MSG100 will open as expected
3. Check states within Home Assistant
 - State for cover.msgopener is now stuck in opening 

One of the MSG100s controls a gate so it auto closes - the state never updates after the initial "opening" issue unless I restart Home Assistant and only use the Meross app.  MSG100 cover states are reported correctly in Home Assistant when using the Meross app.

Thanks for your hard work ... let me know if you need more info.

**Comment by bvdkerkhof** [comment]
Just checked:

HA is running on 0.103.2
Firmware: 3.1.7
Hardware version 3.0.0

Also just like GeneralErrors commented, the addon works just fine except for the state in HA. 

1. Open Garagedoor with HA through LoveLace-UI
2. Garagedoor opens just fine
3. Garagedoor opened fully --> State in HA is still Opening
4. Close Garagedoor with HA throught LoveLace-UI
5. Garagedoor closes as expected
6. When closed state in HA keeps on Closing

When you restart HA the state is back on Closed.

Thanks a lot and if you need more info or want me (or us) to test something just let me know!

**Comment by albertogeniola** [comment]
Hi guys, 
I've performed some fixes in the latest version of the component. Do you mind update it and let me know if the problem persists?

**Comment by GeneralErrors** [comment]
@albertogeniola ... Still having the same issue unfortunately.  Just updated and tried both a gate and a garage door.  The state freezes in an opening/closing state once activated from Home Assistant as it did before.  

Thanks for your work on this - wish I could help more.

**Comment by albertogeniola** [comment]
Hi guys,
so, if the new version did not solve the problem, it probably means that the garate/gate opener you are using differs from mine. For this reason, I need you to collect some data for me in order to check whether that's the case or not. To do so, I need you to do the following:

- install Python 3.5/3.6/3.7 (any version above 3.5 will do just fine)
- download the meross-iot library 
```
pip3 install meross_iot
```
- run the meross_info_gather
```
meross_info_gather
```

The utility will ask for your Meross username and password to connect to your account. Once logged in, you should start playing with the Garage Door, simulating the exact sequence that causes the error you describe. When done, press ENTER on the keyboard and send me privately the data.zip which contains the logged data.

**Comment by albertogeniola** [comment]
Any updates on this?

**Comment by bvdkerkhof** [comment]
how to run the script? I did install the meross_iot library but don't know how to run it?

**Comment by albertogeniola** [comment]
Hi @bvdkerkhof ,
actually the MSG100 only supports 2 real states: closed and opened. There is no sensor on the MSG100 reporting the "closing" or "opening" states. Such transient states are "derived" by the app when a command is issued. I think that I should be doing the same with the custom component. In the next few days I'll try to find some time to give it a look and chek if I can emulate the "opening" state also into the component as it happens on the APP.

**Comment by bvdkerkhof** [comment]
Hi @albertogeniola that would be a cool addition. If you want me to make a dump / debug log let me know.

**Comment by albertogeniola** [comment]
Hi @bvdkerkhof ,
The latest version should provide that functionality you asked for. Can you test it and let me know if that works?

**Comment by coolguymatt** [comment]
I am having the same issue running 20200209.1. Let me know what information you need from me to troubleshoot.

**Comment by albertogeniola** [comment]
Hi guys, please update to the latest version and let me know how it goes.

**Comment by GeneralErrors** [comment]
This is working for me now ... thanks for the efforts.

**Comment by scannifn** [comment]
Hello @albertogeniola I've just done some tests and it doesn't seems to works proprerly.
In my test I've tried to use only Meross App and and check the state in HA. During this test HA reports correctly CLOSED or OPEN).
If I use HA commands to control doors garage I get the wrong state.... CLOSING or OPENING. It will never show CLOSED or OPENED.

![image](https://user-images.githubusercontent.com/67062892/86893561-17b42a00-c102-11ea-97e7-92929c56ed12.png)

The last two evets are done from HA. As you can see I never see the right state.

I you need more info you can ask.
Thanks in advance.

Nicola

**Comment by Protect130** [comment]
I am also having the same problem. I installed my opener in Dec 2020, and within a few weeks, it started having the same problem. Using the app, it shows the unit as being open, whether it’s open or closed. There aren’t any arrows to reflect it is going up or down, nevertheless it still works properly with any programmed command.
