### ISSUE TITLE
today_energy_kwh not outputting value

### ISSUE THREAD

**Issue by ameel** [albertogeniola/meross-homeassistant#212]
Hi, I have installed latest release on using HACS. I have mss310 switch configured. However, today_energy_kwh is outputting total_consumption_kwh rather than the actual value.

I'm looking to obtain the value of today energy consumption.

Please advise how to fix.

Details for entity switch.power_bedroom_mss310_main_channel
current_power_w: 13.266
today_energy_kwh: total_consumption_kwh
friendly_name: Power - Bedroom (mss310) - Main channel

**Comment by vbguy2011** [comment]
If anyone is looking for a temporary solution, this is what I have done:

Edit /config/custom_components/meross_cloud/switch.py
**Replace**
`    @property
    def today_energy_kwh(self) -> Optional[float]:
        if self._daily_consumtpion is not None:
            today = datetime.today()
            date, total = max(self._daily_consumtpion, key=lambda x: x.get('date'))
            return total`
**With**
`    @property
    def today_energy_kwh(self) -> Optional[float]:
        if self._daily_consumtpion is not None:
            total = 0
            today = datetime.today()
            daystart = datetime(year=today.year, month=today.month, day=today.day, hour=0, second=0)
            for x in self._daily_consumtpion:
              if x['date'] == daystart:
                total = x['total_consumption_kwh']
            return total`

the device should now accurately report today_energy_kwh for the day

**Comment by albertogeniola** [comment]
PR Merged, thanks a lot.-

**Comment by octaviz** [comment]
Hi!, I just bought 2 Meross MSS310 and it seems that it doesn't update the "today_energy_kwh" data if the Home Assistant is restarted, it does update, but if you don't it keeps the last data update, something is wrong here, some solution?, I have checked the switch.py code and it is already updated as indicated above.
