### ISSUE TITLE
Unknown Device Type

### ISSUE THREAD

**Issue by pnichols77** [albertogeniola/meross-homeassistant#217]
I've got a meross smart led bulb and an ambient light. Both work in Home Assistant with this integration, but they're showing errors in the log:

```
Could not find any known device class for device type (msl120j).
Could not find any known device class for device type (msl420).
```

**Comment by albertogeniola** [comment]
That's normal: the component is just saying that those devices are unknown to it (no cached device class is hardcoded for them), but their ability are guessed at runtime. You should be fine.
