### ISSUE TITLE
Installed meross-homeassistant, "Meross" does not appear in Integration list after restart

### ISSUE THREAD

**Issue by CTJohnK** [albertogeniola/meross-homeassistant#222]
- Using meross-homeassistant 1.0.5
- Added folder "meross_cloud" to "config/custom_components"
- From Configuration/Server Controls, restarted HA
- Error in log indicating Version is required.
- From Configuration/Integrations
- 	Add Integrations
- 		type in "meross", nothing appears.

- updated "manifest.json" to include "version": "1.0"
- From Configuration/Server Controls, restarted HA
- Error in log indicating an error reading line 10, column 3 regarding character 321.
- From Configuration/Integrations
- 	Add Integrations
- 		type in "meross", nothing appears.

HomeAssistant version: 2021.3.4 in Synology Docker
Hardware environment: Synology DS920+

**Comment by CTJohnK** [comment]
Never mind, I was missing the 'comma' from the previous line.  However, even with "version": "1.0" I get a version warning.

**Comment by jrbecart** [comment]
Thanks, I just understood why I could't configure it.
