### ISSUE TITLE
MSG-200 becomes unavailable after use of physical opener

### ISSUE THREAD

**Issue by yonigold1** [albertogeniola/meross-homeassistant#223]
**Describe the bug**

I have a MSG-200 setup with this awesome plugin however I have found that when I use the physical keypad or remote the garage becomes unavailable it happens every time and the only way to fix it is restarting home assistant. 

**Your environment**
HomeAssistant version: -- 2021.4.4 --
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: -- RaspberryPi 4

 --

**Logs taken when the issue happened**
```
--- PASTE LOGS HERE ---
```
<img width="398" alt="Screen Shot 2021-04-14 at 12 05 41 PM" src="https://user-images.githubusercontent.com/34217684/114742443-bfa5f600-9d19-11eb-8c37-812efbf0593c.png">

**Comment by sccofer** [comment]
I am seeing the same behavior...
