### ISSUE TITLE
Error in new HA 2021.5

### ISSUE THREAD

**Issue by crybakk** [albertogeniola/meross-homeassistant#227]
![Screenshot_20210505-230307](https://user-images.githubusercontent.com/48298703/117209220-5be18b00-adf6-11eb-90d0-6e6e67bd3a46.jpg)

**Comment by tarheelz** [comment]
There is a pending pull request to fix this.

**Comment by crybakk** [comment]
> There is a pending pull request to fix this.

OK thanks
