### ISSUE TITLE
ATTENTION: Service Termination of Your meross Smart Device due to Security Concerns

### ISSUE THREAD

**Issue by aRomaSoloLaLazio** [albertogeniola/meross-homeassistant#229]
**Describe the bug**
Hello,
I want to report that since the installation of "meross-homeassistant" in 10 days Meross has blocked 3 times my devices  (the last today at 1:56 PM), communicating the block to me through the following email: 

"Dear Customer,
This is meross cloud security team contacting you.
First of all, thanks for purchasing meross and we hope that you enjoy life with our smart products.
Recently our cloud security system has noticed that your devices are communicating with the could server at an extremely high frequency. We consider these behaviors abnormal and are concerned about the security of your devices.
Due to the security concerns and the intent to avoid any further potential damage, we will terminate the cloud services of these devices for now.
If you are sure that your devices are safe, NOT hacked, and are performing as expected. Please first lower your periodic request rate to no more than one message every ten seconds and then send an email to <cloudservice@meross.com>. We will resume cloud service for you within 24 hours. Please note that any abnormal high cloud request frequency will cause cloud service termination again.
Should you have any information you would like to provide us with or would like to offer us any clarification, please contact us within 24 hours."

I noticed that several users had already reported the same problem but I understood that with the upgrades it had been solved, but it doesn't seem like that to me.

Thank you

**Your environment**
HomeAssistant version: core-2021.4.4
Hardware environment: Raspbian on AMD Laptop 

**Logs taken when the issue happened**
Uncaught push notification Namespace.HUB_SENSOR_TEMPHUM. Raw data: {"tempHum": [{"syncedTime": 1620622263, "sample": [[201, 680, 1620622263, 1620625863, 0], [201, 680, 1620625863, 1620629463, 0], [201, 680, 1620629463, 1620633063, 0], [201, 680, 1620633063, 1620636663, 0], [201, 680, 1620636663, 1620637254, 0], [205, 640, 1620637254, 1620640854, 0], [205, 640, 1620640854, -10000, 0]], "latestTime": 1620641885, "latestTemperature": 205, "latestHumidity": 640, "id": "120027D1E471"}]}
13:56:10 – (AVVERTIMENTO) /srv/homeassistant/lib/python3.8/site-packages/meross_iot/manager.py - il messaggio si è verificato per la prima volta alle 6 maggio 2021, 9:48:07 e compare 280 volte
Device Camera (#BASE:2010099697780126280748e1e93547c5#SUB:01006446) has been already added to the registry.
13:56:10 – (AVVERTIMENTO) /srv/homeassistant/lib/python3.8/site-packages/meross_iot/manager.py - il messaggio si è verificato per la prima volta alle 6 maggio 2021, 9:48:06 e compare 490 volte
Skipping device <Entity Soggiorno (mts100v3) - temperature sensor (°C, 0): 21.0> as it was already added to registry once.
13:56:09 – (AVVERTIMENTO) Meross Cloud IoT - il messaggio si è verificato per la prima volta alle 6 maggio 2021, 9:48:07 e compare 112 volte
Device Bagno 1 (mts100v3) - temperature sensor (°C, 0) reported online event.
13:56:07 – (AVVERTIMENTO) Meross Cloud IoT - il messaggio si è verificato per la prima volta alle 6 maggio 2021, 9:48:05 e compare 48 volte
Device Soggiorno (mts100v3) reported online event.
13:56:07 – (AVVERTIMENTO) Meross Cloud IoT - il messaggio si è verificato per la prima volta alle 6 maggio 2021, 9:48:05 e compare 36 volte
An unhandled exception occurred while handling push notification
13:51:34 – (ERRORE) /srv/homeassistant/lib/python3.8/site-packages/meross_iot/manager.py - il messaggio si è verificato per la prima volta alle 6 maggio 2021, 9:48:07 e compare 274 volte
albertogeniola/meross-homeassistant - GitHub returned 502 for https://api.github.com/repos/albertogeniola/meross-homeassistant
4:54:53 – (ERRORE) HACS
<Plugin rsnodgrass/water-heater-card> GitHub returned 404 for https://api.github.com/repos/rsnodgrass/water-heater-card
4:54:53 – (ERRORE) HACS - il messaggio si è verificato per la prima volta alle 7 maggio 2021, 18:55:56 e compare 2 volte
Updating DuckDNS domain failed: aromasololalazio
4:50:03 – (AVVERTIMENTO) Duck DNS - il messaggio si è verificato per la prima volta alle 3 maggio 2021, 17:20:04 e compare 7 volte
Timeout fetching shellyswitch25-68C63AFA452F data
9 maggio 2021, 22:28:56 – (ERRORE) Shelly - il messaggio si è verificato per la prima volta alle 3 maggio 2021, 18:34:37 e compare 15 volte
Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: Bagno 2 UUID: 2010099697780126280748e1e93547c5 Type: mts100v3 HW Version: unknown FW Version: unknown Error Message: "An exception occurred"
9 maggio 2021, 22:28:39 – (ERRORE) Meross Cloud IoT - il messaggio si è verificato per la prima volta alle 7 maggio 2021, 0:00:21 e compare 5 volte
Timeout occurred while waiting a response for message b'{"header": {"from": "/app/1200922-eb82239d6ba8d98dda7ee1aaf3e235b3/subscribe", "messageId": "516411de4a8e7fbfb88a3d66481bef6d", "method": "GET", "namespace": "Appliance.Hub.Mts100.Temperature", "payloadVersion": 1, "sign": "5f58b14427493b265a68abdb57cf11ff", "timestamp": 1620338417, "triggerSrc": "Android"}, "payload": {"temperature": [{"id": "01009C78"}]}}' sent to device uuid 2010099697780126280748e1e93547c5. Timeout was: 5 seconds.
9 maggio 2021, 22:28:39 – (ERRORE) /srv/homeassistant/lib/python3.8/site-packages/meross_iot/manager.py - il messaggio si è verificato per la prima volta alle 7 maggio 2021, 0:00:21 e compare 5 volte
Updating meross_cloud sensor took longer than the scheduled update interval 0:00:15
9 maggio 2021, 22:28:34 – (AVVERTIMENTO) Sensore

**Comment by albertogeniola** [comment]
duplicate of #250
