### ISSUE TITLE
Meross Client is becoming unavailable, only restart of the Integration helping

### ISSUE THREAD

**Issue by Chaosflori25** [albertogeniola/meross-homeassistant#231]
**Describe the bug**
The Meross Client is becoming unavailable, only a restart of the Integration is solving the issue. It returns about every 10-20 hours. I tried both branches: Beta and Normal but this did not solve the issue.

**Your environment**
HomeAssistant version: -- Home Assistant OS 5.13 --
Hassio Version (if applicable): -- supervisor-2021.04.3 --
Hardware environment: -- Raspi 3B+ --
Meross Client Version: -- 0.4.1.0rc7 --

**Logs taken when the issue happened**
```
1. (6 occurrences)

Error setting up entry ...@gmail.com for switch
Error setting up entry ...@gmail.com for cover
Error setting up entry ...@gmail.com for sensor
Error setting up entry ...@gmail.com for climate
Error setting up entry ...@gmail.com for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 420, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 164, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

2. (2 occurrences)

Setup of switch platform meross_cloud is taking over 10 seconds.

3. (42313 occurrences)(really that's what Homeassistant is saying)

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/wled/light.py", line 467, in async_remove_entity
    await entity.async_remove(force_remove=True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 594, in async_remove
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity light.wled_segment_1 async_remove called twice

```

**Comment by masmar2007** [comment]
same problem here!

**Comment by amanimmortal** [comment]
Seeing the same thing.

**Comment by dadevil87** [comment]
Same issue here

HomeAssistant version: -- Home Assistant OS 5.13 --
Hassio Version (if applicable): -- supervisor-2021.5.4 --
Hardware environment: -- Raspi 4B --
Meross Client Version: --1.0.5 --

**Comment by Zill11** [comment]
Having this same issue with Raspi4B and HA 2021.5.3. Works fine after a restart for up to a day but then just loses connection with all meross devices until another restart. First saw this issue starting to appear some weeks ago and with HA 2021.4

**Comment by tarheelz** [comment]
This is a long-running issue. #225  For now the work-around is either a Node Red flow or Automation to restart Home Assistant whenever Meross starts reporting "unavailable."

**Comment by yonigold1** [comment]
can someone please attach their home assistant automation to show how to make one?

**Comment by willba050** [comment]
I was having the same issue a while ago (4-5 months ago) so I created an 'Automation' to 'restart' the entity when it became unavailable for more than 20 seconds. 
I only deleted it last week as it hadn't ran for over 3 months and then after Meross cloud IoT latest update it started to happen again (face slap).
there seems to be more options now on updating entities since I last did this as I remember I had to write something in YAML
anyway, I've attached the YAML of my latest automation: hope this helps Yonigold1:

alias: Reload Meross when unavailable
description: ''
trigger:
  - platform: state
    entity_id: switch.************_mss310_main_channel
    to: unavailable
    for: '00:00:20'
condition: []
action:
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      entity_id: switch.********_mss310_main_channel
mode: queued
max: 10

**Comment by geejayem99** [comment]
Thanks, that works quite well. I don't know if it's the same for others but having done this I noticed that it becomes unavailable every 6 hours within +/- 30 seconds.

I had 1 mss310 switch initially and didn't have any problems with it going offline at all. It was only once I bought another 4 pack it started doing this.

**Comment by yonigold1** [comment]
thanks for sharing! i have also created my own! which i will attach and it seems to work every time so far! (i know there are 2 triggers i'm too lazy to figure out which one is the one that actually works)



`alias: Reload (Duplicate)
description: Reloads Smart Garage Door when connection drops
mode: single
trigger:
  - platform: state
    entity_id: cover.smart_garage_door_opener_msg200_garage_door_1
    to: Unavailable
    for: '00:05:00'
    from: Open,Closed
  - platform: state
    entity_id: cover.smart_garage_door_opener_msg200_garage_door_1
    to: unavailable
    for: '00:05:00'
condition: []
action:
  - service: homeassistant.reload_config_entry
    target:
      device_id: 05400976f2474bcffcba0acc1a44cb9b
    data: {}
`

**Comment by albertogeniola** [comment]
Is this still happening with version v1.1.0?

**Comment by geejayem99** [comment]
Do I need to install 1.1.0 manually or just wait a bit for it to show in HACS. I have 'Show beta' turned on, but 1.0.7 is the latest release showing in HACS. Is a manual install just copying the files in the meross_cloud folder from the release zip over the top of  meross_cloud in my custom_components folder. There seems to be a lot of other files in the release other than these.

**Comment by helmarw** [comment]
even after updating to 1.1.0 Meross disabled the service due to communicating with the cloud server at an extremely high frequency. (they sent an email)

![image](https://user-images.githubusercontent.com/10408121/129355666-ce807744-65a9-45a5-92bd-e1bf9a3e0901.png)

i removed it entirely for now until its fixed

**Comment by albertogeniola** [comment]
Version 1.1.2 is out. It now enables custom API rate limiting configuration from component configuration interface. You should be able to "Tune" rate limiter to avoid Meross Ban.
