### ISSUE TITLE
MSS310 is being found, but switch is missing.

### ISSUE THREAD

**Issue by enomam** [albertogeniola/meross-homeassistant#233]
**Describe the bug**
I've just enabled the custom component, and have two MSS310 switches installed.
The integration picks up all the sensors, but it haven't exposed the switch entity, so cannot turn these devices on or off!

<img width="270" alt="2021-05-17_19-39-22" src="https://user-images.githubusercontent.com/7985914/118468156-d5a73c00-b747-11eb-86ab-e867b58ec8d7.png">

**Your environment**
HomeAssistant version: -- core-2021.5.4
Hardware environment: -- docker container

**Logs taken when the issue happened**
```
N/A
```

**Comment by nauj27** [comment]
I have the same issue 

## System Health

version | core-2021.2.0
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 4.19.66-v7+
arch | armv7l
timezone | Europe/Madrid

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 0
views | 12
mode | storage

</details>

**Comment by albertogeniola** [comment]
Hi!
Ok, to better debug this, we should look at what the MerossIot low-level library picks up at discovery time. You should:
1. Restart Homeassistant core
2. Wait for it to come operational again
3. Look at the HA Core logs
4. Post the logs you see from the meross discovery

I suspect your MSS310 device reports some "new ability" for switching that has not been implemented yet. We can should be able to see this from the logs.
