### ISSUE TITLE
After Install Meross Cloud IoT No Integrations appear

### ISSUE THREAD

**Issue by matfil92** [albertogeniola/meross-homeassistant#236]
**Describe the bug**
I've installed Meross Cloud IoT in HACS and reboot Home Assistant.
After reboot if I go in Integration --> Click on + button --> and looking for Meross nothing will be founded!

I've already tried to reinstall the Meross Cloud IoT in HACS and reboot it but doesn't work.

**Your environment**
HomeAssistant version: core-2021.5.5
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: Proxmox
HACS Meross Cloud IoT version: 1.12.4

**Comment by Toinieboy** [comment]
Same issue here!, Ran through al the steps but i can't find it in the intgrations list.....

![image](https://user-images.githubusercontent.com/66773265/120310738-fee2d300-c2d6-11eb-93b1-214f38e4afc9.png)

**Comment by matfil92** [comment]
I've Nearly resolved putting the code in configuration.yaml

**Comment by 2stooges** [comment]
Still same issue of not showing in Integrations after install with HACS. Even after upgrading to core-2021.6.0b5

**Comment by Jacox98** [comment]
You must add a version key to manifest.json file in merros_cloud folder
example "version": "1.0.5"

After re-add the integration in Home Assistant

**Comment by 2stooges** [comment]
> You must add a version key to manifest.json file in merros_cloud folder
> example "version": "1.0.5"
> 
> After re-add the integration in Home Assistant

That worked for me. Added version in manifest.json like:

  "name": "Meross Cloud IoT",
  "version": "1.0.5",
  "documentation": "https://www.home-assistant.io/components/meross_cloud",

And it added in integrations no problem Thanks Jacox98, good to know in the future.

**Comment by giantsfan006** [comment]
> You must add a version key to manifest.json file in merros_cloud folder
> example "version": "1.0.5"

I added this to my manifest.json and it still doesn't appear when searching integrations... Does anyone have any ideas?

**Comment by Toinieboy** [comment]
Yes! That worked for me as well!:) Thank you!

> > You must add a version key to manifest.json file in merros_cloud folder
> > example "version": "1.0.5"
> 
> I added this to my manifest.json and it still doesn't appear when searching integrations... Does anyone have any ideas?

Remove the EXAMPLE

![image](https://user-images.githubusercontent.com/66773265/120604211-19d75380-c44d-11eb-9ebb-b0cca6bed3cc.png)

**Comment by giantsfan006** [comment]
> Remove the EXAMPLE

Lol. Good looking out! Sometimes it's the simple things. It was the stupid browser cache...

**Comment by SteveB2L8** [comment]
**Hello, no install button when i try to add the integration. Thanks to who will help** 
See screenshot below

![image](https://user-images.githubusercontent.com/101350607/158016388-96053fbf-fb78-468c-80e9-8f2941cc9e5a.png)
