### ISSUE TITLE
Version missing from manifest.json, now required field

### ISSUE THREAD

**Issue by teknomar7** [albertogeniola/meross-homeassistant#239]
Today's release of HA (version 2021.6) now requires a version to be included in the manifest.json file or the integration won't start. A work around is just to open the file and add the line entry `"version": "1.0.5"` and restart HA.   

Requirement is described here:
https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/#versions

**Comment by alberisca75** [comment]
hi, i'm trying but it doesn't work! I added "version": "1.0.5" and also changed: from "requirements": ["meross-iot == 0.4.1.0rc7"], to "requirements": ["meross-iot == 0.4.1.1rc1 "], but without success !!

**Comment by teknomar7** [comment]
I only added the k/v I mentioned along with a preceding common to make it valid json.  This is what my manifest.json file looks like (and don't forget to restart HA after you make changes... I think with a docker install, you should restart from within the app and not restart the entire container).

```
{
  "domain": "meross_cloud",
  "name": "Meross Cloud IoT",
  "documentation": "https://www.home-assistant.io/components/meross_cloud",
  "dependencies": ["persistent_notification"],
  "codeowners": ["@albertogeniola"],
  "requirements": ["meross-iot==0.4.1.0rc7"],
  "config_flow": true,
  "quality_scale": "platinum",
  "version": "1.0.5"
}
```

**Comment by alberisca75** [comment]
now i've done the copy and paste from yours, i restarted Home Assistant OS (i don't use docker)! unfortunately nothing for me! meross does not appear in the additions

**Comment by teknomar7** [comment]
I use Docker on Synology for HA.  I did a reinstall first from HACS before I changed the manifest.json.  I assumed that really did nothing but reinstall what was already there, but perhaps that fixed one problem and the json fixed another.  Not sure, but probably should mention that just in case.  I didn't uninstall... just selected the reinstall option for the integration in HACS.  Didn't have to reconfigure login or anything.

**Comment by alberisca75** [comment]
Luckily I'm on proxmox! now i restore the full backup, and i just try editing the manifest.json file without uninstalling anything! Thank you!

**Comment by alberisca75** [comment]
if anyone can help I solved it by restoring the backup then I added to the file "version": "1.0.5" without restarting I updated hassios and everything was working on restart!

**Comment by Raul-7-7** [comment]
https://github.com/albertogeniola/meross-homeassistant/issues/218 Duplicate.

**Comment by teknomar7** [comment]
Closing per duplicate mentioned.
