### ISSUE TITLE
Rate Limit Issues in 2021.6

### ISSUE THREAD

**Issue by pnichols77** [albertogeniola/meross-homeassistant#240]
**Describe the bug**
My Meross integration was working fine under 2021.5. After updating to 2021.6 the integration fails to load, with the log indicating rate limit issues. I updated after adding the version number (1.0.5) to the manifest.json file. 

**Your environment**
HomeAssistant version: 2021.6
Hardware environment: Rapsberry Pi, HA container. 

**Logs taken when the issue happened**
```
Logger: custom_components.meross_cloud
Source: custom_components/meross_cloud/__init__.py:143
Integration: Meross Cloud IoT
First occurred: 9:10:14 (9 occurrences)
Last logged: 9:21:01

Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: <Unavailable> Error Message: "An exception occurred while setting up the meross manager. Setup will be retried..."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/__init__.py", line 143, in async_setup_entry
    await manager.async_device_discovery()
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 262, in async_device_discovery
    enrolled_devices = await asyncio.gather(*tasks, loop=self._loop)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 316, in _async_enroll_new_http_dev
    res_abilities = await self.async_execute_cmd(destination_device_uuid=device_info.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 609, in async_execute_cmd
    raise RateLimitExceeded()
meross_iot.model.exception.RateLimitExceeded

```

**Comment by Bazarov42** [comment]
Same Here !
I reinstalled the snapshot from before the update

**Comment by kloodhu** [comment]
same.

**Comment by salvasacie** [comment]
Same problem.

**Comment by Chaosflori25** [comment]
same

**Comment by gitioda** [comment]
same problem

**Comment by dellrichrichdell** [comment]
Likewise.

**Comment by Odinlistening** [comment]
Same issue here. I am of the opinion the update breaks how custom components are handled, as a 'Variable' component I have used for a very long time also suddenly does not load with core update. Revert to snapshot, both components load as normal.

**Comment by gianlucaromito** [comment]
same here
reverted back to 2021.5.5

**Comment by marceskenazi** [comment]
Ditto. Same issue. Went back to 2021.5.5.
Any chance of a fix? Thanks.

**Comment by nibblerrick** [comment]
Adding the version key and installing the 1.0.6-beta through hacs seems to give me a working setup. Maybe worth a try?

**Comment by Manfredi93** [comment]
same problem

**Comment by albertogeniola** [comment]
Hi guys, it looks like the newest version of HA is even more aggressive on polling. That breaks the Meross API rate limiter. 
Unfortunately, until the Local LAN Addon is completed, any attempt to fix this on component side is useless. 
Hopefully, the local addon should fix this for good.

**Comment by dellrichrichdell** [comment]
Thx.  Do we know when that will be available?

**Comment by pnichols77** [comment]
Thanks for the update @albertogeniola 

I've created a Smart Things account and added that integration to Home Assistant which works (though i dont like the extra 'hop' in the chain). It's a workaround until there's a local method.

**Comment by Bazarov42** [comment]
The last update solved the problem !
All good for me, thx !

**Comment by dellrichrichdell** [comment]
me too thanks.

**Comment by gitioda** [comment]
The last update solved the problem !
great thanks for this quick update !
core-2021.6.1
supervisor-2021.05.4
Home Assistant OS 5.13
Meross Cloud IoT 1.0.7
hacs 1.12.4
on raspberry PI
regards,
Philippe :-)

**Comment by gianlucaromito** [comment]
Working fine here too:
Meross Cloud IoT 1.0.7
hacs 1.12.4
core-2021.6.2

Thanks !

**Comment by albertogeniola** [comment]
Nice to hear that guys. Closing.
