### ISSUE TITLE
Meross integration stop working after update 

### ISSUE THREAD

**Issue by mcevansw** [albertogeniola/meross-homeassistant#241]
The following integrations and platforms could not be set up:
meross_cloud
Please check your config and logs.

Logger: homeassistant.setup
Source: setup.py:172
First occurred: 10:42:27 (1 occurrences)

Setup failed for meross_cloud: Integration not found.

Meross integration will not load following the  update to HA 2021.6.0

**Comment by DuckyNZ** [comment]
Same here. Broken after HA 2021.6.0 update.

2021-06-03 23:29:38 ERROR (SyncWorker_5) [homeassistant.loader] The custom integration 'meross_cloud' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

2021-06-03 23:29:52 ERROR (MainThread) [homeassistant.setup] Setup failed for meross_cloud: Integration not found.

**Comment by mika59112** [comment]
Hello,
In file meross_cloud\manifest.json just add line :
"version": "1.0.0",
(with comma) and restart HA and it's good.

**Comment by pklijzing** [comment]
> Hello,
> In file meross_cloud\manifest.json just add line :
> "version": "1.0.0",
> (with comma) and restart HA and it's good.

Yes that works, thanks!

**Comment by mcevansw** [comment]
Thank you works like a charm , much appreciated

**Comment by lbehrler** [comment]
I am having the same issue... tried uninstalling and reinstalling and I have no integration available to select.

**Comment by mcevansw** [comment]
i had the same issue after uninstalling it caused more issues and would not show up after reinstalling until I did the below 

Remove the Meross component integration
Remove all the Meross Devices / Entities (Settings -> Etntities -> select all meross ones -> Delete )
Remove all Lovelace cards for old Meross devices
Reboot HA

when trying to install with the same browser I had no  integration available to select
After a few hours, I discovered if I moved to another browser the integration was available and after another restart, I was able to install it as it hung the first time.

 so delete everything and try again, if nothing to select then try a different browser with a few servers restarts in between

**Comment by lbehrler** [comment]
I gave it several hours and on the second attempt tonight it fired up and is working great. 

Thanks for all your help
