### ISSUE TITLE
Error on hassio 2021.7.0

### ISSUE THREAD

**Issue by giga89** [albertogeniola/meross-homeassistant#249]
The custom integration 'meross_cloud' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

System Health

version: core-2021.7.0
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.9.5
os_name: Linux
os_version: 5.10.17-v8
arch: aarch64
timezone: Europe/Rome

GitHub API: ok
Github API Calls Remaining: 4882
Installed Version: 1.12.4
Stage: running
Available Repositories: 910
Installed Repositories: 18

can_reach_server: ok
remaining_requests: 45

logged_in: true
subscription_expiration: 19 luglio 2021, 2:00
relayer_connected: true
remote_enabled: true
remote_connected: true
alexa_enabled: true
google_enabled: true
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

host_os: Home Assistant OS 6.1
update_channel: stable
supervisor_version: supervisor-2021.06.8
docker_version: 20.10.6
disk_total: 58.0 GB
disk_used: 20.8 GB
healthy: true
supported: true
board: rpi4-64
supervisor_api: ok
version_api: ok
installed_addons: FTP (4.2.0), Backup Hassio to Google Drive (1.7.10), Check Home Assistant configuration (3.7.1), FTP Backup (0.2.5), File editor (5.3.1), Grafana (7.0.2), Home Assistant Google Drive Backup (0.104.3), InfluxDB (4.1.1), MariaDB (2.2.1), Node-RED (9.2.0), Portainer (1.5.1), Terminal & SSH (9.1.3), Transmission (dev), chrony (2.2.0)

dashboards: 1
resources: 10
views: 9
mode: storage

**Comment by albertogeniola** [comment]
This was fixed starting from version 1.0.7
