### ISSUE TITLE
Meross Color Change 

### ISSUE THREAD

**Issue by bigstevehardy** [albertogeniola/meross-homeassistant#25]
I was just wondering if my new shiny Color Changing Meross Bulb can do a cycle effect to entertain the kids/disco ?

**Comment by albertogeniola** [comment]
Hi!
I guess you can script that with an automation of HA. I've little experience with that, but I've seen people doing so. Have a look at [here](https://community.home-assistant.io/t/syncing-led-lights-to-playing-music/38850/3).
