### ISSUE TITLE
Expected data source not listed (HA Energy Management)

### ISSUE THREAD

**Issue by JackONeill199** [albertogeniola/meross-homeassistant#254]
Unfortunately I can't add the entity to the Energy Management function that was newly added to Home Assistant. 
The Expected data source is not listed.

https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

**Your environment**
HomeAssistant version: -- core-2021.8.5 --
Hardware environment: -- Home Assistant OS 6.2 --

**Comment by albertogeniola** [comment]
Hi!
As written in the documentation, the feature requires some changes on the Sensor component logic. This, however, makes sense only for specific sensed data (e.g. power consumption) not for instant metrics as voltage or current measurements.

I'll mark this as a feature request for future releases.

**Comment by albertogeniola** [comment]
Implemented in ab3fa51b88a0bbf56b4a15d98307e4e2fa8b91c2 and released in v1.1.2
