### ISSUE TITLE
mss210 us rtl8710cf (hardware:6.0.0 firmware:6.1.12) unable to connect

### ISSUE THREAD

**Issue by platofan23** [albertogeniola/meross-homeassistant#255]
mss210 us rtl8710cf (hardware:6.0.0 firmware:6.1.12) not working with mosquito. The plug goes tries to connect to the internet but fails. I hear to clicks. First when the led changes flashing green and later going back into pairing mode.

my mosquitto conf is;
`port 1883
listener 8883
#use_username_as_clientid true
allow_anonymous true
capath /etc/ssl/certs

certfile /etc/mosquitto/certs/mqtt_server.pem
keyfile /etc/mosquitto/certs/mqtt_server.pem

tls_version tlsv1.1
My command:./meross setup --gateway 10.10.10.1 --wifi-ssid XXX --wifi-pass XXX --mqtt 192.168.2.201 --key XXX --mqtt 192.168.2.206

Setting up device with IP 10.10.10.1
┌────────────────────────────────────────────────┬────────────────────────────────────────────┐
│Primary MQTT broker │192.168.2.201:1883 │
├────────────────────────────────────────────────┼────────────────────────────────────────────┤
│Failover MQTT broker │192.168.2.206:1883 │
└────────────────────────────────────────────────┴────────────────────────────────────────────┘
┌────────────────────┬────────────────────────────────────────────────────────────────────────┐
│Device │mss210 us rtl8710cf (hardware:6.0.0 firmware:6.1.12) │
├────────────────────┼────────────────────────────────────────────────────────────────────────┤
│UUID │2012174007893251804648e1e9425940 │
├────────────────────┼────────────────────────────────────────────────────────────────────────┤
│Mac address │48:e1:e9:42:59:40 │
├────────────────────┼────────────────────────────────────────────────────────────────────────┤
│IP address │10.10.10.1 │
├────────────────────┼────────────────────────────────────────────────────────────────────────┤
│Current MQTT broker │192.168.2.201:1883 │
├────────────────────┼────────────────────────────────────────────────────────────────────────┤
│Credentials │User: 48:e1:e9:42:59:40 │
│ │Password: 0_952716e80f5c54ff4493465156d32aa0 │
├────────────────────┼────────────────────────────────────────────────────────────────────────┤
│MQTT topics │Publishes to: /appliance/2012174007893251804648e1e9425940/publish │
│ │Subscribes to: /appliance/2012174007893251804648e1e9425940/subscribe │
└────────────────────┴────────────────────────────────────────────────────────────────────────┘
`
Form mosquitto when trying to sub the plug (sudo mosquitto_sub -d -t "/#" --cafile /etc/mosquitto/certs/mqtt_server.pem):
Client mosqsub|12810-PlatoPi sending PINGREQ
Client mosqsub|12810-PlatoPi received PINGRESP

This is from the log: (sudo tail -f /var/log/mosquitto/mosquitto.log)
New client connected from 192.168.2.50 as fmware:20040808158569251h3748e1e9197500_uBD0TymGUdnTTzoZ (c1, k30, u'48:e1:e9:19:75:00').
1629319822: Socket error on client mosqsub|12433-PlatoPi, disconnecting.

Thank you for helping =)

**Comment by albertogeniola** [comment]
Hi @platofan23 ,

as far I can see, you are using the meross setup utility from Bytespider. You should then open an issue [here](https://github.com/bytespider/Meross).

**Comment by platofan23** [comment]
Hi @albertogeniola,

sorry for the late answer.
I solved the problem later on by adding the plugs via the meross app and than blocked their internet connection via my router.
Now it works great.
Thanks for the help
