### ISSUE TITLE
HA Energy Dashboard

### ISSUE THREAD

**Issue by eximo84** [albertogeniola/meross-homeassistant#256]
**Is your feature request related to a problem? Please describe.**
Currently the power monitor doesnt appear in the Energy Dashboard - https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Describe the solution you'd like**
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by albertogeniola** [comment]
Duplicate of #254
