### ISSUE TITLE
This API causes issue with... Meross company ;-(

### ISSUE THREAD

**Issue by homonto** [albertogeniola/meross-homeassistant#257]
So today Meross company turned off all my sockets... remotely. They simply made "no more smart" - they contacted me and said that I was "attacked" and that they "had to disconnect" my sockets.
When I told them that it is not true and that I am using my sockets in the smart way they said.... read below please:

> Dear customer,
> 
> Thanks for contacting meross.
> 
> Please let us know your meross account, we will help resume cloud service for devices.
> 
> The reason why you received the reminder is that we found your connection was abnormal, and usually it was caused by that you used other home automation solutions, such as iobroker, Domotics, Home Assistant and request the server connection with high frequency. After you have changed the related settings as required, the connection will be resumed automatically within 24 hours. If you are not sure about that, please factory reset the smart devices and configure them from scratch.
> 
> Please know that only meross app, eHomelife app, Google Home, Amazon Alexa, IFTTT, Homekit (specific products) are officially supported by us, any other IoT solutions or API may get you into such problem again.
> 
> Thanks for your understandings.
> 
> Looking forward to hearing back from you.
> 
> Best regards,
> Miree
> Meross Customer Support

So I am not sure what to do - apparently Meross LAN is pulling the data from Meross Servers and this is not seen nicely by Meross. 
What to do?

thx

**Comment by purcell-lab** [comment]
> So I am not sure what to do - apparently Meross LAN is pulling the data
from Meross Servers and this is not seen nicely by Meross.

Switch to meross-lan, it doesn't appear to have any if these issues.

**Comment by homonto** [comment]
I am using meross-lan
but this integration does not disconnect the sockets from the Meross cloud
unless I am doing something wrong - any help?

**Comment by albertogeniola** [comment]
Hi @homonto , for meross-lan integration you should open an issue [here](https://github.com/krahabb/meross_lan/issues).

**Comment by homonto** [comment]
sorry ;-)
