### ISSUE TITLE
After update at 1.1.2 stop working 

### ISSUE THREAD

**Issue by giugit** [albertogeniola/meross-homeassistant#259]
**Describe the bug**

Meross Cloud IoT Nuovo tentativo di configurazione: None
Home Assistant 2021.8.8

Versione
core-2021.8.8
Ultima versione
core-2021.8.8

Versione
supervisor-2021.06.8
Ultima versione
supervisor-2021.06.8

**Your environment**
HomeAssistant version: -- PLEASE SPECIFY --
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: -- PLEASE SPECIFY --

**Logs taken when the issue happened**
```
--- PASTE LOGS HERE ---
```

**Comment by thunder2k** [comment]
Same here!
