### ISSUE TITLE
Component doesn't load: "cannot import name 'DeviceDoorStatusEvent'"

### ISSUE THREAD

**Issue by C0ntroller** [albertogeniola/meross-homeassistant#26]
Hi,
I tried to use this component comming from [this](/vincenzosuraci/hassio_meross_sensor_switch).

I followed the setup but get a python error:

`Component error: meross_cloud - cannot import name 'DeviceDoorStatusEvent' from 'meross_iot.meross_event' (/usr/local/lib/python3.7/site-packages/meross_iot/meross_event.py)`

Could you look into it why the meross_iot integration is failing? I tried to edit the dependency to version 0.3.1.7 with no luck.

System: Rock64
HassOS 2.12
HAss Version: 0.102.2

**Comment by albertogeniola** [comment]
Hi,

could you please link the library you are using? The link you provided is invalid.

Moreoever, which python version are you running?

**Comment by C0ntroller** [comment]
Hi, 

sorry I forgot an / in the link, it should work now.

I can't really say which python version other than version 3.7 (as seen in the error) because I use HassOS and don't have direct access to the linux below.

**Comment by bigstevehardy** [comment]
I am getting this as well

**Comment by albertogeniola** [comment]
Hi @C0ntroller ,

Would you mind installing this library using HACS? I'm pretty sure a clean installation would work.

**Comment by albertogeniola** [comment]
Last version should fox it. Do you mind test it again?

**Comment by C0ntroller** [comment]
So I tested it and the no-HACS version still didn't work (same error) but the HACS version works just fine!

**Comment by albertogeniola** [comment]
Hi @C0ntroller ,
Thanks for the report. I've updated the non-hacs release. Would you mind testing it? Don't forget to remove the HACS component first.

**Comment by C0ntroller** [comment]
Hi @albertogeniola 
Tested it and it seems to work in general but there a few errors/warnings. I don't know how relevant they are:
`Event is not JSON serializable: <Event platform_discovered[L]: service=load_platform.switch, platform=meross_cloud, discovered=None: Smart Surge Protector (mss425e, HW 1.0.0, FW 1.1.9): Channels: 0 = OFF,1 = ON,2 = ON,3 = ON,4 = ON>`
`Error importing platform config_flow from integration meross_cloud to set up meross_cloud config entry: No module named 'custom_components.meross_cloud.config_flow'`

Also the logging 
`Connected to the Meross cloud.`
Shouldn't be an error but an info imo.

**Comment by albertogeniola** [comment]
Hi C0ntroller,
there's something wrong in your installation. First of all, there is no log "Connected to the Meross cloud" in the latest source code. You are probably installing it wrong or you are using an old revision. 

I'ìve updated the release once again. Do you mind trying again?

**Comment by C0ntroller** [comment]
Well seems to work perfectly fine now. Thanks for the support!
