### ISSUE TITLE
Running meross local addon separately from HA

### ISSUE THREAD

**Issue by a-waider** [albertogeniola/meross-homeassistant#264]
**Is your feature request related to a problem? Please describe.**
I'm not running HA in supervised mode, so the addon store isn't available for my installation. Is there a way to run the addon separately from HA?

**Describe the solution you'd like**
Some documentation on how to run the addon separately from HA.

**Describe alternatives you've considered**
I tryed to build the addon container myself but it failed while installing the apt packages. It could be related to this message: `debconf: delaying package configuration, since apt-utils is not installed` but I'm not that sure.

**Additional context**

**Comment by albertogeniola** [comment]
Hi @a-waider ,
that was expected. For now, I'm focusing on developing a HA version of the ADDON. As soon as it is ready, I believe we'll build a stand-alone version to run it where HA is not supervised. For the time being, this is a feature request.

**Comment by shangli123** [comment]
Thanks for keeping it updated @albertogeniola . Love it very much. It would be the best if you may make the local communication functionality available without the HA Addon. It will benefit many users like me with no supervised HA or HAOS.
