### ISSUE TITLE
Meross security notice - [meross_iot.manager] An error occurred while executing push notification handling for <meross_iot.model.push.online.OnlinePushNotification object at 0x7f88ff2190

### ISSUE THREAD

**Issue by silviudc** [albertogeniola/meross-homeassistant#265]
Not sure what we can do about this but since updating to the latest version I have received this email from Meross, saying the API was polled hundreds of thousand of times:

> This is meross cloud security team contacting you. 
> 
> First of all, thanks for choosing meross products and we hope that you enjoy smart life with our smart products. 
> 
> Recently our cloud security system has noticed that your devices are communicating with the could server at an extremely high frequency. We consider these behaviours abnormal and are concerned about the security of your devices. We believe your devices have been hacked and manipulated since they triggered our safety guard hundreds of thousand times during this week.
> 
> Due to the security concerns and the intent to avoid any further potential damage, we will terminate the cloud services of these devices if the abnormal behaviours do not stop. To help you, we suggest you to stop use any third-party platforms other than Alexa, Google Assistant, HomeKit, SmartThings and IFTTT. If you do use third-party platforms such as Home Assistant, we suggest you to downgrade to 1.0.7 immediately.
> 
> If you find your cloud service terminated by meross cloud safety guard  and you are sure that your devices are safe, NOT hacked, and are performing as expected. Please first lower your periodic request rate to no more than one message every ten seconds and then send an email to support@meross.com. We will resume cloud service for you within 24 hours. 
> 
> For the safety of your devices and personal data, we suggest you to use meross app to manage your devices and DO NOT use any other third-party platforms. Meross can NOT guarantee you these unauthorized platforms do not contain any malware and ransomware codes, nor can we ensure the security of your personal data collected by these platforms. Please note that any abnormal high cloud request frequency will cause cloud service termination again. 
> 
> Should you have any information you would like to provide us with or you would like to offer us any clarification, please contact us within 24 hours. 
> 
> Thanks! 
> 
> Meross Cloud Security Team

Anyone got this? Never received this before updating to latest version so maybe related?
Downgrading to HA 1.0.7. is of course a no go, can we get local control added maybe?

**Comment by silviudc** [comment]
I am seeing thousands of these error sin my logs so I think this must be it: 
```
2021-09-02 06:56:34 ERROR (MainThread) [meross_iot.manager] An error occurred while executing push notification handling for <meross_iot.model.push.online.OnlinePushNotification object at 0x7f88ff2190>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('34.253.63.97', 443)
```

**Comment by novisys** [comment]
Hi
I received the same mail today

**Comment by silviudc** [comment]
I have deleted the Meross integration and re-added it back and I haven't seen that error come back so far.
Possible something went wrong when the integration was updated via HACS.
Try that and see.
Will monitor my logs for the day and close this out if re-adding the integration is the fix.

**Comment by undy27** [comment]
I have also received that e-mail from Meross. Clearly states that "If you do use third-party platforms such as Home Assistant, we suggest you to **downgrade to 1.0.7 immediately**." So it looks like the latest updates made things even worse. In any case, it's been a couple of days since I went back to 1.0.7 and yet I still received that email today

**Comment by silviudc** [comment]
Downgraded to 1.0.7 as the log is filled with these errors:
```
2021-09-03 13:23:53 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/63513-a875b30d4b8c8d85f5a43752ea3bf79a/subscribe", "messageId": "496953a9f2c0aaaec084982215908e97", "method": "GET", "namespace": "Appliance.Control.Electricity", "payloadVersion": 1, "sign": "1142bb73501085a564d2b9ed17b0a10e", "timestamp": 1630671823}, "payload": {"channel": 0}}' sent to device uuid 19010849682057251a1334298f1469fc. Timeout was: 10.0 seconds. Mqtt Host: mqtt-eu.meross.com:443.Global manager stats (last minute): Issued -> 9, Delayed -> 0, Dropped -> 0
2021-09-03 13:23:53 ERROR (MainThread) [custom_components.meross_cloud.sensor] Error occurred.
```

**Comment by flouwers** [comment]
Even with latest plugin version (1.1.4), having asked Meross support to unlock my account, and implemented rate limiting, it still fails regularly with the following message : 
`2021-09-24 11:51:02 ERROR (MainThread) [custom_components.meross_cloud.config_flow] Unable to connect to Meross HTTP api, ex: Server disconnected` 
After that, it is impossible to reconnect before 1-2 days.
Even the official app has some connectivity issues. This makes me think they are banning the originating IP address.
