### ISSUE TITLE
Expected data source not listed

### ISSUE THREAD

**Issue by H3ALY** [albertogeniola/meross-homeassistant#266]
**Is your feature request related to a problem? Please describe.**
MSS310 is not available as a source in the Energy functionality to define it as a source for tracking the energy usage of individual devices.

**Describe the solution you'd like**
Require that the entity is correctly configured so HA knows that it needs to track statistics for the device and how.

**Describe alternatives you've considered**
N/A

**Additional context**

https://www.home-assistant.io/more-info/statistics/

**Comment by cooperaj** [comment]
Specifically the power needs exposing as a KWh sensor using the **total_increasing** state class (as opposed to **measurement**). This would probably be an additional sensor to the current instantaneous ones.

**Comment by jkp** [comment]
This is still an issue - would be awesome if it could be solved! Also came to the conclusion that need support for KWh in total_increasing terms. Is this tricky to do?

**Comment by ineffyble** [comment]
I'd love it if this was implemented.

**Comment by ineffyble** [comment]
@albertogeniola Are you able to reopen this issue please?

**Comment by phnguy** [comment]
Issue still here how can i help?
