### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by a-waider** [albertogeniola/meross-homeassistant#270]
**Describe the bug**
I can't notice any functional errors but found some errors in the log.

**Your environment**
HomeAssistant version: 2021.9.3
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: Docker on an Intel NUC

**Logs taken when the issue happened**
```
2021-09-07 15:05:49 ERROR (MainThread) [meross_iot.manager] An unhandled exception occurred while handling push notification
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 724, in _async_dispatch_push_notification
await dev.async_handle_push_notification(
File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/known/subdevice.py", line 53, in async_handle_push_notification
for sample in samples:
TypeError: 'NoneType' object is not iterable
```
I left out some warnings that are common due to being an inofficial integration.

**Comment by PachangaDad** [comment]
I'm having same error message but attributing it to temp/humidity sensors I have using the Meross hub. As I'm a NOOB at this kind of lost how to dig and resolve. Any direction would be appreciated.

**Comment by albertogeniola** [comment]
Hi @a-waider : can you please post the Meross Component startup log? I need to see which HA version are you using to discriminate why this happens.

**Comment by a-waider** [comment]
I wrote the HA version on my initial comment. 
Additionally I can offer this Log snippet:
```
=============================== Meross Cloud Custom component Developed by Alberto Geniola Low level library version: 0.4.2.2 -------------------------------
```

**Comment by albertogeniola** [comment]
Hi guys,
I was able to replicate the problem. This occurs when multiple sensors/valves are connected to a single user account. 
I need to fix the underlying MerossIot library to make it work as expected.

Thanks for reporting this one. I'll update this thread as soon as it gets fixed.

**Comment by albertogeniola** [comment]
Solved with latest release! Can you please update and report back if that happens again?

Thanks!

**Comment by a-waider** [comment]
Seems fine by me. Thanks!
