### ISSUE TITLE
Problema conectividad servidores Meross

### ISSUE THREAD

**Issue by jmatiasGH** [albertogeniola/meross-homeassistant#276]
Tengo entendido que los servidores de Meross están sufriendo caídas por exceso de conexiones en sus servidores. Y al parecer deben tener algún tipo de bloqueo.
Tengo 20 dispositivos y al reconfigurarlo me detecta todo, pero al cabo de unas 7 horas dejan de funcionar de nuevo. A veces hay que esperar x horas hasta que te vuelve a dejar configurar o de repente vuelve a funcionar pero enseguida vuelve a petar.
He probado a actualizar a la última versión de HA y del plugin como se indica en la nota pero sigue fallando.
He descubierto que cuando falla la conexión a iot.meross.com si cambias el host por us-iot.meross.com funciona pero sucede lo mismo al cabo de unas horas falla. Cada host balancea entre 2 IPs pero no se pueden configurar directamente, usan virtualhost o similar.
He intentado activar el limitador de consultas MQTT del plugin y deshabilitar los dispositivos desde HA para dejar menos de la mitad pero sigue fallando.
¿Hay forma correcta de configurar el limitador para que no caiga cada pocas horas?

HomeAssistant version: core-2021.9.7
Hardware environment: x86_64

**Comment by LaskaBozzolo** [comment]
Same problem here. Meross support answered me this: "Did you use the third party integration such as Home Assistant? if so please reduce the server request rate to NO more than one message every 10 seconds, then your connection should be resumed automatically after 24 hours.
Please also make sure your integration is up to date."

**Comment by toot** [comment]
I'm having similar poblems and I'm not sure, if my settings are correct:

![Screenshot 2021-09-30 11 59 52](https://user-images.githubusercontent.com/60329392/135433041-722edec8-5f77-4410-bd7d-585de8fbb90f.png)

The error message: 
![Screenshot 2021-09-30 11 43 35](https://user-images.githubusercontent.com/60329392/135434023-35cdedc2-d5b7-4bcd-8c53-14907be549b2.png)

How can I change the host without total reconfiguration?

**Comment by jmatiasGH** [comment]
Dear Customer,

This is meross cloud security team contacting you.
First of all, thanks for choosing meross products and we hope that you enjoy smart life with our smart products.

Recently our cloud security system has noticed that your devices are communicating with the could server at an extremely high frequency. We consider these behaviours abnormal and are concerned about the security of your devices. We believe your devices have been hacked and manipulated since they triggered our safety guard hundreds of thousand times
during this week.

Due to the security concerns and the intent to avoid any further potential damage, we will terminate the cloud services of these devices if the abnormal behaviours do not stop. To help you, we suggest you to stop use any third-party platforms other than Alexa, Google Assistant, HomeKit, SmartThings and IFTTT. If you do use third-party platforms such as Home Assistant, we suggest you to downgrade to 1.0.7 immediately.

If you find your cloud service terminated by meross cloud safety guard and you are sure that your devices are safe, NOT hacked, and are performing as expected. Please first lower your periodic request rate to no more than one message every ten seconds and then send an email to support@meross.com. We will resume cloud service for you within 24 hours.

For the safety of your devices and personal data, we suggest you to use meross app to manage your devices and DO NOT use any other third-party platforms. Meross can NOT guarantee you these unauthorized platforms do not contain any malware and ransomware codes, nor can we ensure the security of your personal data collected by these platforms. Please note that any abnormal high cloud request frequency will cause cloud service termination again.

Should you have any information you would like to provide us with or you would like to offer us any clarification, please contact us within 24 hours.

Thanks!


Meross Cloud Security Team

**Comment by phantomdez** [comment]
I too have this issue.  Not sure how to properly configure the requiremnet they are asking about as most are settings above their limit.  Any assistance would be appreciated.

**Comment by jmatiasGH** [comment]
He intentado limitar la API a 1call/seg en general y la de dispositivo. Reinicio y falla al momento. Si pongo los parámetros por defecto del limitador vuelve a funcionar.
El problema es que no se puede limitar al limite que nos pide Meross < 0,1call/seg. (< 1 call/10seg) y nos acaban bloqueando.
He conseguido reducir las llamadas de la API a menos de 0,1call/seg desactivando todas las entidades que me dan los valores de consumo en watios, los amperios y el voltage.
A ver si así dejan de bloquearme desde Meross y dejamos de crearles problemas en sus servidores.

![Screenshot_20211002_222922_io homeassistant companion android](https://user-images.githubusercontent.com/91526624/135731328-563252c8-85b1-4ca0-8d74-e6a599f4ca40.jpg)

**Comment by toot** [comment]
I also tried to disable all unnecessary entities (voltage, current...) - with success!
No more unavailable devices for a couple of days now.
