### ISSUE TITLE
mss310 add to Energy Individual Device

### ISSUE THREAD

**Issue by joelang1699** [albertogeniola/meross-homeassistant#277]
I've got a few of these mss310 units link into HA which correctly display the W,A,O readouts. I'd like to add these to the energy panel however when I select "Add a Device" in the energy panel, none are displayed. I am missing something here?
![Screenshot 2021-10-05 013229](https://user-images.githubusercontent.com/13611738/135942283-6841f573-2f7f-42ac-bdce-9175653eba56.jpg)
![Screenshot 2021-10-05 013323](https://user-images.githubusercontent.com/13611738/135942316-644f7135-ec0c-4284-b0b4-e6762b1f1da0.jpg)

**Comment by jkpe** [comment]
Add this sensor to create a new entity that records energy used which can be used in the Energy Dashboard.

```
- platform: integration
  source: sensor.meross_energy_plug_1_mss310_power_sensor_w_0
  name: meross_energy_plug_1_energy_spent
  unit_prefix: k
  round: 2
```

ref: https://www.home-assistant.io/integrations/integration/

**Comment by joelang1699** [comment]
> 
> 
> Add a sensor like this to create a new entity that records energy used which can be used in the Energy Dashboard.
> 
> ```
> - platform: integration
>   source: sensor.meross_energy_plug_1_mss310_power_sensor_w_0
>   name: meross_energy_plug_1_energy_spent
>   unit_prefix: k
>   round: 2
> ```
> 
> ref: https://www.home-assistant.io/integrations/integration/

Ah I see, Will this need to be done for each plug?

**Comment by nchieffo** [comment]
Does this mean the meross integration will never support this and we have to configure it manually?

**Comment by johnbozuk** [comment]
> Add a sensor like this to create a new entity that records energy used which can be used in the Energy Dashboard.
> 
> ```
> - platform: integration
>   source: sensor.meross_energy_plug_1_mss310_power_sensor_w_0
>   name: meross_energy_plug_1_energy_spent
>   unit_prefix: k
>   round: 2
> ```
> 
> ref: https://www.home-assistant.io/integrations/integration/

What file would I add this too as I have the same issue, cannot add sensors to energy dashboard, thanks in advance
