### ISSUE TITLE
Problema su prese MSS210

### ISSUE THREAD

**Issue by pescatore70** [albertogeniola/meross-homeassistant#279]
Da qualche giorno solo queste due prese MSS210 non funzionano (non sono disponibili) mentre tutte le altre MSS310 funzionano perfettamente.

**Comment by albertogeniola** [comment]
Hi,

please write your questions in English, so that also other people can take advantage from your experience :)

Anyways, this also occurred to me. I'm currently working on that. Latest RC version (v1.2.0rc1-dev) should solve the issue. Do you mind testing it and see if it's ok now?
