### ISSUE TITLE
merros humidifier not working

### ISSUE THREAD

**Issue by Medy111** [albertogeniola/meross-homeassistant#28]
from logs
Event is not JSON serializable: <Event platform_discovered[L]: service=load_platform.switch, platform=meross_cloud, discovered=None: Luftbefeuchter (msxh0, HW 3.0.0, FW 3.1.2): 

Unknown/Unsupported namespace/command: Appliance.Control.Light

Unknown/Unsupported namespace/command: Appliance.Control.Spray

**Comment by albertogeniola** [comment]
Hi @Medy111 ! 
Unfortunately your device is not currently supported by the underlying meross-iot library. It will probably be supported in the future, so stay tuned.

**Comment by Tscherno** [comment]
That device would be great, because it also could show different LED colours as status :|

**Comment by aluisperezh** [comment]
I got my Smart Humidifier today and this appears in my log:

`INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.meross_cloud entity: switch.humidificador`

It seems it is supported by Meross cloud in some way now...

**Comment by steffenu** [comment]
well im using iobroker + merross adapter for a while now...
Thats iobroker is winner ;)

**Comment by albertogeniola** [comment]
Hi all, just to inform you that I've just received a brand new Smart Humidifier, so it's just a matter of time before it gets supported... As it always happen, I first need to add support on the [low-level library](https://github.com/albertogeniola/MerossIot), then I need to implement HA plugin integration. It takes time, but it will be supported eventually. Stay tuned!

**Comment by albertogeniola** [comment]
Hi guys,
I've just released version 20200308.2 which now adds support for the Meross smart humidifier. At the moment, I've just added support for SPRAY operations. Future releases will include light control. 
In the meantime, would you please test the current version and let me know?

**Comment by aluisperezh** [comment]
Ciao, Alberto. It's working fine on my side.

Thank you very much for your work!!!

**Comment by pierpa68** [comment]
Hi,
In my case even with version 20200308.3 I'm unable to find my smart humidifier. Should it be detected automatically or have I to do something in order to find it in HA?

Many thanks for your work anyway

**Comment by albertogeniola** [comment]
Have you tried to remove/re-add the meross integration? Discovery has not been coded yet.

**Comment by pierpa68** [comment]
I've tried multiple times but no success.
My other device (smart plug) is re-added correctly every time I reinstall the Meross integration.
Can I do anything else?

Thanks

**Comment by Ma194** [comment]
> I've tried multiple times but no success.
> My other device (smart plug) is re-added correctly every time I reinstall the Meross integration.
> Can I do anything else?
> 
> Thanks

Same for me!
I had the integration installed for some time now - when I added the humidifier, it showed up, but it couldn't be used. 
Now, because of your comment, I deleted the integration and installed the newest version. However, the humidifier doesn't even show up now
