### ISSUE TITLE
Meross IoT Login fails with “Aborted” message

### ISSUE THREAD

**Issue by mattyf** [albertogeniola/meross-homeassistant#281]
The Meross integration (v1.1.4) is showing a warning in HA: "Failed to set up: Invalid token or credentials," but whenever I attempt to update the login info (which is blank currently), I get a popup window that just says “Aborted.” The Meross app on my phone works fine, and the login credentials work there. I tried reinstalling the integration, but that didn’t help. I also can’t seem to find any entries in the logs relating to any Meross problems, or why the attempt was “aborted.”

What I haven’t tried yet is completely deleting the integration and reinstalling it fresh. I’m relatively new, so I don’t know how to make sure the entities stay in place if I uninstall/reinstall. Or how uninstalling with affect the flows I’ve built with those entities in Node Red. I’m not sure this is even the right category to post this in! :confused:

Any help appreciated!

**Comment by thunder2k** [comment]
Hi,
I had the same issue. I deleted the integration, uninstalled and reinstalled from HACS and it solved my issue. Do a HA restart between each step. All the automations/dashboards I have with the Meross devices are working fine without any rework after reinstalling. I'm not sure about Node Red as I don't use it.
Good luck!
