### ISSUE TITLE
Integration Meross Cloud IoT does not appear (Issue #236)

### ISSUE THREAD

**Issue by 0lmagalhaes0** [albertogeniola/meross-homeassistant#283]
It is the same problem of the issue #236  - After the repository installation in HACS and system restart, there are still no Integration called Meross to be installed.

HomeAssistant version: core-2021.11.1
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: RPi 4

The previous Issue solution is to add the verion in the manifest. In my case, it was already there (see manifest below):

> {
>   "domain": "meross_cloud",
>   "name": "Meross Cloud IoT",
>   "documentation": "https://www.home-assistant.io/components/meross_cloud",
>   "issue_tracker": "https://github.com/albertogeniola/meross-homeassistant",
>   "dependencies": ["persistent_notification"],
>   "codeowners": ["@albertogeniola"],
>   "requirements": ["meross-iot==0.4.2.2"],
>   "config_flow": true,
>   "quality_scale": "platinum",
>   "iot_class": "cloud_push",
>   "version": "1.1.4",
>   "zeroconf": ["_meross-api._tcp.local."]
> }

I have already reinstalled the repository in HACS, restarted the system multiple times and cleared the browser cache...
Any other suggestions?

**Comment by faultylogic** [comment]
Took me a bit to figure it out but I found the missing button its already in the repo so it won't let you add the github but you had add the integration through a button on the bottom right.  I've added all the screenshots so hopefully that helps you.  



![Screen Shot 2021-11-07 at 10 29 51 PM](https://user-images.githubusercontent.com/5971643/140679975-834a1c9b-c786-446e-b4b2-4402d849baf5.png)
![Screen Shot 2021-11-07 at 10 30 20 PM](https://user-images.githubusercontent.com/5971643/140680068-d31c9645-4d62-426a-8294-ad5341ea2778.png)
![Screen Shot 2021-11-07 at 10 30 29 PM](https://user-images.githubusercontent.com/5971643/140680081-8274f8ef-f50f-4e93-af8f-bb512ef078f0.png)

![Screen Shot 2021-11-07 at 10 30 38 PM](https://user-images.githubusercontent.com/5971643/140680085-4f982c7f-5350-4d3b-a261-5736aa96acb8.png)

**Comment by 0lmagalhaes0** [comment]
Thank you, but it was already installed in HACS, the problem was that the integration was not showing up afterwards. 

But after 4 days, clearing ache, logging out and logging in again, it worked. :)

**Comment by g0per** [comment]
I had to reboot the VM I have Home Assistant running on, from the hypervisor menu itself rather than the Configuration/Server Controls menu, to make it appear there.
