### ISSUE TITLE
i cannot add multiple accounts

### ISSUE THREAD

**Issue by KnifeOfDunwall** [albertogeniola/meross-homeassistant#289]
I dont know if this is a bug or not implemented and if it is not implemented it would also be a feature request.
i wanted to add a second component with another account and it just said cancelled or something similar(was not english so cannot give exact words). it would be really cool to have the abillity to manage multiple accounts. in my house for example every part of my family has its own account so they would not mess with each others devices but it would be really useful to have them all managed by home assistant anyways. for example when leaving to turn all loghts off. there was nothing in the log about this issue specifically

**Comment by Flowwwww** [comment]
Same problem here :(
