### ISSUE TITLE
mss425e with newer firmware not yet supported?

### ISSUE THREAD

**Issue by AdmiralRaccoon** [albertogeniola/meross-homeassistant#29]
Hi there,
I have several mss425e power bars working well with HA and this plugin. Yesterday, I bought a new one, and for this one, I get only one switch for the entire bar called "switch.smart_surge_protector" (not 5 switches for each channel).

the difference to my other mss425e is that the new one has Firmware 3.1.2 and Hardware Version 3.0.0 (All my other mss425e have Firmware 2.1.3 and Hardware 2.0.0.)

Could this be the problem? Are there any logs to examine?

Thanks,
Philipp

**Comment by albertogeniola** [comment]
Hi @AdmiralRaccoon ,

would you mind open an issue about this on the [meross-iot library](https://github.com/albertogeniola/merossiot)?

**Comment by albertogeniola** [comment]
Hi @AdmiralRaccoon ,
Would you mind testing the latest version of the integration and let me know if the problem still persists?

**Comment by AdmiralRaccoon** [comment]
yes, thank you, it works! 
Now i can see each single socket as an entity.

**Comment by albertogeniola** [comment]
Awesome! 
Thanks for reporting the error.

Closing the issue then.
