### ISSUE TITLE
Meross Retrying Setup: None

### ISSUE THREAD

**Issue by disco1111** [albertogeniola/meross-homeassistant#290]
Not sure whats happened here? 

In integrations it says 'Retrying Setup: None'

I have 5 Meross Smart Plugs- 1 just used as a switch, 3 used for power measurement, and 1 for power and voltage 
All works fine generally apart from when they drop off the network for no reason lol 

Logs below..

I had the API Rate limit off.. Is this the cause? I have activated it now - will it just re-start once their servers let me in again?  

`This error originated from a custom integration.

Logger: custom_components.meross_cloud
Source: custom_components/meross_cloud/__init__.py:113
Integration: Meross Cloud IoT
First occurred: 13:26:13 (12 occurrences)
Last logged: 13:37:44

Error occurred. ------------------------------------- Component version: 0.4.2.2 Device info: <Unavailable> Error Message: "An exception occurred while setting up the meross manager. Setup will be retried..."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/__init__.py", line 206, in async_setup_entry
    client, http_devices, creds_renewed = await get_or_renew_creds(
  File "/config/custom_components/meross_cloud/__init__.py", line 113, in get_or_renew_creds
    http_devices = await http_client.async_list_devices()
  File "/usr/local/lib/python3.9/site-packages/meross_iot/http_api.py", line 318, in async_list_devices
    result = await MerossHttpClient._async_authenticated_post(url, {}, cloud_creds=self._cloud_creds, http_proxy=self._http_proxy)
  File "/usr/local/lib/python3.9/site-packages/meross_iot/http_api.py", line 226, in _async_authenticated_post
    async with session.post(url, data=payload, headers=headers, proxy=http_proxy) as response:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
`

And 
`Logger: homeassistant.config_entries
Source: config_entries.py:335
First occurred: 13:26:13 (1 occurrences)
Last logged: 13:26:13

Config entry 'https://iot.meross.com' for meross_cloud integration not ready yet: None; Retrying in background`

![meross](https://user-images.githubusercontent.com/95193909/144433031-c2800412-3921-4220-bff0-60422b36d0e2.JPG)

**Comment by FirefoxNL** [comment]
I'm having the same issue. Since around 11:58 am UTC this message showed up.
I also had the API rate limit turned off but it had been running without issue for months prior to today.

Tried reïnstalling the integration but then it gives me the following undescriptive error:
![image](https://user-images.githubusercontent.com/74513001/144483731-6fb5ba95-6b80-493a-a8b9-c3e64aef42f9.png)

**Comment by disco1111** [comment]
> I'm having the same issue. Since around 11:58 am UTC this message showed up. I also had the API rate limit turned off but it had been running without issue for months prior to today.
> 
> Tried reïnstalling the integration but then it gives me the following undescriptive error: ![image](https://user-images.githubusercontent.com/74513001/144483731-6fb5ba95-6b80-493a-a8b9-c3e64aef42f9.png)
> 
> I'm still able to control the devices through the Meross app itself.

Exactly the same here..

**Comment by disco1111** [comment]
mine started working at exactly 11.57.43am gmt ? no idea what caused it but working now

**Comment by FirefoxNL** [comment]
Strange! Mine also works again since about the same time.

**Comment by albertogeniola** [comment]
Hi guys, 
That was probably an error with Meross cloud itself.
