### ISSUE TITLE
MSG100 does not appear in Entity Registry

### ISSUE THREAD

**Issue by coolguymatt** [albertogeniola/meross-homeassistant#3]
I have two devices, an MSG100 (garage door opener) and MSL120 (light bulb). The MSL120 appears in the Entity Registry but the MSG100 does not. Functionality isn't affected but figured I would mention it.

**Comment by albertogeniola** [comment]
Hi, could you be more precise? What do you mean by saying that the MSG100 does not appear in the Entity Registry? Can you provide a screenshot?

**Comment by coolguymatt** [comment]
Configuration > Entity Registry

Here is the light bulb:
![image](https://user-images.githubusercontent.com/35379891/59965015-ca552280-94d6-11e9-81e4-246d18a11fef.png)

But the garage door opener doesn't appear. Reading the dev documentation, it seems that only entities that have a unique ID assigned to them will appear.

**Comment by albertogeniola** [comment]
Well, I'm not sure this is a bug. I think COVER devices are treated differently than others in HA. Was it supposed to appear there?

**Comment by coolguymatt** [comment]
I checked on the Discord channel, and they said that Cover entities aren't handled differently - if they have a unique ID, they should appear in the Entity Registry. It isn't a huge deal - I went through the list and several other things do not appear (example: Lutron Caseta light switches). I just wanted to change the name and didn't feel like editing the customize.yaml file.

**Comment by albertogeniola** [comment]
Hi @coolguymatt ,
thank you for asking in the discord channel. That is valuable piece of information. This probably means I'm failing in assigning the unique ID. I'll try to check that and report back to you!

**Comment by albertogeniola** [comment]
Hi @coolguymatt ,
your comment was so specific and right that I was able to fix the issue in just couple of minutes. Please update the component (maybe using HACS?) and let me know if that works now.

**Comment by coolguymatt** [comment]
Fixed! Thanks so much.
