### ISSUE TITLE
Sensor refresh time

### ISSUE THREAD

**Issue by GrayFarkas** [albertogeniola/meross-homeassistant#307]
Hello Alberto!

First of all, thank you about your work with this great repo.

Yesterday I moved my heating system control from Meross IoT python script to HA automation with your integration.

I can't install the HACS so as you described I manualy copyed the custom components.

The integrations is work fine for the first look.

I'm not sure this is a bug, maybe just a usage question:

My temperature and humidity sensors not updating the values too often. My opinion is to update the sensor values perhaps every 5 or 15 minutes. Is it possible to do this?

**Your environment**
HomeAssistant version: -- Home Assistant 2021.12.7 I install to Ubuntu Server 20.04 LTS with snap
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: -- MSH300 FW:4.1.35 HW:4.0.0

**Comment by albertogeniola** [comment]
Hi @GrayFarkas ,

the update timings are somehow limited by the Meross Cloud and: by pushing the limit too hard your account might get banned by the Meross Cloud. However the latest version 1.2.0RC0 introduced some improvements on sensor updates. You should give it a try!
