### ISSUE TITLE
Add support for Msl320cl

### ISSUE THREAD

**Issue by cima37** [albertogeniola/meross-homeassistant#308]
Hallo, i can not konfig a Msl320cl in home Assistant is ther a chance to make this?

**Comment by albertogeniola** [comment]
Hi @cima37 ,
can you provide more info about your problem? What is exactly the issue you encountered?

**Comment by cima37** [comment]
Problem I wouldn't say so, I can only turn on and off and adjust the brightness nothing else. But I'm not sure if it's just a configuration problem or not

**Comment by albertogeniola** [comment]
Well,
The led strip has not been tested and, for sure, there are some functionalities to be implemented at low level library. To do so, I need to get my hands on the strip, reverse engineer it, and then implement the necessary logic on the component.

**Comment by cima37** [comment]
Thank you!!!
