### ISSUE TITLE
Meross MTS200 floor heating thermostat

### ISSUE THREAD

**Issue by Cully81** [albertogeniola/meross-homeassistant#309]
Hello,

I recently got a MTS200 floor heating thermostat. I have already successfully connected my integration to the cloud and can also control our garagedoor. But unfortunately I do not see the thermostat as a device yet. I guess this is so new on the market that it is not yet integrated? Or am I still doing something wrong?
Are you planning to integrate that soon?

Thanks a lot

**Comment by albertogeniola** [comment]
Hi @Cully81 ,
unfortunately such device is not yet supported by this integration. We need to get our hands on that to add the required functional support.

**Comment by albertogeniola** [comment]
In the meantime, you could provide some data logs via "[Meross Sniffer](https://albertogeniola.github.io/MerossIot/advanced-topics.html#sniff-device-data)": feel free to open an issue [here](https://github.com/albertogeniola/MerossIot/issues) and provide the collected data to help me add the necessary logic to this support this piece of hardware.

**Comment by Cully81** [comment]
Hi @albertogeniola 

unfortunately i can't start the meross sniffer. But that is probably more to me than to the tool.
But maybe this will help you too.

https://www.dropbox.com/s/72mifd0sivihrjo/mts200-1642425928.csv?dl=0

**Comment by cagnulein** [comment]
guys any news on this? I would like to buy one

**Comment by albertogeniola** [comment]
Hi,
The last versions support the mts200. Of course I cannot guarantee it'll work 100% as Meross might have changed the firmware of newest hardware revisions. In any case, the MTS200 I've got is working :)

**Comment by cagnulein** [comment]
Grazie @albertogeniola :) I will buy one on amazon and I will check it.

**Comment by Maje2025** [comment]
Good afternoon, I have the meross mts200b and today in the meross application you can select the summer mode for the refreshing underfloor heating but it does not appear in the HA integration, is there any idea of ​​integrating that option or is it that I have not been able to find it ?

**Comment by cagnulein** [comment]
@ChakraFusion yes it's working flawlessy after the meross firmware update! thanks again @albertogeniolafor your amazing work, truly appreciated!

**Comment by ChakraFusion** [comment]
Wow, thank you very much for your lightning fast response. I am ordering two Mts200 right now.
Thanks again 🙏
