### ISSUE TITLE
Hassio integration?

### ISSUE THREAD

**Issue by pfaffenrodt** [albertogeniola/meross-homeassistant#31]
I have Homeassistant based on latest hassio image.

The issue is, that in hassio addons live in own docker service.
And the host has not even python installed.

Basically what I need is an addon for hassio. I found this example.
https://github.com/hassio-addons/addon-example

I could also try to create one. but I dont realy know the details of internals of hassio nor from home assistant. But I could help on the docker side, if you are interested in creating one.

**Comment by albertogeniola** [comment]
Hi @pfaffenrodt ,
this is not an add-on and has nothing to do with that. You need to install this custom component within the docker image that runs homeassistant itself (which is entirely based on python).

I suggest you to rely on HACS (another custom component) that can take care of installing many other components (as meross): https://community.home-assistant.io/t/custom-component-hacs

**Comment by pfaffenrodt** [comment]
Hi @albertogeniola ,
you are right, the component will be executed in hassio docker image. 

On Hassio you add components inside */config/custom_components/*meross_cloud

The component was registered and was tried to be executed, but it missing your meross python package. 
```
Error loading custom_components.meross_cloud. Make sure all dependencies are installed
```

I did some research and it looks like, that hassio (also home-assistant) uses the manifest.json to install required python packages.  
See Docs:  
https://developers.home-assistant.io/docs/en/creating_integration_manifest.html
Example:  
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/hue/manifest.json


So I guess, an manifest.json will be enough. I will try it later and give you an pull request.

**Comment by pfaffenrodt** [comment]
Oh sry. There is already an manifest.json file. blame on me. I should go to bed.

But why is not working then. I guess there is also an requirement that is missing in the json file?

**Comment by pfaffenrodt** [comment]
@albertogeniola 

I dont know why. But it works now. "Connected to the Meross cloud." it says in my logs.

I had to reboot the whole system.

Sorry to waste your time.

Happy Holidays
