### ISSUE TITLE
Meross not found in HACS

### ISSUE THREAD

**Issue by bridavis** [albertogeniola/meross-homeassistant#312]
**Describe the bug**
I'm not able to find your Meross plug-in in the default repository.

**Your environment**
HomeAssistant version: core-2021.12.8
Hassio Version (if applicable): Home Assistant OS 7.1, supervisor-2021.12.2
Hardware environment: rpi4-64

**Logs taken when the issue happened**
https://imgur.com/VKnmSOO

**Comment by albertogeniola** [comment]
Hi, 

you should first install it via HACS or manually. Once it has been installed locally, you need to reboot HASSIO and then add it as you were trying to do.

**Comment by bridavis** [comment]
Yes, I figured that out and mean to close this issue, thank you for your work!
