### ISSUE TITLE
Unable to connect to Meross HTTP api: Invalid username/Password combination

### ISSUE THREAD

**Issue by kavibhuva** [albertogeniola/meross-homeassistant#314]
**Describe the bug**
Unable to connect to Meross HTTP api: Invalid username/Password combination

**Your environment**
HomeAssistant version: Home Assistant OS 7.1
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: Local Server - Hyper-V VM HA

**Logs taken when the issue happened**
```
This error originated from a custom integration.

Logger: custom_components.meross_cloud.config_flow
Source: custom_components/meross_cloud/config_flow.py:155
Integration: Meross Cloud IoT
First occurred: 10:34:46 (5 occurrences)
Last logged: 10:43:35

Unable to connect to Meross HTTP api: Invalid username/Password combination
```

I am new to this and I am not sure what wrong I am doing.
I have freshly built a HA server on local network.

I am prompted for the login for meross but when entered it keeps telling me invalid creds when those are the same creds I have used to login to my meross app.

**Comment by albertogeniola** [comment]
Hi,
are you sure you entered correct credentials? Can you please change your password excluding special characters and test again?

**Comment by albenex** [comment]
Hi,
I've same issue after upgrading to 1.20
Up to ver 1.14 everything was fine.
Also note that after upgrading (Via HACS) from 1.14 to 1.20, integration stopped working but I didn't collected error log as it's a quite usual stuff so I deleted integration, flushed cache and installed new one.
![image](https://user-images.githubusercontent.com/2207059/149327556-46a936ed-23c1-47e4-bf8b-e3b31b717d28.png)
I've copy-pasted password to my phone using original Meross password and it works.
I've also tried to put password without dashes, no change.

Then I've also tried downgrading from 1.20 to 1.14 but still invalid password message is displayed.

**Comment by albertogeniola** [comment]
Can you check the logs and see what is the message being written when attempting the integration setup? 
You should get some more detailed info there, which can be useful in this case.

**Comment by albenex** [comment]
> Can you check the logs and see what is the message being written when attempting the integration setup? You should get some more detailed info there, which can be useful in this case.

hi, after trying to reset password i found that a typo was present on originally used email address (no verification code used by Mereoss while signing up) so typing wrong email address worked (instead of gmail.com i wrote gmail.coN) so this definitely wasn't integration fault.

**Comment by albertogeniola** [comment]
Gald to hear that!

**Comment by superpower10** [comment]
I have problems connection. No typo. I even reset my password in the app. Still can't connect:

2022-03-01 16:16:23 ERROR (MainThread) [custom_components.meross_cloud.config_flow] Unable to connect to Meross HTTP api: Invalid username/Password combination

**Comment by saxon-viking** [comment]
Sept 2024 update:

I have spent a long time this year trying to reset or even find where to change my Meross login password in Home Assistant. 

Finally found it today. Ready?

Go into the Meross app on your PHONE and then change the password.  They will send you a verification code, then you can change the password. I then deleted the Meross IoT app from HA, then re-installed using the new password. All ok now.

I have not seen this documented anywhere, so I hope this helps someone else.
:+1:

**Comment by rcesp67** [comment]
> Sept 2024 update:
> 
> I have spent a long time this year trying to reset or even find where to change my Meross login password in Home Assistant.
> 
> Finally found it today. Ready?
> 
> Go into the Meross app on your PHONE and then change the password. They will send you a verification code, then you can change the password. I then deleted the Meross IoT app from HA, then re-installed using the new password. All ok now.
> 
> I have not seen this documented anywhere, so I hope this helps someone else. 👍

This worked.... Thank you
