### ISSUE TITLE
Meross Shutter Switch MRS100 support

### ISSUE THREAD

**Issue by Cully81** [albertogeniola/meross-homeassistant#315]
Hello,

I have read here that there must have been repeated attempts and also numerous problems to integrate the MRS100 in HA. But now I could not find any information about whether the problems are now solved and whether the switches can now be integrated without problems. Can someone tell me something about this?

Many thanks

**Comment by albertogeniola** [comment]
Hi,
The MSR100 has not been officially tested and might not work as expected. It would be nice if you could test it and let us know!

**Comment by Cully81** [comment]
Hello,

I have integrated the MRS100 today in the app, but it was not visible in the integration despite several reloads and restarts.
I have now switched to the LAN version of the integration, so I can now control the shutter.
Thanks anyway for your work!
