### ISSUE TITLE
Last update broke my Meross thermostat integration.

### ISSUE THREAD

**Issue by PrzemekSkw** [albertogeniola/meross-homeassistant#316]
**Describe the bug**
My Meross thermostat entireties are unavailable after last update to ver. 1.2.0.rc0.

**Your environment**
HomeAssistant version: core 12.10.9
Hassio Version (if applicable): -----
Hardware environment: MiniPC Intel x64

**Logs taken when the issue happened**
```
Logger: meross_iot.manager
Source: deps/lib/python3.9/site-packages/meross_iot/manager.py:950
First occurred: 10:02:19 (3 occurrences)
Last logged: 10:02:19

Device Domowy HUB (#BASE:1911086520745426280348e1e9114887) has been already added to the registry.
Device Pokój Emilki (#BASE:1911086520745426280348e1e9114887#SUB:01009A5F) has been already added to the registry.
Device Master Bedroom (#BASE:1911086520745426280348e1e9114887#SUB:0100A738) has been already added to the registry.
```
How to downgrade to older version?
Regards

**Comment by Bazarov42** [comment]
Same here, everything ok in meross app, but it's broken in HA...

**Comment by PrzemekSkw** [comment]
I uninstall and install again and now works.
