### ISSUE TITLE
Diffuser Integration Problem (mod100)

### ISSUE THREAD

**Issue by vincenzocalabrese** [albertogeniola/meross-homeassistant#327]
**Describe the bug**
Hello,
I've added the integration to use, through HA, the Meross diffuser mod100 with firmware 3.1.5, but the device and entity was not created into HA. In the follow log you can see that the integration properly read the device, but nothing appear in integration dashboard.

![image](https://user-images.githubusercontent.com/30824836/151808957-8cfb3402-acdb-4d1b-bdf8-66a0d08c7640.png)

Thanks for your support,
Vincenzo

**Your environment**
HomeAssistant version: 2021.12.10
Hardware environment: VM

**Logs taken when the issue happened**

```
2022-01-31 15:05:05 WARNING (MainThread) [custom_components.meross_cloud] Skip MQTT cert validation option set to: True
2022-01-31 15:05:05 WARNING (MainThread) [custom_components.meross_cloud] 
===============================
Meross Cloud Custom component
Developed by Alberto Geniola
Low level library version: 0.4.4.4
-------------------------------
This custom component is under development and not yet ready for production use.
In case of errors/misbehave, please report it here: 
https://github.com/albertogeniola/meross-homeassistant/issues
If you like this extension and you want to support it, please consider donating.
-------------------------------
List of devices reported by HTTP API:
- Diffusore (mod100) - OnlineStatus.ONLINE
===============================
2022-01-31 15:05:07 WARNING (MainThread) [meross_iot.manager] Device Diffusore (#BASE:2011301637014990835148e1e93d3ef3) has been already added to the registry.
2022-01-31 15:05:07 WARNING (MainThread) [meross_iot.manager] Found a new device Diffusore (mod100, HW 3.0.0, FW 3.1.5, class: mod100:3.0.0:3.1.5) that has become online while we were offline.
```

**Comment by albertogeniola** [comment]
HI, 
that's correct: support for mod100 has not been implemented yet. I'm marking this thread as feature-request.

**Comment by cooper645** [comment]
I'm confused, this is closed but doesn't seem to be included yet. Appreciate all your work on this. My humidifier is literally the only smart thing i have not been able to integrate into home assistant
