### ISSUE TITLE
Support for MOD100

### ISSUE THREAD

**Issue by cooper645** [albertogeniola/meross-homeassistant#330]
**Is your feature request related to a problem? Please describe.**
I have a meross smart oil diffuser, non homekit version. the model number is MOD100. I have reloaded, deleted and reconfigured the Meross IOT cloud integration and it still won't find my diffuser. All other smart switches are found without issue.

**Describe the solution you'd like**
Suport for the MOD100 to be added. I see it is available for HOOBS, but I guess it is yet to be implemented into HA

**Describe alternatives you've considered**
No alternative solution has been considered

**Additional context**
No additional information deemed necessary, but I will of course provide any info that you require that may be of use.

I have tried to get my head around the meross sniffer but having never worked with pyhton, I am lost as to where i should begin with it. Is this something i should run from within HA terminal? as this didn't seem to work.

**Comment by cooper645** [comment]
Just done a restart and the following are appearing in the logs:


```
Logger: meross_iot.manager
Source: /usr/local/lib/python3.9/site-packages/meross_iot/manager.py:517
First occurred: 20:11:15 (4 occurrences)
Last logged: 20:11:15

Found a new device Diffuser (mod100, HW 3.0.0, FW 3.1.5, class: mod100:3.0.0:3.1.5) that has become online while we were offline.
```


```
Logger: meross_iot.model.enums
Source: /usr/local/lib/python3.9/site-packages/meross_iot/model/enums.py:105
First occurred: 20:11:21 (2 occurrences)
Last logged: 20:11:22

Namespace Appliance.Control.Diffuser.Spray is not currently handled/recognized.
Namespace Appliance.Control.Diffuser.Light is not currently handled/recognized.
```

**Comment by AndreaSpampi** [comment]
Ciao, anche io nella stessa situazione

**Comment by cooper645** [comment]
This issue seems to still exist, is there something i'm missing as the logs see the diffuser and the custom component has stuff in there for the humidifier in the fan.py file
