### ISSUE TITLE
Meross Cloud IoT not showing

### ISSUE THREAD

**Issue by micgogo** [albertogeniola/meross-homeassistant#332]
**Describe the bug**
After install Meross Custom Component via HAC, restart Home Assistant, Meross Cloud IoT not showing in Device & Intergration

also tried to add version in manifest.json, still not showing

**Your environment**
HomeAssistant version: -- Home Assistant 2022.2.5 --
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: -- Run in Dock --

**Comment by hermannx5** [comment]
Hi, I have the same problem. Just installed via HACS -> restart -> Add Integration: cannot find Meross

**Comment by hermannx5** [comment]
Hi, I managed to see the integration using a different browser/client. I have seen this kind of behaviour also with other HACS integrations.
