### ISSUE TITLE
Some special characters are not accepted in login phase

### ISSUE THREAD

**Issue by Berejeck** [albertogeniola/meross-homeassistant#337]
Ciao, if any special characters like "$" and "!" are used in the password related to meross account, the authentication of "Meross Cloud IoT" integration fails.

**Your environment**
HomeAssistant version: 2022.2.9
Hardware environment: Raspberry pi4

```
![Schermata 2022-02-20 alle 11 42 36](https://user-images.githubusercontent.com/59388498/154838786-8733b198-d487-4319-af05-1d8f30a240c6.png)
```

Tks and regards,
Mic

**Comment by NicciZar** [comment]
Mine contains a "$" but no "!" and it works fine.
