### ISSUE TITLE
Unable to see Meross Devices from a few weeks ago

### ISSUE THREAD

**Issue by korro1975** [albertogeniola/meross-homeassistant#338]
Hi Sirs,
I have a very simple and stable configuration in HA with different sensors and a couple of Meross Plugs that have been working from months and since a few weeks ago, I can't see now as registered in HA. No changes has been made neither in HA nor raspbian and I was wondering what has happen. I have seen a new code from Alberto has been developed in this fantastic integration for HA and I have tried to load onto HA but an error appear (probably due to some Python version). My question is ... what must I do to have the plugs registered as previously?. Has something be changed in Meross that I have to take into account to adapt HA?,

**Your environment**
HomeAssistant version: 0.114.2

Hardware environment: -- PLEASE SPECIFY --
Estado del sistema
arch	armv7l
dev	false
docker	false
hassio	false
installation_type	Home Assistant Core
os_name	Linux
os_version	5.4.51-v7l+
python_version	3.7.3
timezone	Europe/Madrid
version	0.114.2
virtualenv	true

Thanks in advance.
Regards.

**Comment by markdelfs** [comment]
Same thing with my integration--it says NOT LOADED in home assistant, no matter what I try.

**Comment by Nooka6845** [comment]
Same here. Would like to get my automations back

**Comment by dwl99** [comment]
My garage door opener is no longer showing in the integration
