### ISSUE TITLE
Problem with Smart Bulb msl120b

### ISSUE THREAD

**Issue by barbatrukko** [albertogeniola/meross-homeassistant#342]
**Describe the bug**
Unable to configure color or temp in config modal. In scene i set color temp and power, but when i close modal bulb remain in RGB color

**Your environment**
HomeAssistant version: core-2022.3.5
Hassio Version (if applicable): Home Assistant OS 7.5
Hardware environment: RaspPi3

**Logs taken when the issue happened**
```
--- PASTE LOGS HERE ---
```
msl120b 2.0.0
da Meross
Firmware: 2.1.16

**Comment by stetsonandblack** [comment]
I have the exact same issue!

**Comment by stetsonandblack** [comment]
> 

Did you find a solution?
