### ISSUE TITLE
MTS100 Operation and presset reflected in home assistant

### ISSUE THREAD

**Issue by githubjles** [albertogeniola/meross-homeassistant#35]
Hi Alberto, thanks again for your work!

The climate entities reflects the current temperature what is right, and the target temperature demanded, that it´s also right. 
But it shows the current operation and preset, not the target and demanded, and that issue it´s confusing, because if you want to turn off the device, put it to auto, or heating, seems that it´s not responding (in the UI) until the device receives the order (until 3 minutes), making you tap various times the UI thinking you didnt tapped right.
I think it must reflect the target state demanded, so if you tap to turn off like in the meross app, it instantly shows the off state (independly when the device received the order from the hub).

Thanks again and happy new year!!

**Comment by albertogeniola** [comment]
Hi @githubjles ,

The latest version of the library implements such request. Would you mind testing it and let me know if that works as expected?

**Comment by githubjles** [comment]
Thanks Alberto,
Switching to power-off shows instantly. 
Switching from manual to auto, or auto to manual takes a while to show like before.
Switching from power-off to manual, or power-off to auto shows power-on instantly (and last remembered state), but takes a while to show the demanded operation and presset (seems that the problem is switching from manual to auto instruction that doesnt shows instantly).
Hope this helps.

**Comment by githubjles** [comment]
Hi Alberto, in latest updates doesnt work the feature, ¿have you removed the instant demanded operation?. 

Thanks

**Comment by albertogeniola** [comment]
Actually there was a regression. Latest version (20200222.4) should be ok. Can you confirm it?

**Comment by githubjles** [comment]
Ok, thanks, its now back in 20200223.1 and its working great, sometimes need to tap twice to switch auto to custom or reverse, but its a very small issue.
