### ISSUE TITLE
After update loading blocked - 'meross_cloud' does not have a version key in the manifest file

### ISSUE THREAD

**Issue by rpitera** [albertogeniola/meross-homeassistant#352]
**Describe the bug**
After updating today, integration is blocked from loading on restart.  Was working fine prior to update.  On inspection, it looks like part of the manifest.json is missing.

**Your environment**
Home Assistant Core 2022.5.3
Home Assistant Supervisor 2022.05.0
Home Assistant OS 7.6
HAOS running in VM on Virtualbox - hosted on Win10
Meross Cloud version: 20200412.2, installed via HACS

**Logs taken when the issue happened**
```
2022-05-09 08:23:02 ERROR (SyncWorker_6) [homeassistant.loader] The custom integration 'meross_cloud' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
```
manifest.json in my local custom_components\meross_cloud 

```
{
  "domain": "meross_cloud",
  "name": "Meross Cloud IoT",
  "documentation": "https://www.home-assistant.io/components/meross_cloud",
  "dependencies": ["persistent_notification"],
  "codeowners": ["@albertogeniola"],
  "requirements": ["meross_iot==0.3.3.0"],
  "config_flow": true,
  "meross_cloud_version": "unknown"
}

```

This doesn't match the one in the repo at all, so I tried redownloading the integration in HACS but got the same manifest.json (refreshed dir just to make sure).  While I'm sure I could resolve this by manually installing, I'm holding off on that in case that obfuscates the cause of problem.

**Comment by kwkid** [comment]
Same issue with me as well..

2022-05-09 09:55:46 ERROR (SyncWorker_9) [homeassistant.loader] The custom integration 'meross_cloud' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

**Comment by rpitera** [comment]
I just took a look at the zip file of the release in the 'latest release' listed in the releases section and the manifest.json I showed above is the same as the one in the zip.   What's also kind of weird is that despite the listed release date of Apr 12, 2020, I was only notified of this version by HA updater this morning.

**Comment by rpitera** [comment]
Oddly enough, the manifest.json seems to remain the same.  I *am* getting the notification to update to 20200412.2 though.  And prior to updating this morning, I wasn't getting any error messages and the integration was loading just fine.  Weird.

**Comment by kwkid** [comment]
my setup is the same as @rpitera except i'm running Meross v1.2.1

**Comment by scottjl** [comment]
same issue here, same error. i even tried adding `"version": "1.0.0"` to the manifest.json file and while it did stop the error telling me HA wasn't going to load it, it still doesn't show up in integrations.

**Comment by rpitera** [comment]
For now, I've just restored the \custom_components\meross_cloud\ folder from my nightly backup and restarted and everything is loading again.

**Comment by rpitera** [comment]
So since I went back and restored my backup, I've rebooted several times - had some other updates and today's Supervisor release.  Not once has the meross cloud integration showed up again in updates.  It's almost like the version we downloaded wasn't ready for prime time or something.  And the old version I reinstalled is running perfectly fine.  WTH?

**Comment by albertogeniola** [comment]
Hi,
this is related to #353. @rpitera : as you see from the logs, you are running a very old version of the integration (20200412.2) and that is the cause of your problem. I've updated the release so that the "latest" is 1.2.1. Please update the HA integration version and try again.

According to me there has been something wrong with the latest HA update. It should be fine now. Can you confirm that?

**Comment by scottjl** [comment]
i just downloaded the currently 1.2.1 release and it is working for me again. thank you @albertogeniola

**Comment by rpitera** [comment]
I've restarted a couple of times and while I'm seeing updates on other components come through, there's no update showing for meross.  I mean, I can manually install it from a clone of the repo but shouldn't it be showing up with my other HACS updates?

**Comment by scottjl** [comment]
@rpitera i uninstalled it completely, restarted HA, installed the 'current' 1.2.1 version, restarted HA again, and then it was working for me.

**Comment by rpitera** [comment]
@scottjl - Thanks.  I'll give this a shot tomorrow.  I need a chance to check through and find my credentials.  Will report back.

**Comment by rpitera** [comment]
OK, I could not get this to install or show the latest (1.2.1) version in HACS so I just renamed the folder and archived it then downloaded the repo and extracted the custom_components\meross_cloud folder and put it and place.  After a restart, I'm not getting any more errors, I can verify that the 1.2.1 version is in place and if I go to redownload in HACS I now see the 1.2.1 version as the default option.

But if I do an info on the integration in HACS, this is what I am seeing:
![Clipboard01](https://user-images.githubusercontent.com/19910294/167859659-88d1e44f-929e-45ae-b7ca-f403e6bf1392.png)

The info screen still shows 20200412.2 as the latest version.  @scottjl can you take a look and confirm that you're seeing the correct version in HACS?   Maybe it's just on my end.

**Comment by scottjl** [comment]
@rpitera yes. mine says v1.2.1 correctly. i would recommend removing it completely through HACS. shut down HA, then make sure the directory is actually gone out of your custom_components directory. restart and there should be no trace of it remaining. HACS should say v1.2.1 is available to install then, that's what it did for me. i installed, restarted, and all was well.

**Comment by rpitera** [comment]
Did you have to reconfigure after the reinstall?  I'm not sure if I can find my creds - I'd have to look in .storage to see if I can find them in the config files.
