### ISSUE TITLE
Meross Integration not available after update

### ISSUE THREAD

**Issue by ngudat** [albertogeniola/meross-homeassistant#353]
**Describe the bug**
After update meross IoT in HACS, there was an error in the notification. I deleted the integration in settings and in HACS. I reinstalled Meross IoT in HACS and tried to add it in settings/integrations but it was not available. I had tried resetting hassio and the host machine and installing previous versions.

**Your environment**
HomeAssistant version: 2022.5.3

Hardware environment: Raspberry Pi4

**Comment by xabaras75** [comment]
same situation in my case. even if I follow the instruction in issue number #350 (install master version) the problem remain

**Comment by Duke-Box** [comment]
Also can confirm this. But when I re-installed "master" it worked for me

**Comment by johnwalk61** [comment]
Thanks Duke, master worked for me.

**Comment by elnas** [comment]
Same thing as mine. Meross IOT Integration Broken after update

**Comment by ngudat** [comment]
I tried the masters as well but it didn't work for me. Will try again later. I did restore a backup version of hassio, before the update of meross and that seems have brought things back to normal but I have not tried to update meross again. everything seems to be working fine without that update.

**Comment by steveof2620** [comment]
Same here.

**Comment by PMaxx-Gaming** [comment]
I'm having this issue as well. Latest update shows it's from 2020

**Comment by Friedi1970** [comment]
Same issue. I tried to reinstall completely and it didn't work either :(

**Comment by tunisiano187** [comment]
Same here

**Comment by beber-msft** [comment]
same issue here, seems this is not maintained anymore, all issues from the last few months have been auto-closed.

**Comment by Friedi1970** [comment]
> same issue here, seems this is not maintained anymore, all issues from the last few months have been auto-closed.

Last update was yesterday or the day before ^^

**Comment by 2stooges** [comment]
I haven't upgraded yet and still working. I noticed the upgrade is a completely different version number "Meross Integration You are running version v1.2.1, version 20200412.2 is available".

Did they change repositories?  I suggest not upgrading or try and find v1.2.1 and go back to that one.

**Comment by NicciZar** [comment]
The latest version is just set wrong
![image](https://user-images.githubusercontent.com/43537611/167636913-788fcb4c-d6ae-43e6-b361-86f5c34d7f75.png)

if you search via tags you can see the newest version is v1.2.1
https://github.com/albertogeniola/meross-homeassistant/tags
![image](https://user-images.githubusercontent.com/43537611/167637060-59939cff-e1ed-4644-bb1f-cf5f7647ed7e.png)
https://github.com/albertogeniola/meross-homeassistant/releases/tag/v1.2.1

**Comment by marceskenazi** [comment]
Same problem here. Both Meross Cloud and Meross LAN are borked.
The Meross App stilll functions.

**Comment by xabaras75** [comment]
I think that the problem is HAC itself. now it is proposing me to update another integration using an old release (dated 2020) even if I already have the new one installed.
In case of Meross, for ex, I manually installed the release 1.2.1 and magically the integration work again.

**Comment by jgreen84** [comment]
I also had this problem after updating Home Assistant to 2022.5

In HACS I found the Meross Integration and chose to redownload it and then selected "master" from the list of versions. Once that had downloaded I restarted and the integration is working fine again. I hope that helps some who maybe didn't understand the other people's success above.

**Comment by albertogeniola** [comment]
Hi guys,

the problem is not HACS nor the integration. It looks like something changed on GitHub so that we lost the latest releases. I've just updated the release from tag 1.2.1 and now it should be ok. Can you please try it and let me know?

**Comment by NicciZar** [comment]
It now shows the correct version after updating information within hacs
![image](https://user-images.githubusercontent.com/43537611/167697647-011f08f8-5505-44fb-8bf1-2359044a1bbd.png)

**Comment by marceskenazi** [comment]
It is working for me after manually loading the new ZIP file.
Many thanks.

**Comment by omarantelmi** [comment]
it also works for me by uploading manually

**Comment by mclever** [comment]
I did redownload, selected 1.2.1 and then rebooted and it's working

**Comment by Duke-Box** [comment]
I can confirm, that after updating info from within HACS Meross Integration, the correct version was available for download.
After downloading V1.2.1 and rebooting HAS everything is ok.

Though it was working for me with "master" anyway.

**Comment by tankqj** [comment]
Still not working after, re-downloading, restarting.  Does not show up in Integrations to be re-added/installed. I have checked under disabled or ignored integrations too but doesn't show up there.  

It seems to install in HACS fine but just doesn't show in the Integrations within HA.

**Comment by Duke-Box** [comment]
I don't suppose this is a cache issue with your browser?

**Comment by tankqj** [comment]
> I don't suppose this is a cache issue with your browser?

That was it!  Ctrl+F5 and I can see it now.  Thanks!

**Comment by spectrum-art** [comment]
> That was it! Ctrl+F5 and I can see it now. Thanks!

This worked for me as well, thank you!
