### ISSUE TITLE
error meeros cloud integration not found

### ISSUE THREAD

**Issue by davidteles** [albertogeniola/meross-homeassistant#356]
**Describe the bug**
After the last release i get the following error meeros cloud integration not found

**Your environment**
HomeAssistant version: 2022.5.4
Hassio Version (if applicable): 7.6
Hardware environment: Intel NUC

**Logs taken when the issue happened**
```
--- PASTE LOGS HERE ---
```
![image](https://user-images.githubusercontent.com/23188280/168293948-5ced3967-fba9-428f-bf95-67b76f2579ba.png)

![image](https://user-images.githubusercontent.com/23188280/168293759-3e2aff04-49da-441e-8eca-99bb50085d24.png)

**Comment by rsefer** [comment]
I am experiencing the same issue after updating to 2022.5

**Comment by rcdd** [comment]
Same here... 
I've checked the Meeros endpoint (https://iot.meross.com) and it's giving me 403 Forbidden. 
Anyone with same issue?
<img width="1762" alt="Screenshot 2022-05-13 at 15 25 45" src="https://user-images.githubusercontent.com/13470733/168304975-c937716d-0f79-4221-aec3-00e10c1960c9.png">

**Comment by aaamoeder** [comment]
me too ... same issue

**Comment by piellex** [comment]
me too...

**Comment by TorgeTorge** [comment]
Having the same issue...

**Comment by cryptedx** [comment]
Please can you fix this? Thanks.

**Comment by albertogeniola** [comment]
Hi  @davidteles ,
according to your logs, it looks like the Meross Integration was not found: this may be due to a bad upgrade attempt.
Have you tried to reinstall the component from scratch? If so, can you attach the detailed error logs?

**Comment by davidteles** [comment]
@albertogeniola  I have redownload the repo on hacs and it now works again. Thanks

**Comment by albertogeniola** [comment]
Glad to hear that!

**Comment by piellex** [comment]
Thanks, now work perfectly
