### ISSUE TITLE
Add support to shutter MRS100

### ISSUE THREAD

**Issue by alfredoanton82** [albertogeniola/meross-homeassistant#357]
Dear Alberto, 

First of all, thanks for your library meross-iot and the integration you implemented for HA. Is working great with the smart switches.

Support to MRS100 seems not to be implemented, however in the meross-iot there is a "limited implementation" for the shutters.
https://www.meross.com/Detail/91/SmartWi-FiRollerShutterTimer?ref=riT3b8AsiR7n

Would it be possible to add the support for the shutters in the HA integration?. 

Functions allowed by the Meross App is open, close, and stop, however i think that just knowing the total time to open or close the shutter, it should be easy to be able to know the position of the shutter based on times, and it can always be reset when totally close or totally open, by forcing the total time for the opening/closure of the shutter. 

I have quite extensive programming skills, old school, Fortran, C and Java, therefore i'm not expert in python but please, let me know if I could help you with the implementation/testing of this device. I will try to understand on my side how this works and try to solve it myself, but it will take some time I'm afraid...

Thanks in advance.

Best regards
Alfredo

**Comment by TriptonPt** [comment]
Also struggling to get this working with HomeAssistant, smart plugs work without any issue but the MRS100 are not added as devices . 

Homeassistant 2022.6.7
[v1.2.5rc5]

Logs show this :

```
Found a new device Smart Roller right (mrs100, HW 2.0.0, FW 2.1.4, class: mrs100:2.0.0:2.1.4) that has become online while we were offline.
4:36:05 PM – (WARNING) /usr/local/lib/python3.9/site-packages/meross_iot/manager.py - message first occurred at 4:33:08 PM and shows up 4 times

Device Smart Roller right (#BASE:2112297493075490864348e1e983cf6b) has been already added to the registry.
4:36:05 PM – (WARNING) /usr/local/lib/python3.9/site-packages/meross_iot/manager.py - message first occurred at 4:36:05 PM and shows up 2 times

Received a push notification for a device that is not available in the local registry. You may need to trigger a discovery to catch those updates. Device-UUID: 2112293344139690864348e1e983d17c
4:35:07 PM – (WARNING) /usr/local/lib/python3.9/site-packages/meross_iot/manager.py - message first occurred at 4:34:33 PM and shows up 4 times
Received a push notification (Namespace.SYSTEM_ONLINE, raw_data: {"online": {"status": 2}}) for device(s) (2112293344139690864348e1e983d17c) that are not available in the local registry. Trigger a discovery to intercept those events.

4:35:07 PM – (WARNING) /usr/local/lib/python3.9/site-packages/meross_iot/manager.py - message first occurred at 4:34:33 PM and shows up 4 times

Device Smart Roller (2112293344139690864348e1e983d17c) is online, but timeout occurred when fetching its abilities.
4:33:08 PM – (WARNING) /usr/local/lib/python3.9/site-packages/meross_iot/manager.py - message first occurred at 4:33:08 PM and shows up 2 times
```

**Comment by albertogeniola** [comment]
Hi!
Support for Roller Shutter Timer has been added in v1.2.6, after implementing the necessary driver at lower level (MerossIot library). You can now test it if you like, just update your HA component first!

**Comment by FoxScout** [comment]
I cannot retrieve the position of the roller shutter mrs100. ¿how can I see it? In entities say it supports 11 functionalities... but I dont know. I tryied this way, without success, based on other's procedure: https://www.youtube.com/watch?v=lWeZmR3Cjlk

**Comment by viktor56240** [comment]
Good morning,
Same for me, the opening and closing works correctly but I have no feedback on the position.
Do you have a solution for this?

**Comment by FoxScout** [comment]
What I found in muy google research is that these 11 functionalities can be shown if you write this (changing the name of entity) in servicies: {{ states.cover.name_of_your_entity }}
But no positioning is given. So, internet say that it is needed to implement in the python library that controls the device... so, I am guessing that @albertogeniola has to implement this? or someone else that helps to be implented in the MEROSS integration libraries.

I can try to help, I wanted to make the variables in helpers, but it's hard to manage, so I could try in python if Alberto helps me telling me how to open and see his code. and how can I make tests.

**Comment by viktor56240** [comment]
I think we should open a new PR because this one is closed and I don't think @albertogeniola  will come through here?

**Comment by walterwhite-star** [comment]
I have the same trouble no position feedback for shutter MRS100
