### ISSUE TITLE
MSG200 Support

### ISSUE THREAD

**Issue by brbi76** [albertogeniola/meross-homeassistant#363]
Please ad support for msg200  smart garage door opener. The current integration in not full functionaly.

**Comment by albertogeniola** [comment]
Hi @brbi76,

MSG200 support should be already in place with last versions. Can you provide some more details about the missing functionality?

**Comment by albertogeniola** [comment]
Closing. Feel free to re-open if still relevant.

**Comment by PeetersCarl** [comment]
When adding this repository to HA and logging in with my Meross account I'm only able to control my first garage door, the other is not showing up. Can you help me?
