### ISSUE TITLE
Not listed in energy monitor

### ISSUE THREAD

**Issue by inoxas78** [albertogeniola/meross-homeassistant#364]
**Describe the bug**
I have 8 plugs, on each i can add an integration on dashboard to see W consumption, but in energy monitor it seems to be invisible, do you know how can i solve this?

**Your environment**
HomeAssistant version: -- 2022-6-22  --
Hassio Version (if applicable): -- 1.25.5 --
Hardware environment: -- Raspberry pi 4 --

**Logs taken when the issue happened**
```
Nothing in log, every thing is fine
```

**Comment by chicco83** [comment]
same issue for me. also using "integration" integration the virtual sensor is not shown in energy monitor

**Comment by belikh** [comment]
same issue here. 
![Screenshot from 2022-06-09 21-39-14](https://user-images.githubusercontent.com/4435491/172838183-9d0987ac-ca63-492c-b857-ed9ae4dad15c.png)
attributes are missing, in particular unit_of_measurement is missing.   Can't use integration to convert None to kWh.
