### ISSUE TITLE
[CALL FOR ARMY] Local Addon testing

### ISSUE THREAD

**Issue by albertogeniola** [albertogeniola/meross-homeassistant#368]
# [🎉](https://emojipedia.org/party-popper/)[🥳](https://emojipedia.org/partying-face/) Local Addon is HERE! [🎉](https://emojipedia.org/party-popper/)[🥳](https://emojipedia.org/partying-face/)[🎉](https://emojipedia.org/party-popper/)

Hi all!
Today I released the very first version of the local meross addon, running on HA, which enables off-grid local management of Meross devices, directly in HA. 

The entire set of software components that are necessary to take Meross devices offgrid are:
1. The HA local addon, which implements MQTT broker with appropriate MQTT version support to match the Meross devices capabilities, alongside the HTTP API layer necessary to deal with the control pane;
1. The Meross Custom Pairer app, which runs on Android devices, and is able to pair Meross devices with the local broker;
1. The Meross custom component integration, which integrates Meross devices into HA by dialogating with the Meross cloud or via the local addon (that's what we need now!)
1. The underlying MerossIot library that implements the python driver to work with Meross API layer (both with the local and the official Meross API).

The entire ecosystem is still fragile and far from being production ready. Consider it as a prototype which needs refinement, bugfixing and, most of all, documentation and tutorial. Since my time is becoming more and more limited, I'd ask you guys to help me with providing appropriate documentation, tutorials and support for the users who will try this integration. 

Also, any bug issue will be welcomed, especially when filled in with specific debugging details.

**Comment by joselcaguilar** [comment]
For unknown reason, I cannot install v1.2.5rc1 through the UI:

![image](https://user-images.githubusercontent.com/7523585/174443313-c55d5a42-4e65-49c9-bda0-e8526dfa6c42.png)

Thanks for the hard work @albertogeniola 🥳

**Comment by arohl** [comment]
> For unknown reason, I cannot install v1.2.5rc1 through the UI:
> 
> ![image](https://user-images.githubusercontent.com/7523585/174443313-c55d5a42-4e65-49c9-bda0-e8526dfa6c42.png)
> 
> Thanks for the hard work @albertogeniola 🥳

 v1.2.5rc1 has broken for me. Tried removing and reinstalling and now get same error as above. I have also tried to download previous version through the HACS gui but no joy there either

**Comment by albertogeniola** [comment]
HI @joselcaguilar and @arohl ,
that happened to me one time ago. I had to remove the integration via HACS, reboot, install the integration back via HACS, reboot again. Can you test it please?

**Comment by joselcaguilar** [comment]
It has been fixed @albertogeniola, thanks! I have discovered another one, when I clicked on local broker it failed with an "unknown error", however the local broker is running and working like a charm with the Meross LAN integration from Krahabb.

![image](https://user-images.githubusercontent.com/7523585/174448425-c066dd11-b42d-4800-991f-5d6eeee5a234.png)

Let me know if I can help to debug :)
Best regards, j

**Comment by albertogeniola** [comment]
Hi, 
Yeah, the latest release seems unable to discover the MQTT broker via mDNS discovery, I confirm that. I need more time to debug that: hopefully I'll fix that by the end of the weekend.

**Comment by arohl** [comment]
> Hi,
> Yeah, the latest release seems unable to discover the MQTT broker via mDNS discovery, I confirm that. I need more time to debug that: hopefully I'll fix that by the end of the weekend.

RC2 works for me - many thanks @albertogeniola

**Comment by moto3001** [comment]
Hi, is the local support similar to MerossLan on HACS? https://github.com/krahabb/meross_lan

If it’s different, how so?

Thanks!

**Comment by Parzival0x** [comment]
> It has been fixed @albertogeniola, thanks! I have discovered another one, when I clicked on local broker it failed with an "unknown error", however the local broker is running and working like a charm with the Meross LAN integration from Krahabb.
> 
> ![image](https://user-images.githubusercontent.com/7523585/174448425-c066dd11-b42d-4800-991f-5d6eeee5a234.png)
> 
> Let me know if I can help to debug :) Best regards, j

I'm seeing the same issue on my end.

**Comment by joselcaguilar** [comment]
Hi @albertogeniola,

Just sharing another warning showed on Supervisor logs:
`WARNING (MainThread) [supervisor.addons.options] Option 'debug_port' does not exist in the schema for Meross Local Broker Addon (ab1234ab_meross_local_broker)`

Do you know how can we help to address this?
Thanks!

**Comment by joselcaguilar** [comment]
> HI all, please update the addon to version 0.0.1-alpha43 and also update the Meross Cloud integration to v1.2.5rc3. Those two versions should play nice together.

Both updated, I can see now the dialog when I try to add the integration, but by default it takes as HTTP API Endpoint the address `http://homeassistant.local:2003` and always fail, I have tried with `http://myIP:2003` but again is failing, so I opened the Custom Pairer App on my mobile in order to discover the endpoint and I can see that it detects `http://myIP:**62748**` and I tried to authenticate, but it fails again.

What's the correct endpoint? In the addon config I have the HTTP API Port set to 2003 and I can access to the dashboard using the ingress url through HA only.

**Comment by colejv76** [comment]
I am seeing the same behavior as above 

from the logs 

[14:48:24] INFO: Substituting ingress_entry with /api/hassio_ingress/*redacted*
[14:48:24] INFO: Substituting interface with 172.30.32.1
[14:48:24] INFO: Substituting port with 65468

the interface listed above is the docker gateway, not the IP address of my home assistant server

**Comment by colejv76** [comment]
I was able to get it working with alpha44, I had a slight issue at first with the integration asking me to reconfigure which was failing with the unknown error and there was no way to delete it, I finally configured it for cloud which allowed me to delete it and start over and it's working   

Good job

**Comment by albertogeniola** [comment]
Yup, Addon v0.0.1Alpha44 and integration V1.2.5rc4 should now work even if the mDNS resolution fails, as the default values are prefilled with standard parameters. This means that it should just work as long as the user does not remap the addon ports. 

This trick should.mitigate the cases where mDNS does not work.

**Comment by joselcaguilar** [comment]
> Yup, Addon v0.0.1Alpha44 and integration V1.2.5rc4 should now work even if the mDNS resolution fails, as the default values are prefilled with standard parameters. This means that it should just work as long as the user does not remap the addon ports.
> 
> This trick should.mitigate the cases where mDNS does not work.

It is working like a charm now @albertogeniola, thanks!

Just minor adjustments on entities once the device is detected, what was discovered using the meross-homeassistant integration:
![image](https://user-images.githubusercontent.com/7523585/175404449-720f251e-9c5b-4add-bef7-a2f44276a51f.png)

What was discovered by Meross LAN integration (same device):
![image](https://user-images.githubusercontent.com/7523585/175404788-4e734295-3c97-43ba-ad40-29c0ddcaa940.png)

On the other hand, cloud dependency info might be removed from UI:
![image](https://user-images.githubusercontent.com/7523585/175405057-2f0cd661-4d66-4cde-9bdc-6609c1ad9b98.png)

Last but not least, the warning on Supervisor still remains (I don't know if it will be addressed later):
`WARNING (MainThread) [supervisor.addons.options] Option 'debug_port' does not exist in the schema for Meross Local Broker Addon (ab1234ab_meross_local_broker)`

**Comment by josntrm** [comment]
Hello @albertogeniola 

So i switched to LAN addon for my 4 MSS310 plugs, because cloud add-on was always disconnecting after a few hours, certainly because of API limitations from Meross. 
So far everyhting seems to work fine, control and power readings. But as i loose the ability to control plugs from outside by using LAN only add on, i wanted to try on "Enable Meross Link" option and using my Meross credentials. Unfortunately it didn't help getting back the control of plugs in Meross app. I know this is under starting development but is there something i can try to make it work for now? By the way even if the cloud function doesn't work, this option doesn't seem to interfere with LAN functions. 

Thanks a lot anyway for all your work!

**Comment by albertogeniola** [comment]
Hi @josntrm ,
I've just released version alpha45, which fixes one issue preventing the local bridge option from being applied.
I've tested it quickly and not extensively and it's working with a MSS310. However there are some pitfalls to consider (which I need to fix):
1. Once you enable the MEROSS_LINK, you need to re-pair all the devices again with the pairer app. 
2. The name of the devices will be "unknown" or something like that, which isn't probably the best

So, if you can't wait to test it, feel free to do so. Remember to upgrade the addon, restart it, reset the hardware devices, re-configure the addon with you Meross account (and enable the link option); the use the pairer app to pair again the devices.
That should make it: you'd be able to command the same device both with the Meross app and with the HA addon/integration.

I'd ask you to open a new issue to report back your findings so we keep this issue clean.

**Comment by prjcarr** [comment]
I have installed alpha45 and have the device paired and online. In the HA integration after setup, I am getting "Retrying setup: None". 

In the logs for MQTT Service I am getting "level=warning msg="wrong password for user _agent"

I have checked and the password is correct. 

In the local agent log I am getting:

2022-07-12 08:22:13.252518633 WARNING:Client has been disconnected. Connection will be re-attempted.
2022-07-12 08:22:13.252365092 DEBUG:Disconnection detected. Reason: 5

Any ideas?

**Comment by prjcarr** [comment]
> I have installed alpha45 and have the device paired and online. In the HA integration after setup, I am getting "Retrying setup: None".
> 
> In the logs for MQTT Service I am getting "level=warning msg="wrong password for user _agent"
> 
> I have checked and the password is correct.
> 
> In the local agent log I am getting:
> 
> 2022-07-12 08:22:13.252518633 WARNING:Client has been disconnected. Connection will be re-attempted. 2022-07-12 08:22:13.252365092 DEBUG:Disconnection detected. Reason: 5
> 
> Any ideas?

I got it working. I did two things - restarted the add on and also disabled and re-enabled the integration. Not sure which one did it.

I had previously tried rebooting HA and also deleted the integration and re added it multiple times. None of that worked, but the above did.

**Comment by Lordnnud** [comment]
Hi @albertogeniola 
I'm running V1.2.5rc5 with Alpha 45, Core 2022.7.3.

All is well, I've installed and configure everything to work with Meross Local Broker. On the Broker UI it shows my Garage Door device with valid network info (Mac and IP addr). The status is "NOT_ONLINE" Meross Link: Disconnected. I can ping the device ok so it's alive and well.

How can I resolve thsi please ?

**Comment by Lordnnud** [comment]
Hi,
I'm running V1.2.5rc5 with Alpha 45, Core 2022.7.7 for about a month now with no issues. I only have a garage door opener.

Occasionally the Meros Door opener drops offline or looses its senses, so only a hard reboot the device will fix.

However it would be nice to able able to recycle the broker from within Home Asistant before having to drag myself out to the garage.

**Comment by Julien-D** [comment]
Hi,
I use the local addon for a couple of MSL120  bulbs.
In my logs, I have the following warning message when I boot home assistant 👍 Cette erreur provient d'une intégration personnalisée
```
Logger: meross_iot.model.http.device
Source: custom_components/meross_cloud/__init__.py:341
Integration: Meross Cloud IoT
First occurred: 21:02:46 (2 occurrences)
Last logged: 21:02:46

Provided bind_time is not int neither datetime. It will be ignored.
```
Otherwise, it works perfectly.
Julien

**Comment by midadami** [comment]
I have changed from the meross cloud to local addon 3 mss310 plugs. While the toggle/control works perfectly, the power readings don't work. The power readings for the 3 mss310 plugs stay at 0 without any change (voltage, amps and power).

Any idea whats going on and/or how I can find out?
I use the readings for important parts of my home so sadly it's not an option to leave it like this.
Thanks

**Comment by josntrm** [comment]
Hello, 

I am been using local addon with several MSS310 plugs without any issue for a while. I just bought two new MSS310 plugs and while i've been able to add these plugs flawlessly, i cannot get the power readings from these new plugs. I have the same issue as the post just before from midadami. Power readings always shows 0 from these two new plugs.
I've found a difference though, in the Meross Cloud IOT integration page my old MSS310s (working) are version 2.0.0, the new ones (not working) are version 6.0.0.
Is this a firmware compatibility issue? Is there a way to solve this?
Thanks

**Comment by Mr-Alicates** [comment]
Regarding the MSS310 issues, I have 4 plugs with firmware 6.1.10 and several ones with the 2.1.16

I have an install with local broker addon and I'm using the meross iot integration.

The ones with FW 6.1.10 don't show power readings but the ones with 2.1.16 show it.

Is there any workaround for this?

**Comment by Lordnnud** [comment]
> I've been using this 



> Hi, I'm running V1.2.5rc5 with Alpha 45, Core 2022.7.7 for about a month now with no issues. I only have a garage door opener.
> 
> Occasionally the Meros Door opener drops offline or looses its senses, so only a hard reboot the device will fix.
> 
> However it would be nice to able able to recycle the broker from within Home Asistant before having to drag myself out to the garage.

I've been uisng this since mid-july. It's been rock solid :-)

**Comment by Filippo125** [comment]
Hello,
i want to help in testing, but i can't find the local addon in the repository. It seems to be a broken link to repository. https://github.com/albertogeniola/meross-local-homeassistant

What am I wrong?

**Comment by jscmidt** [comment]
Hi,
What is the difference between this an the Meross LAN Integration  https://github.com/krahabb/meross_lan ?

**Comment by Niek** [comment]
> Hello, i want to help in testing, but i can't find the local addon in the repository. It seems to be a broken link to repository. https://github.com/albertogeniola/meross-local-homeassistant
> 
> What am I wrong?

Same here, what is the process to install the add-on? It's not listed in the store and the link above is 404.

**Comment by deevus** [comment]
> Regarding the MSS310 issues, I have 4 plugs with firmware 6.1.10 and several ones with the 2.1.16
> 
> I have an install with local broker addon and I'm using the meross iot integration.
> 
> The ones with FW 6.1.10 don't show power readings but the ones with 2.1.16 show it.
> 
> Is there any workaround for this?
> 
> I'm seeing this in the logs:
> 
> `Logger: meross_iot.model.http.device Source: custom_components/meross_cloud/**init**.py:196 Integration: Meross Cloud IoT First occurred: 19:59:58 (7 occurrences) Last logged: 19:59:58
> 
> Provided bind_time is not int neither datetime. It will be ignored.`
> 
> I'm also seeing this one:
> 
> Logger: meross_iot.model.enums Source: /usr/local/lib/python3.10/site-packages/meross_iot/model/enums.py:128 First occurred: 21:48:17 (30 occurrences) Last logged: 22:35:18
> 
> Namespace Appliance.System.Clock is not currently handled/recognized. Namespace Appliance.Control.ConsumptionConfig is not currently handled/recognized.

I am seeing the same issue

**Comment by josntrm** [comment]
> > Regarding the MSS310 issues, I have 4 plugs with firmware 6.1.10 and several ones with the 2.1.16
> > I have an install with local broker addon and I'm using the meross iot integration.
> > The ones with FW 6.1.10 don't show power readings but the ones with 2.1.16 show it.
> > Is there any workaround for this?
> > I'm seeing this in the logs:
> > `Logger: meross_iot.model.http.device Source: custom_components/meross_cloud/**init**.py:196 Integration: Meross Cloud IoT First occurred: 19:59:58 (7 occurrences) Last logged: 19:59:58
> > Provided bind_time is not int neither datetime. It will be ignored.`
> > I'm also seeing this one:
> > Logger: meross_iot.model.enums Source: /usr/local/lib/python3.10/site-packages/meross_iot/model/enums.py:128 First occurred: 21:48:17 (30 occurrences) Last logged: 22:35:18
> > Namespace Appliance.System.Clock is not currently handled/recognized. Namespace Appliance.Control.ConsumptionConfig is not currently handled/recognized.
> 
> I am seeing the same issue

I am having the exact same issue for a while now. I tried to upgrade meross integration to 1.2.10 but then i discovered it wasn't working with local only paired meross plugs. So i reverted to 1.2.8
Same issue, my 4 plugs using 2.1.16 firmware are fine. But i have 2 newer plugs with 6.1.10 firmware for which i cannot get power readings

Also i can read in logs the same kind of errors about bind_time. 

And then i just disovered this thread talking about an general issue with meross plugs, apparently when the meross plug is unable to sync its time at startup with ntp server, it will not send the power values. 
https://github.com/krahabb/meross_lan/issues/300
Since our plugs using firmware v6.x are not giving power readings, it may be because their ntp request is not correctly answered by local broker.

Would there be a way to provide correct sync time to the plugs? 
Or would we have to switch to cloud pairing method to get these plugs working with meross integration. I really prefer the local only method because it's not dependent of the the changes that could be made on meross side..
