### ISSUE TITLE
Local Addon linked to Meross Cloud

### ISSUE THREAD

**Issue by josntrm** [albertogeniola/meross-homeassistant#369]
Hi @albertogeniola 

As requested i open this new issue to report back regarding the Link option in the Meross local add-on.
But this is not really a bug report as everything seems to work well for now.

As suggested i've updated to version alpha45, logged again in the setup with my Meross cloud credentials and activated the Link option, and re-paired all 4 MSS310 plugs i own. Everything went flawlessly, and the plugs appeared again in Meross app. Control and power data is still working fine in HA.

One thing i forgot to do is resetting the hardware devices before re-pairing, i just re-paired them with the Android app, without deleting before. The names i previously gave to devices in the local addon broker were actually kept after re-pair! The only thing i had to do is rename the plugs in the Meross app. I think this is due to the fact that i didn't reset hardware devices. But for me it's perfect!

So for now eveything seems good. I will report if i find something wrong in the next days.

Thanks a lot!

**Comment by josntrm** [comment]
Hi @albertogeniola, 

So today i have my first issue with local addon linked to Meross Cloud. I had to restart my ISP Wifi router (the network that connects Meross plugs and HA), and since then all Meross devices report are reported offline in HA, in Local Meross Broker, as well as in the Custom Pairer App.
I tried to restart HA, and to restart some plugs but nothing helps here.
The system logs doesn't contain any interesting infos, only saying that devices are offline.
I have one error though, but i don't think it's related : 

" Logger: meross_iot.model.http.device
Source: /usr/local/lib/python3.9/site-packages/meross_iot/model/http/device.py:49
First occurred: 20:40:56 (24 occurrences)
Last logged: 20:48:57
Provided bind_time is not int neither datetime. It will be ignored."

But one thing to note is that while everything seems offline in HA, the link function to Meross cloud is working because i still have access to plugs in Meross app and i can control them! Weird..

**Comment by josntrm** [comment]
Hi @albertogeniola 

I did some more testing about the disconnection with Meross Cloud Link enabled.
First of all the first time i had problem i was actually reinstalling my desk and i had to restart my wifi network. This is when the plugs disconnected from HA and reconnected only to Meross Cloud.
It happened once again during an evening but this time nothing happened in the network or power. All my 4 four plugs just disappeared from HA and the Status in Local broker Add On was UNKNOWN. Restarting the addon or integration didn't solve the issue. I have to repair with the app.

So i decided to restart from scratch, removed the plugs from Meross Cloud, i changed my Meross Cloud password (to avoid connection memory), changed credentials in Local Broker Addon and repaired all 4 plugs. Everythin was Online.
Then i tried what you were proposing, unplugged/replugged one of the plugs and looked at entries in Status/Local API page. I did see the entries concerning this plug (with the right ID) and looking at Home Page, the plug was Online.
But then i tried to restart HA and i noticed two things : 
-While HA was restarting (and so local addon was off), the plugs never showed any disconnection status, and they were still usable with Meross Cloud app !
-When HA finished restarting the plugs were Online in Local Addon except the one i had previously replugged which is now Offline.

I stopped HA to re-check that plugs were usable with Meross Cloud without the Local Addon running. it was indeed the case. Then when i restarted HA, all the plugs were in status UNKNOWN in Local Broker Addon...

I don't understand what's going on. For me it's as if when using Local Add On with Meross  Cloud Link, the connection with Local Add On and with Meross Cloud was made in a parallel way, not a serial way, meaning that the plugs when  paired were connected directly to Local Add On and Meross Cloud. So when for a reason the connection is lost with Local Add On, the plugs doesn't try to reconnect because they're already still connected to Meross Cloud. Does that make any sense?

Thanks

**Comment by smartmatic** [comment]
Hi,

i am interested in testing the local add-on and installed it. But no now i am struggling with setting up the local Broker. I am asked to install Meross Pairer App from Google Play Store but i am an iOS user.

Is there also a App for iOS user or how to proceed as iOS user?

**Comment by albertogeniola** [comment]
Hi @smartmatic ,
I am afraid not. Apple is not an "open" platform like Android or HA and that has always been something I did not like, that is why I have never developed on that platform and I am not planning to do so. Maybe we can think of a Python/Nodejs Script to run on a Linux machine, but that won't be available any soon, I'm afraid.
