### ISSUE TITLE
MSS530H Device "Main Switch" don't reflect status on single switch

### ISSUE THREAD

**Issue by GianCann** [albertogeniola/meross-homeassistant#37]
I have successfully integrated the MSS530H device, a 3-way wall light switch.
HA detects the device as 4 switches, one for each channel, and one for all 3 channels.
Everything works perfectly.
The only problem is that when the 4th device is operated, the states of the individual switches are not updated: The lights are turned on (all 3), but the individual switches on the HA UI remain in the OFF position. And viceversa.

**Comment by GianCann** [comment]
(Alberto, i'm Gianluca, from Florence)

**Comment by ITensEI** [comment]
Same issue on MSS425E surge protector power strip

**Comment by albertogeniola** [comment]
Please update to the latest version (v1.0.0) which fixes the problem alongside various improvements.
