### ISSUE TITLE
Meross mss310 don't show on energy

### ISSUE THREAD

**Issue by alessiovalvano** [albertogeniola/meross-homeassistant#370]
i've just linked my new meross mss310, i read on one of your post that i could use energy meter on this.
i currently see the dashboard with energy consumption, but if i go to energy dashboard i can't add it on the consumption elements.

![image](https://user-images.githubusercontent.com/107791588/176456804-dcaf23fb-d463-46df-b20e-8204ae0504bd.png)

but i correct see on other widgets
![image](https://user-images.githubusercontent.com/107791588/176456948-5c8b37d9-2def-4107-a03d-b2d5472967ac.png)

can you help me?

**Comment by nlubello** [comment]
Interested to add same feature too, if anyone has some documentation from Meross API I can give a try
