### ISSUE TITLE
Alexa, possible integration?

### ISSUE THREAD

**Issue by DomoMaxaM** [albertogeniola/meross-homeassistant#371]
Hi Alberto, congratulations for the work done so far.
I am testing your "Pair" app and paired with the "Meross IoT" app for mss710 and mss310 products, everything works fine. Currently used as a simple switch and simple socket. I have various Meross products to combine with the local cloud, but before performing the complete migration to it, I asked you if there is the possibility of combining them, that is, have them also detected by Alexa, or if there is already a way (I currently do not l 'I found ). Given that I have already activated Alexa on HA, to forbid the procedure for free.
Thank you in advance and congratulations again.

**Comment by DomoMaxaM** [comment]
Hi Alberto,
Thanks for the reply.
Yes, my intent is or was to use the device with both Alexa and HA, but without the Meross app. Also because I wanted to get rid of the official app, but without giving up the integration with Alexa.
But from what I understand, without the Official Meross app, I can't integrate it with Alexa, right?

**Comment by albertogeniola** [comment]
Hi!
Unfortunately, as far as I know, you must use your official meross account to use Alexa. This means you need to only keep your Meross Account active. In other words you might uninstall the Meross app,  pair the devices via the Custom Pairer app using the local addon with the Meross Link option and still have the devices federated with Alexa.

In my opinion, however, having the Meross App installed is still a good second option of HA gets stuck (remember, the local addon is still in development and is not stable).
