### ISSUE TITLE
Skip MQTT cert validation option set to: False

### ISSUE THREAD

**Issue by tarheelz** [albertogeniola/meross-homeassistant#374]
Log Details (WARNING)
This error originated from a custom integration.
Logger: custom_components.meross_cloud
Source: custom_components/meross_cloud/__init__.py:388
Integration: Meross Cloud IoT
First occurred: 6:55:06 PM (1 occurrences)
Last logged: 6:55:06 PM

Skip MQTT cert validation option set to: False

**Comment by albertogeniola** [comment]
Hi!
What is the issue you are experiencing, exactly?

**Comment by tarheelz** [comment]
Apologies.  I see that this report is expected per the repository documentation.  The problem is simply the mild annoyance of the regular warning in the logs.  As I think I'll adopt the MQTT server approach, this will be mooted in my instance as I understand things.  You can close this.  The warning seems purely cosmetic.
