### ISSUE TITLE
change color for meross msl120dr bulbs

### ISSUE THREAD

**Issue by warlordattack** [albertogeniola/meross-homeassistant#376]
we need be able to change bulbs color,
i have various RGB bulbs msl120dr and ambilight,
i want to match automaticly my bulbs color to my PC wallpaper dominant color
so when wallpaper engine change my wallpaper, my bulbs would match this color

please implement color change to meross bulbs msl120dr :)

**Comment by albertogeniola** [comment]
Hi @warlordattack ,

as per my understanding, you should be already be able to change color of your meross device. If not, please open a different issue [here ](https://github.com/albertogeniola/MerossIot/issues) and [provide a sniffed payload](https://albertogeniola.github.io/MerossIot/advanced-topics.html#sniff-device-data) to let me integrate your hardware with the library.
