### ISSUE TITLE
Component Setup: Integration not found.

### ISSUE THREAD

**Issue by alexanderVonBergner** [albertogeniola/meross-homeassistant#377]
**Describe the bug**
After installing "Meross Integration" and restarting Homeassistant, I cannot find a "Meross Cloud IoT" Integration in Settings>Integrations>Add. I also notices that the HACS-Integration that I installed has the Name "Meross Integration" instead of "Meross Cloud IoT", as mentioned in your Setup Guide.

**Your environment**
HomeAssistant version: Home Assistant 2022.7.6, Supervisor 2022.07.0
Hardware environment: Raspberry Pi 2B
Memos Integration version: v1.2.5rc5

**Logs taken when the issue happened**
```
no logs found
```

**Comment by alexanderVonBergner** [comment]
Alright, I think I got it. Cleaning the cache and deleting the website cookies made the Integration appear afterwards. Maybe you could add a hint to the setup guide?

**Comment by albertogeniola** [comment]
Glad you solved it!
