### ISSUE TITLE
Cannot update to the latest release with HACS

### ISSUE THREAD

**Issue by mfabiani53** [albertogeniola/meross-homeassistant#38]
I am trying to update to the latest release through HACS, but i always get the 'download not complete' error and the integration doesn't update
```
2020-01-07 20:55:51 ERROR (MainThread) [hacs.repository.integration.albertogeniola.meross-homeassistant] Download was not complete.
2020-01-07 21:00:48 ERROR (MainThread) [hacs.repository.integration.albertogeniola.meross-homeassistant] Download was not complete.
```
I try also to uninstall and then reinstall the component, but unsuccesfully.
Now i have installed manually but in this way HACS doesn't recognize it and i will not have notifications about new updates.

**Comment by Mongomeri** [comment]
The same error and problem for me, I also tried in the past few days, always getting the same result

**Comment by githubjles** [comment]
Same problem, does not update.

**Comment by woody4165** [comment]
same as @mfabiani53 via HACS
no update, uninstalled and now not able to install it again.

How can we solve?

Thanks

**Comment by albertogeniola** [comment]
Hi Guys,
I was able to reproduce. The problem was due to an invalid ZIP file being added as release. It should now be fixed. Could you please try with the latest version and let me know if does it work now?

**Comment by woody4165** [comment]
Now it's working for me, installing from scratch after uninstalling.

**Comment by githubjles** [comment]
![E77DB3A6-1826-42CC-8F7D-8C17A2989858](https://user-images.githubusercontent.com/8670396/72101563-45701000-3325-11ea-8d6a-3a514f03fae9.jpeg)
Updated to a version that doesnt exist¿?, but now same problem, does not update to the last indicated.

**Comment by woody4165** [comment]
Ops!
You're right

The one installed now is the one that was not installing previously.
Installing from scratch, the version proposed was the 20200109.4, but the installed one is the 20200105.8.
And now after updating even if it says that was installed, after restarting HA, it's still on the  20200105.8.

![Schermata 2020-01-09 alle 21 27 03](https://user-images.githubusercontent.com/6501444/72102586-a7317980-3327-11ea-8402-ba699cc9c545.png)

**Comment by albertogeniola** [comment]
Please restart homeassistant. Once restarted, updated and then restart again.

**Comment by woody4165** [comment]
I'm sorry, no change

Restarted, updated and restarted again, same as above

**Comment by githubjles** [comment]
Get stuck at 20200105.8 here too.

**Comment by albertogeniola** [comment]
Ok. Try now. I guess I found a bug with HACS: please try the latest version available. If it works, I'll report the issue to the HACS guys.

Please let me know!

**Comment by githubjles** [comment]
Ok, updated now, had to go through the 20200109.4 first and then update to the 20200109.5, but it worked.

Thanks again!!

**Comment by woody4165** [comment]
Same as @githubjles and now it's updated to latest version.

Thanks!

**Comment by albertogeniola** [comment]
Thank you guys.

**Comment by albertogeniola** [comment]
Bug confirmed by HACS guys
https://github.com/hacs/integration/issues/922
