### ISSUE TITLE
Meross Smart WiFi Essential Oil Diffuser Mod100

### ISSUE THREAD

**Issue by LordHenry76** [albertogeniola/meross-homeassistant#380]
I can't integrate it with Meross Cloud IoT.
Is it a compatibility problem?
Thanks

**Comment by albertogeniola** [comment]
Yes, it is. At the moment, I do not own any oil diffuser device to reverse engineer. Before being able to do so, I first need to get my hands on one of them.

**Comment by artskeit** [comment]
I'd also love to integrate a Meross Oil Diffuser to my Home Assistant. The version i own is the MOD150 though. I hope you will be able to get your hand on this device!

**Comment by albertogeniola** [comment]
Hi! Latest version (v1.3.0) added support for oil diffuser. Can you please try and provide feedbacks? Thanks!

**Comment by albertogeniola** [comment]
Closing as no feedback was received. Feel free to open again if needed
