### ISSUE TITLE
Sensor energy

### ISSUE THREAD

**Issue by manustars** [albertogeniola/meross-homeassistant#385]
it is possible to see the "total consumption" sensor and convert everything into kwh

**Comment by F74** [comment]
https://github.com/krahabb/meross_lan/issues/207#issuecomment-1220490670

**Comment by magnum** [comment]
i've a similan problem, this is the error

```Entity not defined
Check the integration or your configuration that provides:
sensor.presastudio2_month_energy
```

<img width="1767" alt="Screenshot 2022-09-09 alle 21 00 03" src="https://user-images.githubusercontent.com/9384/189424770-89b4d087-86ce-4b30-be9f-de03ea36f49f.png">

**Comment by albertogeniola** [comment]
Hi!
The total daily consumption should be calculated directly via HA. The Meross plugs should only be used to gather instant metrics on power consumption.
