### ISSUE TITLE
Flickering when using in groups

### ISSUE THREAD

**Issue by jscmidt** [albertogeniola/meross-homeassistant#386]
**Describe the bug**
When the Meross bulb is already off an I turn off a group the meross bulb belong to the bulb shortly Fades in without any reason

**Your environment**
All newest, installed on docker

**Logs taken when the issue happened**
Don’t know which logs could be relevant here?

Maybe this videos helps to better understand the problem (second 18):
https://we.tl/t-qA0VLShqiK

**Comment by JSAnyone** [comment]
It's not stale...

**Comment by albertogeniola** [comment]
Hi @jscmidt ,
I tested the exact same situation you described with integration version v1.2.6 and two lights (MSL120). I was unable to reproduce the issue: my light bulbs do not fade. Cal you please provide a more information about the issue? In particular:
- Hardware type of your setup (MSL120? MSL110?)
- Group composition (which devices do take part of the group?)
- Homeassistant version
- Meross integration version

Without that info, it's hard for us to reproduce the issue.

**Comment by jscmidt** [comment]
Hi,
Sorry for the late reply.


> * Hardware type of your setup (MSL120? MSL110?)
MSL120
> * Group composition (which devices do take part of the group?)
Only two MSL120
> * Homeassistant version
Newest
> * Meross integration version
Newest

Here a video:

**Comment by jscmidt** [comment]
I‘m really sorry, I just realized that I use the Meross LAN integration not this one…
