### ISSUE TITLE
MTS200 add floor temeprature sensor and eco mode

### ISSUE THREAD

**Issue by JanZimmer** [albertogeniola/meross-homeassistant#387]
**Is your feature request related to a problem? Please describe.**
The MTS200 provides floor temperature readings.
Also, besides, on-off, auto, heating, and cooling, it has a separate eco mode.

**Describe the solution you'd like**
It would be awsome to have a separate floor temperature sensor or at least another attribute at the thermostat, so one could create a template sensor.

Also, the eco mode should be available via the climate entity.

**Comment by cagnulein** [comment]
@zimjjan did you handle it?

**Comment by zimjjan** [comment]
No neither of the things are currently available. The issue was auto-closed.
