### ISSUE TITLE
Meross Diffusor

### ISSUE THREAD

**Issue by msteingr** [albertogeniola/meross-homeassistant#388]
Hello Im not sure if I'm writing in the correct place
I have a Meross Diffusor which works well on there app but I'm unable to get it in the Home assitant working.  I installed the Meross Cloud LOT on but the diffusor does not show as an unit.. any help  please
marc

**Comment by albertogeniola** [comment]
Hi!
The current version of this integration does not support the latest diffusers, yet.

I am planning to add the necessary support in the next few releases.

**Comment by msteingr** [comment]
Hello Alberto thanks for the email do you have any timeline for this
I know it’s your personal time 😇

Thanks
Marc
