### ISSUE TITLE
Devices triggered for updates while disabled

### ISSUE THREAD

**Issue by Kalma-House** [albertogeniola/meross-homeassistant#39]
Hi,

I get the following errors in the log:

WARNING (MainThread) [homeassistant.helpers.entity] Entity switch.meross_mss310_1 is incorrectly being triggered for updates while it is disabled. This is a bug in the meross_cloud integration.

and

WARNING (MainThread) [homeassistant.helpers.entity] Updating state for switch.meross_mss425e_1_main (<class 'custom_components.meross_cloud.switch.SwitchEntityWrapper'>) took 0.531 seconds. Please report platform to the developers at https://goo.gl/Nvioub

**Comment by albertogeniola** [comment]
Hi, I can reproduce the issue. It's not critical for Homeassistant, however is not aligned to the expected entity behavior. 

Thanks for the spot.

**Comment by Kalma-House** [comment]
No worries. Just so you are aware of it.

**Comment by albertogeniola** [comment]
Fixed with latest (20200222.4).
