### ISSUE TITLE
MSS310 SmartPlug

### ISSUE THREAD

**Issue by Nagi2626** [albertogeniola/meross-homeassistant#395]
Not all data is transmitted with the MSS310 connector to homeassistant. 
Only current power consumption, but not per day or month. In the app there is the data.

maybe there is a way to get the data yet?

**Comment by albertogeniola** [comment]
HI Nagi, 
that's a feature we do not currently implement, I'm sorry. Daily power usage should be caluclated via HA reading the instant metrics, though.
