### ISSUE TITLE
MSS310: Hack mode seems to stop working with firmware version 6.3.6

### ISSUE THREAD

**Issue by Spielkind88** [albertogeniola/meross-homeassistant#397]
**Describe the bug**
I have several MSS310 plugs running. All with firmware version 6.1
With this version the hack mode works. But from version 6.3 on this does not seem to work anymore. The error message in German is: "Geräteschlüssel fehlerhaft: Wählen Sie 'Cloud retrieve' um von Meross zu kommen"

**Your environment**
HomeAssistant version: 2022.10.3
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: HA is running in Docker

**Logs taken when the issue happened**
```
--- PASTE LOGS HERE ---
```

**Comment by albertogeniola** [comment]
Hi!

What is the Hack mode you mention?
There is no such mode on this integration...

**Comment by Spielkind88** [comment]
Isn't that your integration in Home Assistant?

![2022-11-02 08_53_52-Einstellungen – Home Assistant – Mozilla Firefox](https://user-images.githubusercontent.com/115810899/199432654-331eaf9d-c7eb-4a11-afaa-be512215f356.jpg)

**Comment by albertogeniola** [comment]
That is another integration.

**Comment by Spielkind88** [comment]
*Facepalm* I'm very sorry. Stupid me. Have a nice day anyway!
