### ISSUE TITLE
Garage Overtime Close issue

### ISSUE THREAD

**Issue by is-gj** [albertogeniola/meross-homeassistant#398]
Reproduction

1. Start closing garage door
2. Stop in a partially open position

Expected

Command to close is given.
Garage re-opens (since was previously closing)
Check for position occurs again
Garage closes
Check for position occurs again
Garage remains closed (correct position)

Actual

Command to close is given.
Garage re-opens (since was previously closing)

-- The system is currently re-opening our garage if we leave it slightly open, intentionally. 
Extra checks from the magnetic switch should be performed to ensure closing is complete, as it is sometimes resulting in the opposite effect desired.

**Comment by albertogeniola** [comment]
Hi @is-gj ,

Can you reproduce the same thing with the Meross App? Does the Meross app behave as expected or does it work as this integration does?
