### ISSUE TITLE
No Value (MSS310)

### ISSUE THREAD

**Issue by Nagi2626** [albertogeniola/meross-homeassistant#399]
After about 4 hours, no more values are transmitted. The value freezes at the last value.

**Comment by Teudimundo** [comment]
The same happens to me with a MTS200. 

this is the data from Meross IOT Cloud

<img width="536" alt="image" src="https://user-images.githubusercontent.com/662992/202006550-30b1733e-8167-45ce-9c8f-3dab24809e31.png">

and this is instead from HomeKit

<img width="546" alt="image" src="https://user-images.githubusercontent.com/662992/202006711-caaaa7c0-59dd-4118-a2d8-bf246301a00d.png">

**Comment by Teudimundo** [comment]
I think this might be a duplicate of #394

**Comment by albertogeniola** [comment]
Closing as @Teudimundo correctly pointed out, this is a duplicate of #394

**Comment by albertogeniola** [comment]
I am reopening this thread to tell you I cannot reproduce this issue on my systems (development environment and my personal HA). I've been using the v1.2.6 version for three days with and the MSS310 has been collecting meaningful data all the time. 

When you get the "frozen" values, are you able to interact with the device?

**Comment by Nerthur1978** [comment]
I have the same issue with Meross Cloud IoT. I have 4 meross mss310 (2 of them at home, in the same lan of the raspberry and the other 2 in another lan in another house). All of the mss310 after some hours working, get frozen.
I dont know how I can help  you to fix this issue, but ask me for any you need for this.

**Comment by Nagi2626** [comment]
It's the same with me. Last connection 2 days ago. And also not switchable.

**Comment by albertogeniola** [comment]
Seems related to #414 . Closing in favour of that.
