### ISSUE TITLE
MSS560 - Support confirmed

### ISSUE THREAD

**Issue by marcelsphone** [albertogeniola/meross-homeassistant#4]
MSS560 is confirmed working with this component

**Comment by albertogeniola** [comment]
Glad to hear thet.
Thank you for the feedback!

**Comment by allansantosh** [comment]
> MSS560 is confirmed working with this component

Currently I have the MSS560 showing up as a light switch only and no dimmer capability in HA. I cannot adjust the brightness up or down but I can turn on and off the light. Is this a known issue? Dimmer works in the Meross app
