### ISSUE TITLE
not ADD-ON installation ?

### ISSUE THREAD

**Issue by lejibxl** [albertogeniola/meross-homeassistant#410]
**Describe the bug**
the Add-on does not appear in the "Add-on Store" and it is impossible to add it via "Manage add-on repositories" because I think the "repository.yaml" file is missing at the root in the git repository.

**Your environment**
HomeAssistant version: 2022.12.3
Hassio Version (if applicable): 9.3
Hardware environment: ESX

**Logs taken when the issue happened**
```
--- PASTE LOGS HERE ---
```

**Comment by Joerchi** [comment]
Same here. The addon-on is not findable in Home Assistant using search.

**Comment by Joerchi** [comment]
Workaround: Screenshot 1 of 3: Install FTP add-on

![FTP1](https://user-images.githubusercontent.com/5272745/208313890-90d5aff0-40a7-4849-bb9b-1049943e2e8b.png)

**Comment by Joerchi** [comment]
Workaround: Screenshot 2 of 3: Configure FTP add-on: Enable file upload and set password, then save the changed configuration and restart the FTP add-on. 

![FTP2](https://user-images.githubusercontent.com/5272745/208313929-ba101b41-4007-4ba1-88ee-4fbcffc51aa9.png)

**Comment by Joerchi** [comment]
Workaround: Screenshot 3 of 3: Use any FTP software (in this example Filezilla under Windows 10) and upload the **meross_cloud** subfolder to the **custom_components** folder. After the successful FTP upload, restart Home Asisstant. 
![FTP3](https://user-images.githubusercontent.com/5272745/208314037-d062df08-cea1-4a16-870c-c66f20fe2e9f.png)

**Comment by albertogeniola** [comment]
Hi,
What URL are you using as addon-repository? It **MUST NOT** be  "https://github.com/albertogeniola/meross-homeassistant". Instead, it should be the following: `https://github.com/albertogeniola/ha-meross-local-broker`.

I've double checked and on the latter there is the `repository.yaml` file. 

Moreover, be advised that the installation instructions provided by @Joerchi only address the custom component installation, not the addon-installation. They are two different things. You can install the component via HACS or manually as reported by @Joerchi , while you must install the addon via the button reported into the README of [this repository](https://github.com/albertogeniola/ha-meross-local-broker).
