### ISSUE TITLE
MS100 Sensor not showing up as device or entitiy

### ISSUE THREAD

**Issue by us3d** [albertogeniola/meross-homeassistant#411]
The MS100 sensor is not showing up as device or entity. But in the log i see that this sensor is sending the information. 

> Logger: meross_iot.manager
> Source: runner.py:120
> First occurred: December 21, 2022 at 1:33:16 PM (73 occurrences)
> Last logged: 7:07:15 AM

> Uncaught push notification Namespace.HUB_SENSOR_TEMPHUM. Raw data: {"tempHum": [{"syncedTime": 1671771036, "sample": [[212, 500, 1671632395, 1671633448], [213, 520, 1671633448, 1671633550], [213, 540, 1671633550, 1671633652], [213, 560, 1671633652, 1671633788], [213, 580, 1671633788, 1671635163], [214, 600, 1671635163, 1671636418], [214, 620, 1671636418, 1671637996], [215, 640, 1671637996, 1671641606], [216, 620, 1671641606, 1671641725], [215, 600, 1671641725, 1671642165], [215, 580, 1671642165, 1671647862], [215, 600, 1671647862, 1671648370], [216, 620, 1671648370, 1671659775], [219, 610, 1671659775, 1671665209], [219, 590, 1671665209, 1671673899], [216, 610, 1671673899, 1671685391], [215, 590, 1671685391, 1671687426], [214, 570, 1671687426, 1671688359], [214, 550, 1671688359, 1671689818], [214, 570, 1671689818, 1671696297], [215, 590, 1671696297, 1671724555], [215, 570, 1671724555, 1671724606], [213, 550, 1671724606, 1671724657], [211, 530, 1671724657, 1671724725], [209, 510, 1671724725, 1671724826], [206, 500, 1671724826, 1671725218], [209, 520, 1671725218, 1671725778], [212, 520, 1671725778, 1671728392], [213, 540, 1671728392, 1671733191], [214, 520, 1671733191, 1671733361], [214, 540, 1671733361, 1671734005], [215, 560, 1671734005, 1671735090], [215, 580, 1671735090, 1671737734], [216, 600, 1671737734, 1671737937], [216, 620, 1671737937, 1671739666], [216, 640, 1671739666, 1671748985], [219, 630, 1671748985, 1671751525], [218, 610, 1671751525, 1671768051], [215, 610, 1671768051, 1671771036], [215, 590, 1671771036, -10000]], "latestTime": 1671771036, "latestTemperature": 215, "latestHumidity": 590, "id": "120027D29A05"}]}

How can i resolve this?

thx

**Comment by albertogeniola** [comment]
Hi,
can you please attach the logs shown by the library at boot? It looks like the SubDevice is not registered within the MerossIot registry. Have you tried to re-couple the MS100 with the HUB?
