### ISSUE TITLE
[MEROSS-API-CHANGED] Integration no longer loads - TypeError: HttpDeviceInfo.__init__()

### ISSUE THREAD

**Issue by Raul-7-7** [albertogeniola/meross-homeassistant#412]
**Describe the bug**
As of today (upgrading to 2022.12.9) the integration no logers loads with the error below. Tried restarting HA / reloading integration with no luck. 
**Your environment**
HomeAssistant version: -- Home Assistant 2022.12.9 --
Hassio Version (if applicable): -- Operating System 9.4 --
Hardware environment: -- Intel i7 (Ubuntu) --

**Logs taken when the issue happened**
```
Error occurred. ------------------------------------- Component version: 0.4.5.0 Device info: <Unavailable> Error Message: "An exception occurred while setting up the meross manager. Setup will be retried..."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/__init__.py", line 451, in async_setup_entry
    await meross_coordinator.initial_setup()
  File "/config/custom_components/meross_cloud/__init__.py", line 149, in initial_setup
    self._client, http_devices, creds_renewed = await get_or_renew_creds(
  File "/config/custom_components/meross_cloud/__init__.py", line 341, in get_or_renew_creds
    http_devices = await http_client.async_list_devices()
  File "/usr/local/lib/python3.10/site-packages/meross_iot/http_api.py", line 417, in async_list_devices
    return [HttpDeviceInfo.from_dict(x) for x in result]
  File "/usr/local/lib/python3.10/site-packages/meross_iot/http_api.py", line 417, in <listcomp>
    return [HttpDeviceInfo.from_dict(x) for x in result]
  File "/usr/local/lib/python3.10/site-packages/meross_iot/model/shared.py", line 27, in from_dict
    obj = cls(**new_dict)
TypeError: HttpDeviceInfo.__init__() missing 1 required positional argument: 'skill_number'
```

**Comment by chrsc59** [comment]
Same here, 
failed during the night (Europe), was working yesterday evening

**Comment by midadami** [comment]
Same, everything was working fine until few hours ago. Same error.

**Comment by dpacecca** [comment]
I also have the same error, lost connectivity around 2hrs ago.

**Comment by chrsc59** [comment]
restoring to core 2022.12.8 did not help, same error after HA reboot, or reload of the integration

**Comment by varactor** [comment]
Same issue here, it happened before any updates. Restarted HA, updated to latest core and still same issue.

Error same as original post.

Error Message: "An exception occurred while setting up the meross manager. Setup will be retried..."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/__init__.py", line 451, in async_setup_entry
    await meross_coordinator.initial_setup()
  File "/config/custom_components/meross_cloud/__init__.py", line 149, in initial_setup
    self._client, http_devices, creds_renewed = await get_or_renew_creds(
  File "/config/custom_components/meross_cloud/__init__.py", line 341, in get_or_renew_creds
    http_devices = await http_client.async_list_devices()
  File "/usr/local/lib/python3.10/site-packages/meross_iot/http_api.py", line 417, in async_list_devices
    return [HttpDeviceInfo.from_dict(x) for x in result]
  File "/usr/local/lib/python3.10/site-packages/meross_iot/http_api.py", line 417, in <listcomp>
    return [HttpDeviceInfo.from_dict(x) for x in result]
  File "/usr/local/lib/python3.10/site-packages/meross_iot/model/shared.py", line 27, in from_dict
    obj = cls(**new_dict)
TypeError: HttpDeviceInfo.__init__() missing 1 required positional argument: 'skill_number'

**Comment by dpacecca** [comment]
I reloaded the integration an that did not work, I think the API address is down, iot.meross.com

**Comment by chrsc59** [comment]
> I reloaded the integration an that did not work, I think the API address is down, iot.meross.com

I'm presuming it is not down as the Meross app can control the devices from te cloud

**Comment by Raul-7-7** [comment]
> 

yeah, also the devices work with Google Home so the API seems fine.

**Comment by Odinlistening** [comment]
Confirming same issue here. All fine yesterday evening - no updates or system changes.

**Comment by Raul-7-7** [comment]
Hmmm, since no change, then maybe Meross has changed something in the API payload?

**Comment by komima** [comment]
It may be the Meross api has changed, and no longer returns the `skill_number` field. Response is directly used to construct the device info class, and missing fields break the integration.

https://github.com/albertogeniola/MerossIot/blob/0.4.X.X/meross_iot/http_api.py#L439

For now I managed to resolve the issue by changing the `meross_iot` library `model/http/device.py` file manually (from homeassistant python environment, use `python -c "import meross_iot.model.http.device as d; print(d.__file__)` for file location), since that field seems not to be used anywhere important for homeassistant.

`# skill_number: str` ([for arg](https://github.com/albertogeniola/MerossIot/blob/0.4.X.X/meross_iot/model/http/device.py#L29))
`skill_number = "123"` ([for assignment](https://github.com/albertogeniola/MerossIot/blob/0.4.X.X/meross_iot/model/http/device.py#L64))

**Comment by albertogeniola** [comment]
Hi all,
yeah, Meross API changed. Tracking this issue [here](https://github.com/albertogeniola/MerossIot/issues/274)

**Comment by albertogeniola** [comment]
Hi all,
the [beta release](https://github.com/albertogeniola/meross-homeassistant/releases/tag/v1.2.7rc1) that addresses this issue is ready to be tested (the lower-level library has been released right away). **I need some volunteers** to test it and report back if that solves the issue. 

You can enable "beta releasaes" directly from HACS. You'll find a release named "Prerelease v1.2.7rc1": that is the one to be tested. Update your HA component, restart HA and please report back if that's working again. As soon as I get some confirmation, I'll proceed with producing the stable v1.2.7 release.

**Comment by nao-pon** [comment]
@albertogeniola Problem solved for me! thanks so much!

**Comment by tomrush** [comment]
@albertogeniola I have just updated and tested on my garage door opener. Everything looks to be working correctly on my simple setup. No errors or issues in the log.

Thanks for your prompt fix for this issue.

**Comment by merlin-zaraza** [comment]
@albertogeniola Works for me. Thanks!

**Comment by albertogeniola** [comment]
Thank you guys. I've released the v1.2.7 right away (it's exactly the same as 1.2.7rc1). 
We just need now to "spread the voice" to all people who are using this integration around the world.

I't just too bad Meross changes its API signature keeping the same api version number, which just break existing things. 
Also, this time we've been lucky: I'm currently on hollidays and I had my laptop with me, so I could fix this in a few hours.

**Comment by Odinlistening** [comment]
Thank you so much for incredible speed of response.

**Comment by chrsc59** [comment]
orking now, Thanks !

**Comment by Tristano67** [comment]
Hi ! I think it's my first comment on GitHub, but I really need to say THANK YOU !!!
I'm using your Meross integration and a lot of automations in my house, and you resolved this issue so fast ! 
**BRAVO @albertogeniola and all people who worked on it**

**Comment by Phishing-Fish** [comment]
Like what was previously stated, thank you so much for the quick response to address this issue. Your work is greatly appreciated.

**Comment by davecowell** [comment]
I am trying to update but HACS still shows 1.2.10 only and no update.

**Comment by jasonwitty** [comment]
> I am trying to update but HACS still shows 1.2.10 only and no update.

try this: https://github.com/albertogeniola/meross-homeassistant/issues/510
