### ISSUE TITLE
Setup failed

### ISSUE THREAD

**Issue by trytogetme85** [albertogeniola/meross-homeassistant#413]
**Describe the bug**
Since yesterday the installation seems corrupt, and reusing setup dont work
![image](https://user-images.githubusercontent.com/20819567/210621076-c075311f-d2da-4898-9fcc-23fab9b60f3d.png)

**Your environment**
HomeAssistant version: 2022.12.9
Hassio Version (if applicable):  9.4
Hardware environment: Raspy4//

**Comment by Quasaro** [comment]
Same error on my installation

**Comment by kwkid** [comment]
Ditto...the state of my integration has been Unavailable...the app version (eHomeLife on iOS) works just fine

**Comment by omega015** [comment]
Have you updated HACS Meross integration to v1.2.7 (Released 9 hours ago)? This resolved my issue.

**Comment by Quasaro** [comment]
> Have you updated HACS Meross integration to v1.2.7 (Released 9 hours ago)? This resolved my issue.

Confirmed working after the update to 1.2.7.
Thanks for swift response!

**Comment by kwkid** [comment]
Working....after update to 1.2.7

**Comment by TecnoTalarn** [comment]
I'm losing all meross integration this morning, but I'm having a lot of problems after upgrading to 1.2.7
It only sees the switch... no other options... mss310 doesn't see power sensors, no voltage.
temperature sensors do not work at all. I can't detect my msh300 hub.

![Screenshot 2023-01-04 at 20-41-13 Visualització principal – Home Assistant](https://user-images.githubusercontent.com/61935185/210636099-1ad986f0-a5fb-4a33-847d-be13101890e3.png)
![Screenshot 2023-01-04 at 20-42-07 Visualització principal – Home Assistant](https://user-images.githubusercontent.com/61935185/210636204-b9616ed6-c1ba-4b96-9ab6-b7632a1e233b.png)

**Comment by trytogetme85** [comment]
#Have you updated HACS Meross integration to v1.2.7 (Released 9 hours ago)? This resolved my issue.



> Have you updated HACS Meross integration to v1.2.7 (Released 9 hours ago)? This resolved my issue.

Thanks alot. Problem solved
