### ISSUE TITLE
MSG100 & MSS630 not working on v1.2.7 

### ISSUE THREAD

**Issue by colakang** [albertogeniola/meross-homeassistant#415]
MSG100 only device no entities.
![msg100](https://user-images.githubusercontent.com/17260007/210677258-86fe1ae1-c176-4c6b-85ef-678e4f93e17a.png)

MSS620 only one entities, Should be three entities.
![mss620](https://user-images.githubusercontent.com/17260007/210677261-09db8f02-8360-4c29-8bed-844d9d4801dd.png)

HomeAssistant version: -- 2022.10.5 --
Hassio Version (if applicable): -- 1.28.4 --
Hardware environment: 
  -- MSG100 3.5.0 / Firmware: 3.2.7 --
  -- MSS620 3.0.0 / Firmware: 3.1.7 --

**Comment by albertogeniola** [comment]
Hi,
which version of the Meross Integration are you using? Can you please upgrade to v1.2.8 and let me know if that solves the issue?

**Comment by colakang** [comment]
> Hi, which version of the Meross Integration are you using? Can you please upgrade to v1.2.8 and let me know if that solves the issue?

Thanks for reminding me.

v1.2.8 is working great.

😀😀

**Comment by albertogeniola** [comment]
Glad it helped!
