### ISSUE TITLE
[question] does this work with the merros smart power strips?

### ISSUE THREAD

**Issue by t3dium** [albertogeniola/meross-homeassistant#416]

**Comment by albertogeniola** [comment]
Hi! 
Yes it should. It mostly depends on the specific device. You should try and see if that works!

**Comment by blueferret** [comment]
Hi,

I thinks there has have been more changes to the Meross API - I have a Merros mss420f 4 outlet strip which used to work fine.  I have it available both through Alexa and the HA integration and it's stopped working in both. Looking in the logs I see:
Device Prodigy (20..................6) is online, but timeout occurred when fetching its abilities.

**Comment by albertogeniola** [comment]
Hi @blueferret ,
I am closing this issue as the original question was about a compatibility report. Please open a separate issue if still necessary and provide the necessary information (as logs/screenshots/etc) to help developers debug your issue.

Thanks!
