### ISSUE TITLE
Meross integration is not working again after upgrade to v.1.2.8

### ISSUE THREAD

**Issue by aperezva** [albertogeniola/meross-homeassistant#418]
**Describe the bug**

**Your environment**
Home Assistant 2023.1.2
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230104.0 - latest
Hardware environment: MinPC HASSIO

```

**Comment by albertogeniola** [comment]
Hi!
Can you please provide the logs you see ?
What is the meross device that is not working?
What functionality is affected?

**Comment by aperezva** [comment]
Sorry, I have removed LAn integration and installed again the cloud , and right now are working

**Comment by albertogeniola** [comment]
I'm glad you solved it!
