### ISSUE TITLE
Unable to import component: cannot import name 'TransportMode'

### ISSUE THREAD

**Issue by highlandtran** [albertogeniola/meross-homeassistant#419]
**Describe the bug**

**Your environment**
Home Assistant 2022.12.8
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest
Hardware environment: -- V1.2.8 --

**Logs taken when the issue happened**
```
Logger: homeassistant.setup
Source: setup.py:210
First occurred: 4:21:16 PM (1 occurrences)
Last logged: 4:21:16 PM

Setup failed for custom integration meross_cloud: Unable to import component: cannot import name 'TransportMode' from 'meross_iot.manager' (/usr/local/lib/python3.10/site-packages/meross_iot/manager.py)
```

**Comment by albertogeniola** [comment]
Hi!
This is strange. Can you please re-download the component via HACS and restart HomeAssistant? It sounds like HACS failed to download the right version of the code.

**Comment by highlandtran** [comment]
Hi I’ve been redownload and restart for over 3 times and result still the same

**Comment by albertogeniola** [comment]
HI @highlandtran ,
then, there must be something wrong in your setup. Probably some corrupted dependency or installation.
Here's what you should do.
1. Completely remove the integration via HACS
2. Restart HA
3. Using a SSH or FTP addon, make sure to delete the following folders:
    - /config/custom_components/meross_cloud
    - /usr/local/lib/python3.10/site-packages/meross_iot
4. Restart HA
5. Install the Meross Cloud integration again, via HACS

This should trigger the re-installation of the MerossIot component.

Let me know if this solves the issue.
