### ISSUE TITLE
Energy Dashboard Individual Device

### ISSUE THREAD

**Issue by matteusz88** [albertogeniola/meross-homeassistant#424]
Can the MS3310 plug socket be used with the “Individual Device Monitoring” feature of the Energy Dashboard?

**Comment by seiferrtalle** [comment]
Hello, that would be my question too.

**Comment by RaoulSargent** [comment]
Yes
HA > Settings > Dashboards > Energy > Individual Devices > Add Device
Then just pick the entity for the Meross MSS310 plug.

**Comment by seiferrtalle** [comment]
This is the problem and the background of the question - the entities for the Meross MSS310 plug (see screenshot) cannot be selected or added to the individual devices section in the configuration of the energy dashboard. They are not displayed there at all?
![2023-02-16 18_01_55-Einstellungen – Home Assistant – Mozilla Firefox](https://user-images.githubusercontent.com/68616885/219435994-3d93fab9-9f8f-4937-9aac-a496391f24fe.jpg)
