### ISSUE TITLE
Error Message: "Only one configuration of Meross is allowed.”

### ISSUE THREAD

**Issue by gianky69** [albertogeniola/meross-homeassistant#43]
I have 2 Home Assistant installations, 1 at home and another one at my holiday house. I have some Meross Switches at home and other 2 ah holiday house, they are all "registered" in Meross App (iOS) and perfectly working.
In both HA I get this error "Only one configuration of Meross is allowed."
But all works as it should.

**Comment by dodo1337** [comment]
@gianky69 
Hi, I had the same last month - it was because of having the integration doubled in "integrations" and within the configuration.yaml entry.
I deleted both and only added it again via the "integration" menu. after that it disappeared.

Best
 Dominik

**Comment by gianky69** [comment]
> @gianky69
> Hi, I had the same last month - it was because of having the integration doubled in "integrations" and within the configuration.yaml entry.
> I deleted both and only added it again via the "integration" menu. after that it disappeared.
> 
> Best
> Dominik

But I have no meross in configuration, other than user/pass

**Comment by dodo1337** [comment]
> > @gianky69
> > Hi, I had the same last month - it was because of having the integration doubled in "integrations" and within the configuration.yaml entry.
> > I deleted both and only added it again via the "integration" menu. after that it disappeared.
> > Best
> > Dominik
> 
> But I have no meross in configuration, other than user/pass

Having that in your config is a full setup because it connects to your account. 
To be 100% sure - you could go into the entities register and double check if there is still meross entities registered

**Comment by gianky69** [comment]
Ok. I’ll do it

**Comment by soberstadt** [comment]
I found that I had new entities named the same as my meross outlets but with `_2` added. I removed the integration from the "Integrations" list in HA and then renamed the new entities to their original names, and then I was good to go. 

Thanks for pointing this out!

**Comment by albertogeniola** [comment]
Glad you fixed! Thanks @dodo1337 for the help.
