### ISSUE TITLE
Unable to rename entities using local broker with Meross IoT integration

### ISSUE THREAD

**Issue by rcdailey** [albertogeniola/meross-homeassistant#431]
I have an entity named this:

```
cover.small_garage_door_opener_msg100_main_channel
```
I renamed it to:
```
cover.small_garage_door_opener
```
Now it shows up as "unavailable". When I reload the integration or restart HASS, now both show up!
![image](https://user-images.githubusercontent.com/1768054/222770003-1fcc3c9f-220b-40b8-96e9-14f2edac9c1e.png)

I'd like the ability to rename the entity. In addition, none of these entities have unique IDs so I'm not able to remove them. I do not know where to go to clean this up.

**Your environment**
HomeAssistant version: 2023.3.1
Hassio Version (if applicable):
Hardware environment: HASS OS in Proxmox

**Comment by TheHolyRoger** [comment]
I have the same issue although the entities come back after a restart.

**Comment by TheHolyRoger** [comment]
Also seems to resolve by reloading the integration. I see a bunch of log entries saying meross cloud doesn't generate unique id's, is that something to do with it maybe?
