### ISSUE TITLE
HomeKit Controller integration ?

### ISSUE THREAD

**Issue by zenzip** [albertogeniola/meross-homeassistant#435]
Just used to add my smart plugs to HA and work flawlessly, but I'm not able to find the way to include in the HomeKit Hub of HA.

**Comment by albertogeniola** [comment]
Hi @zenzip ,

I've just releaed a new beta version, v1.3.2beta1. This beta add support for the HK HUB version. 
Can you test it and provide feedback?

**Comment by zenzip** [comment]
Thanks for the effort. Seems to be working importing the plugs, able to on/off from HK. 
Not able to monitor the consumption, but maybe it's a limitation on HK itself.
