### ISSUE TITLE
state_class is not exposed

### ISSUE THREAD

**Issue by FluffyGhoster** [albertogeniola/meross-homeassistant#439]
**Describe the bug**
MSS310h does not seem to expose state_class.

This makes the usage of it into the Energy monitoring tab impossible.

The configurator says to redirect the integrator developer to: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Your environment**
HomeAssistant version: 2023.4.4
Hardware environment: ARM

**Comment by wanted156** [comment]
Same problem here. I am trying to integrate it with the energy panel, along with my PV system, but since the state_class is not exposed this is not possible. A fix would be great!

**Comment by benoitm974** [comment]
https://github.com/albertogeniola/meross-homeassistant/pull/460 switch was deprecated I pushed a new sensor for this which allow energy dashboard and sensor for each plug

**Comment by benoitm974** [comment]
![sources_energy](https://github.com/albertogeniola/meross-homeassistant/assets/1139277/8f440b9b-6f3a-4335-a3d0-6e8048ccd1f3)
![cafetiere](https://github.com/albertogeniola/meross-homeassistant/assets/1139277/e4f5a414-3ea5-4301-9cc0-d544bfd30934)

**Comment by benoitm974** [comment]
1.2.10 integrates power transmission can we close this issue ?

**Comment by albertogeniola** [comment]
Yup, closing!
