### ISSUE TITLE
MSS310 consumption does not appear

### ISSUE THREAD

**Issue by cnopix** [albertogeniola/meross-homeassistant#44]
Hi ,

i configure the add-on the switch for my 2 MSS310 work great but i don't see the consumption, only the switch.

i miss something ?

**Comment by dodo1337** [comment]
hi @cnopix 

Look at 
https://github.com/albertogeniola/meross-homeassistant/issues/40#issuecomment-581145258 

Best
  Dominik

**Comment by cnopix** [comment]
Strange, i change nothing and now i see the consumption.

So i closed the issue
