### ISSUE TITLE
Meross LAN and this integration can live on the same system?

### ISSUE THREAD

**Issue by cagnulein** [albertogeniola/meross-homeassistant#440]
I'm trying to setup this integration for a Meross thermostat but i see this

![image](https://user-images.githubusercontent.com/48216/232422029-7e3e7c45-ca09-459a-9ec0-94fa170d9c0b.png)

and nothing more in the integration. My doubt is the fact that maybe Meross LAN is conflicting with this integration? I would like to use Meross LAN for my Meros Power Outlet, and your integration for my Meross Thermostat. Is it possible?

**Your environment**
Home Assistant 2023.4.4
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230411.1 - latest

No logs from the system about errors

**Comment by albertogeniola** [comment]
Hi!
There should be no issue in having both integration working together, but I really discourage such approach. You'll end up handling double the entities and that is far from ideal. My suggestion is to rely only on a single integration for Meross device management.
