### ISSUE TITLE
Works for a while then stops

### ISSUE THREAD

**Issue by garethsnaim** [albertogeniola/meross-homeassistant#443]
**Describe the bug**
Hello. Sorry perhaps its not a bug but it has me perplexed. I have 14 meross home plugs around the house. When I installed this service they have all been found which is great. For about 10 minutes they work just fine through this service then at some point it randomly stops working. The only way to get it going again is to restart Home Assistant which is not ideal.

I have had it reliably going for more than an hour.

**Your environment**
HomeAssistant version: 2023.4.5
Hassio Version (if applicable): -- PLEASE SPECIFY -- I don't know what this is which perhaps does not bode well.
Hardware environment: 32 core server, 64 gigs ram running OpenMediaVault. Home assistant is Docker. from Docker IO
Its set to not rely on local HTTO and only ues web
It says custom HTTP user agent is MerossHA/1.2.8

**Logs taken when the issue happened**
```
I will try and get it to fail again whilst collecting logs.
```

**Comment by garethsnaim** [comment]
OK I turned on logging but have no idea where to find the logs

**Comment by sharkwsk** [comment]
Hi @garethsnaim, I also have similar issue of frequent disconnect and raised https://github.com/albertogeniola/meross-homeassistant/issues/441

You should be able turn on logs in HA configuration.yaml and then should see the logs in homeassistant.log file

Let me know if you able to find any progress
