### ISSUE TITLE
Migrating from eHomeLife to Refoss app

### ISSUE THREAD

**Issue by kwkid** [albertogeniola/meross-homeassistant#445]
Has anyone been able to use this integration after migrating from the eHomeLife app to the Refoss app. You need to re-authenticate your login within NA and it now gives "An unexpected error occurred"...Perhaps the HTTP API Endpoint has changed from https://iot.meross.com?

**Comment by msgroner** [comment]
I have the same experience. No solution yet.

**Comment by 946021** [comment]
same here

**Comment by Adam-Kay** [comment]
Bump. Also not working for me currently. Maybe there's a new API endpoint URL?

**Comment by HiroMT** [comment]
For anyone looking… Though not ideal. I was tired of this and reset the device and connected to meross and works like a charm with meross lan for HA

**Comment by prashker** [comment]
Sniffing some traffic on my Pi-Hole, seems like the new endpoint in Refoss version of the app is https://iotx-us.refoss.net

However when I try and login by specifying that endpoint I get: 

`2023-08-25 22:38:53.826 ERROR (MainThread) [meross_iot.http_api] Received non-ok API status code: CODE_WRONG_EMAIL. Failed request to API. Response was: {'apiStatus': 1008, 'sysStatus': 0, 'info': 'Email unregistered', 'timestamp': 1693017533, 'data': {}}`

**Comment by Christophe668** [comment]
I did the same as @HiroMT, Refoss and Meross ship the same hardware under a different company name.
The Refoss switch can therefore be paired to a Meross account via the Meross app and it works perfectly.
Confusing but working well 👌
