### ISSUE TITLE
Maybe issue with utility_meter and integration

### ISSUE THREAD

**Issue by SuperSpe** [albertogeniola/meross-homeassistant#45]
I wrtite here because I cannot figure out what I am doing wrong. 
I amusing 2 MS310 for metering the power costs.
HA is configured correctly with utility_meter and integration platform for converting the W power in Kwh, and passaed the created sensor to the utilty_meter.
The problem is that this thing does not work. The counter of the power is not in Kwh, so when I fire up a stove that consume 1 kwh for 10 seconds, the sensor got 1 kwh of power consumtion. This is not correct.
Since HA is ocnfigured correctly, I want to exclude that this component is all ok with this function. Any other experencie this problem or is getting the power consumtpion meter working properly?
Thanks

**Comment by albertogeniola** [comment]
Please update to the v1.0.0 and let me know if the problem persists.
