### ISSUE TITLE
Garage doors periodically become unavailable in new version

### ISSUE THREAD

**Issue by elijah286** [albertogeniola/meross-homeassistant#450]
I've been using this integration for local control of my garage doors and they've been rock solid. However, after a recent upgrade I've noticed that the doors periodically become unavailable. I have two doors and two merls controllers but they go offline asynchronously so it's not like it loses connection with a common service, just the individual nodes. Nothing about my network or the very close proximity to a WiFi AP has changed.

**Your environment**
Home Assistant 2023.6.3
Supervisor 2023.06.4
Operating System 10.3
Frontend 20230608.0 - latest
Home Assistant blue

**Logs taken when the issue happened**
```
--- PASTE LOGS HERE ---
Reload meross if devices become unavailable: Already running
5:49:40 AM – (WARNING) Automation - message first occurred at June 30, 2023 at 1:27:21 PM and shows up 54 times
MerossDevice(Garage Door Outside): incorrect timestamp: 5 seconds behind HA
4:54:54 AM – (WARNING) Meross LAN (custom integration) - message first occurred at June 30, 2023 at 2:24:15 PM and shows up 13 times
Error doing job: Task exception was never retrieved
4:49:30 AM – (ERROR) Meross LAN (custom integration) - message first occurred at 1:07:30 AM and shows up 2 times
MerossDevice(Garage Door Outside): incorrect timestamp: 15 seconds behind HA
4:49:30 AM – (WARNING) Meross LAN (custom integration) - message first occurred at June 30, 2023 at 10:56:52 PM and shows up 2 times

**Comment by TheOneOgre** [comment]
> I've been using this integration for local control of my garage doors and they've been rock solid. However, after a recent upgrade I've noticed that the doors periodically become unavailable. I have two doors and two merls controllers but they go offline asynchronously so it's not like it loses connection with a common service, just the individual nodes. Nothing about my network or the very close proximity to a WiFi AP has changed.
> 
> **Your environment** Home Assistant 2023.6.3 Supervisor 2023.06.4 Operating System 10.3 Frontend 20230608.0 - latest Home Assistant blue
> 
> **Logs taken when the issue happened**
> 
> ```
> --- PASTE LOGS HERE ---
> Reload meross if devices become unavailable: Already running
> 5:49:40 AM – (WARNING) Automation - message first occurred at June 30, 2023 at 1:27:21 PM and shows up 54 times
> MerossDevice(Garage Door Outside): incorrect timestamp: 5 seconds behind HA
> 4:54:54 AM – (WARNING) Meross LAN (custom integration) - message first occurred at June 30, 2023 at 2:24:15 PM and shows up 13 times
> Error doing job: Task exception was never retrieved
> 4:49:30 AM – (ERROR) Meross LAN (custom integration) - message first occurred at 1:07:30 AM and shows up 2 times
> MerossDevice(Garage Door Outside): incorrect timestamp: 15 seconds behind HA
> 4:49:30 AM – (WARNING) Meross LAN (custom integration) - message first occurred at June 30, 2023 at 10:56:52 PM and shows up 2 times
> ```

Based on your debug logs, seems like you're using the meross lan component rather than this iot one. If that's the case, you'll want to post under their issue tracker.
