### ISSUE TITLE
Cannot connect smart plug to Wi-Fi

### ISSUE THREAD

**Issue by 1Euro7Cent** [albertogeniola/meross-homeassistant#452]
**Describe the bug**
cannot connect to Wi-Fi. (password is correct)
![Screenshot_20230807-121823_Settings](https://github.com/albertogeniola/meross-homeassistant/assets/67194495/e2d38d22-c19b-4a65-9211-654048f21c59)

after a while this comes up
![Screenshot_20230807-122635_Settings](https://github.com/albertogeniola/meross-homeassistant/assets/67194495/d22b3946-5956-4c54-a4e9-4043593ab966)

**Your environment**
Home Assistant 2023.8.1
Supervisor 2023.07.1
Operating System 10.4
Frontend 20230802.0 - latest

Smart plug: MSS210W

**Logs taken when the issue happened**
```
NO LOG
```

**Comment by ianjs** [comment]
Do you have a VPN set up on your phone? I couldn't connect till I disabled this.

**Comment by albertogeniola** [comment]
Hi @1Euro7Cent ,

Please report this kind of issue in the dedicated repository for the [Meross Custom Pairer](https://github.com/albertogeniola/Custom-Meross-Pairer) app if still valid. This repository is about the Meross HomeAssistant component.
