### ISSUE TITLE
No entity with 20200206.1

### ISSUE THREAD

**Issue by gianky69** [albertogeniola/meross-homeassistant#46]
After last update via HACS, all entities greyed out. Back to  20200109.5 all working again...

**Comment by swampylee** [comment]
Same here

**Comment by albertogeniola** [comment]
Hi guys, I apologise for the inconvenience: the last release introduced a regression. I am currently working on a fix that will be hopefully be ready by this evening.

**Comment by albertogeniola** [comment]
Ho @gianky69 ,

I've released a new version:  20200209.1.
Can you test it and let me know if that works ?

**Comment by gianky69** [comment]
Updated to 20200209.1 but all entities grayed out. And getting this notice...

![immagine](https://user-images.githubusercontent.com/5670189/74131690-34951180-4be5-11ea-992b-e36fdd05678e.png)

**Comment by swampylee** [comment]
> Updated to 20200209.1 but all entities grayed out. And getting this notice...
> 
> ![immagine](https://user-images.githubusercontent.com/5670189/74131690-34951180-4be5-11ea-992b-e36fdd05678e.png)
> 
> Back to 20200109.5 all working
> 
> HA version 105.2, supervisor 200, system HassOS 3.9, 3 Meross MSS425e + 2 MSS310

Not sure if this will help but I was using a manual configuration and in the end I commented it out and added the integration through the UI. I then got all my devices back (with the caveat that some had new entity names that I had to change in lovelace). That was with 206.2 (not .1) and now everything seems ok again, even with the latest 209.1

**Comment by gianky69** [comment]
I've used integration to add Meross devices to HA since some versions ago...

**Comment by Aiace88** [comment]
ciao alberto, a me con l'ultima versione ora funziona perfettamente. grazie mille!

**Comment by Aiace88** [comment]
ho riscontrato una problematica nel caso della multipresa. se attivo una delle entità delle prese, il bottone generale non si aggiorna e rimane spenta. viceversa se accendo solamente la generale e non le singole uscite, rimangono tutte come spente
![2020-02-12 00_55_08-Home Assistant](https://user-images.githubusercontent.com/35429685/74290563-85fee700-4d32-11ea-9d93-d912c6373e6e.jpg)

**Comment by albertogeniola** [comment]
Hi Aiace,
Please open a new issue for that.

**Comment by gianky69** [comment]
Today I have done a complete uninstall/reinstall of Meross Cloud IoT... now it seems working... mah!?

**Comment by Schmedu** [comment]
I had to reinstall the component multiple times during the last days to overcome the unavailable status. I know it’s not pretty but does some know how to write a script to automatically reinstall the component & restart hassio?

**Comment by albertogeniola** [comment]
Hi all,
I've just released a new version of this component which should address the issues that have arose with the latest changes. Would you please update it and confirm it's now working as expected?

**Comment by gianky69** [comment]
> Hi all,
> I've just released a new version of this component which should address the issues that have arose with the latest changes. Would you please update it and confirm it's now working as expected?

Installed. Now working, but let some days pass...

**Comment by Gobolin80** [comment]
> Hi all,
> I've just released a new version of this component which should address the issues that have arose with the latest changes. Would you please update it and confirm it's now working as expected?

Hi Alberto,
thanks for your work.
After update I recive this error when I change preset mode: 
```
A timeout exception occurred while executing function <function ValveEntityWrapper.set_preset_mode at 0xb1402e40>  Hold on, Home Assistant is now restarting.
OK  
Connessione persa. Riconnessione...
```

**Comment by albertogeniola** [comment]
Hi @Gobolin80 , it's a known bug (#47 ). Will be fixed in the next release.

**Comment by swampylee** [comment]
All looks good to me. Thanks for all your work on this.

**Comment by albertogeniola** [comment]
Closing. In case the problem persists, please reopen the issue or start a new one.

**Comment by Schmedu** [comment]
Thanks for your help. Unfortunately, the switches don't react after one day and I still need to reinstall the component then 😅 Although they don't show any longer "unavailable", they just don't react. I think I'll buy me some tasmota switches and get rid of Meross

**Comment by albertogeniola** [comment]
> Thanks for your help. Unfortunately, the switches don't react after one day and I still need to reinstall the component then  Although they don't show any longer "unavailable", they just don't react. I think I'll buy me some tasmota switches and get rid of Meross

Do the switches react if you use the App?
Can you provide Homeassustant logs?

How about other people? Are you experiencing the issue or is everything okay?

**Comment by gianky69** [comment]
Same trouble for me (it also hanged with latest 20200209.1 but worked with 20200109.5), Meross switches stop responding in HA but work with Meross App on iPhone. My log is attached.
The error related to Meross is: 
`2020-02-18 07:48:12 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1251, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 198, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 356, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 384, in _handle_service_platform_call
    result = await result
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 609, in async_turn_off
    await self.hass.async_add_job(ft.partial(self.turn_off, **kwargs))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/meross_cloud/switch.py", line 80, in turn_off
    self._device.turn_off_channel(self._channel_id)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 162, in turn_off_channel
    return self._channel_control_impl(c, 0, callback=callback)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 35, in _channel_control_impl
    return self._togglex(channel, status, callback=callback)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 29, in _togglex
    return self.execute_command("SET", TOGGLEX, payload, callback=callback)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 126, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 302, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10`

[home-assistant.zip](https://github.com/albertogeniola/meross-homeassistant/files/4217817/home-assistant.zip)
