### ISSUE TITLE
Meross Integration not shown in HACS

### ISSUE THREAD

**Issue by pc-bastler** [albertogeniola/meross-homeassistant#463]
**Describe the bug**
I am trying to install the Integration to my Home Assistant but it is not found in HACS (V 1.33.0).
I am not firm enough to try a manual installation.

**Your environment**
HomeAssistant version: 2023.10.1
Hassio Version (if applicable): 10.5
Hardware environment: Raspberry PI 3B+ connected via LAN.

![Bildschirmfoto 2023-10-08 um 19 14 28](https://github.com/albertogeniola/meross-homeassistant/assets/46841479/4f950797-c283-4777-b65a-97003671ea5e)

**Comment by albertogeniola** [comment]
Closing as no feedback has been provided. Feel free to open it back if needed.
