### ISSUE TITLE
ATTENTION: Service Termination of Your meross App device control due to Security Concerns

### ISSUE THREAD

**Issue by joewong123321** [albertogeniola/meross-homeassistant#464]
I have just received an email from the Meross team, as below:

> Dear Customer,
> 
> This is meross cloud security team contacting you.
> 
> Recently our cloud security system has noticed that your devices are communicating with the could server at an extremely high frequency. We consider these behaviours abnormal and are concerned about the security of your devices.
> 
> Due to the security concerns and the intent to avoid any further potential damage, we will terminate the cloud services of these devices for now to protect your devices.
> 
> If you are sure that your devices are safe, NOT hacked, and are performing as expected. Please first lower your periodic request rate to no more than one message every ten seconds and then send an email to <[support@meross.com](mailto:support@meross.com)>. We will resume cloud service for you within 24 hours.
> 
> For the safety of your device and personal data, we suggest you to use meross app to manage your devices and DO NOT use any other third-party platforms. Please note that any abnormal high cloud request frequency will cause cloud service termination again.
> 
> Should you have any information you would like to provide us with or you would like to offer us any clarification, please contact us within 24 hours.
> 
> Thanks!
>
> Meross Cloud Security Team

Do I using the integration wrongly?

**Your environment**
HomeAssistant version: -- 2023.10.1 --

**Comment by hardysim** [comment]
I got the same message, how did you resolver it?

**Comment by joewong123321** [comment]
Finally I turn to Local based meross home assistant control
