### ISSUE TITLE
Invalid state at HA startup

### ISSUE THREAD

**Issue by bpolaszek** [albertogeniola/meross-homeassistant#466]
Hello there, 

I own a Meross [MRS100 roller shutter](https://www.meross.com/en-gc/smart-switch/wifi-shutter/91), but every time I restart HA, it systematically appears as open although it's closed. Clicking on the down button in HA (or in the Meross app) when it's already closed changes its state to _closing_, then _open_ again. To solve the issue I have to open the shutter for real (via Meross app or physically hitting the up button) then close it - and the state becomes correct, until I restart Home Assistant and it will appear as open again.

Thank you,
Ben

**Your environment**
HomeAssistant version: 2023.10.1
Hardware environment: Rpi OS + Docker

**Comment by cyrillus2** [comment]
hi
same issue here with same device and HA version  and plugin

**Comment by albertogeniola** [comment]
Hi! 
The latest versions of the integration should have solved this issue. could you please check that and report if the error still occurs?

**Comment by albertogeniola** [comment]
Closing as no feedback has been received. Please feel free to re-open if still needed.
