### ISSUE TITLE
Don't install this update

### ISSUE THREAD

**Issue by boehser-enkel** [albertogeniola/meross-homeassistant#474]
So there is an update but i must not install it? I also can't hide it...

`This version is not compatible with LOCAL-ONLY-ADDON. Do not upgrade if you use the integration with the meross local addon.`

What to do?

**Comment by albertogeniola** [comment]
It simply says you should not install that update if you are planning to use the local-only-addon. If you are not using that addon, you can proceed with the upgrade.
