### ISSUE TITLE
Sensor logger verbosity

### ISSUE THREAD

**Issue by thkrmr** [albertogeniola/meross-homeassistant#481]
Hi! 

My HA logs are full of entires like:
> 2024-01-05 16:18:06.668 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device TV (mss310) power W - Main channel
> 2024-01-05 16:18:06.671 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device TV (mss310) voltage V - Main channel
> 2024-01-05 16:18:07.765 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device TV (mss310) energy kWh - Main channel

I see in sensor.py:
One instance it's a debug log ` _LOGGER.debug(f"Refreshing instant metrics for device {self.name}")`, but int 3 other places it's `_LOGGER.info(f"Refreshing instant metrics for device {self.name}")` at info level logger. 

Is the level of verbosity at INFO necessary for the refreshing? Should it be debug instead?

**Comment by albertogeniola** [comment]
Hi @thkrmr ,

this has been just implemented in v1.3.1. 

Thanks a lot for the heads-up!
