### ISSUE TITLE
Internal LED control

### ISSUE THREAD

**Issue by Blacksimo** [albertogeniola/meross-homeassistant#483]
I would like to switch on/off the internal led of a meross wall switch

**Comment by albertogeniola** [comment]
Hi @Blacksimo , thanks for the request. 
As per now, this should be doable for all the devices that expose the namespace "DND" (Do Not Disturb). 

I'll try to find some time to implement this in the few next months.

**Comment by albertogeniola** [comment]
Hi @Blacksimo ,

this has been implemented in v1.3.1. You should find a number of switches called do-not-disturb. Can you please try and report your feedback?

Thanks!
