### ISSUE TITLE
Deprecation of HVAC_MODE_COOL --> Use HVACMode.COOL instead

### ISSUE THREAD

**Issue by zenkraker** [albertogeniola/meross-homeassistant#485]
In the logs of HomeAssistant I found this deprecation error: [homeassistant.components.climate.const] HVAC_MODE_COOL was used from meross_cloud, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.COOL instead, please create a bug report at https://github.com/albertogeniola/meross-homeassistant

**Comment by Sch3ssi** [comment]
I've got a similiar Problem.
I can't set havac Auto in ha  meross anymore.
IT worked since some Updates ago

**Comment by albertogeniola** [comment]
Fixed in version 1.2.12
