### ISSUE TITLE
Validation of translation placeholders for localized (it) string component.meross_lan.issues.cloud_token_expired.fix_flow.step.profile.description failed

### ISSUE THREAD

**Issue by micium** [albertogeniola/meross-homeassistant#492]
Registratore: homeassistant.helpers.translation
Fonte: helpers/translation.py:345
Prima occorrenza: 15:36:36 (1 occorrenze)
Ultima registrazione: 15:36:36

Validation of translation placeholders for localized (it) string component.meross_lan.issues.cloud_token_expired.fix_flow.step.profile.description failed

**Your environment**
HomeAssistant version: 2023.3.0
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: RPI 4

**Comment by albertogeniola** [comment]
Hi @micium ,

this issue refers to another component called "meross_lan". Please open the issue on the [corresponding repository](https://github.com/krahabb/meross_lan).
