### ISSUE TITLE
"Closing" and "Opening" state feedback

### ISSUE THREAD

**Issue by cliffjao** [albertogeniola/meross-homeassistant#493]
After tapping on the button in Home Assistant, it doesn't change to an intermediate "Closing" or "Opening" state, so sometimes it's hard to know whether the button press was actually registered. It would be great to add in this intermediate state for feedback.

**Comment by mekeppler** [comment]
+1

Agree - would be an excellent addition

**Comment by albertogeniola** [comment]
Hi!
May I ask to which device are you referring? Garage opener? Roller Shutter?

**Comment by cliffjao** [comment]
> Hi! May I ask to which device are you referring? Garage opener? Roller Shutter?

Garage opener for me

**Comment by albertogeniola** [comment]
Hi @cliffjao ,

I've just released version v.1.3.1 which implements the OPENING and CLOSING states. Can you please test them and post your feedback?

Thanks!

**Comment by cliffjao** [comment]
> Hi @cliffjao ,
> 
> I've just released version v.1.3.1 which implements the OPENING and CLOSING states. Can you please test them and post your feedback?
> 
> Thanks!

Just did a quick test on my end and confirmed that ir works as expected. Thank you!

**Comment by albertogeniola** [comment]
Glad it worked!
