### ISSUE TITLE
BUG: Duplicate "do_not_disturb" entities 

### ISSUE THREAD

**Issue by moebis** [albertogeniola/meross-homeassistant#498]
After updating to v 1.3.1 (not sure why it's installing a pre-release), but now all of my Meross devices have a duplicate entity with "do_not_disturb" named at the end, that do nothing. They show up everywhere, clicking them does nothing. The normal named devices are fine and turn on and off. I've tried to manually remove them from "core.entity_registry" and purge entities in the developer tools, but they keep coming back. How can I get rid of these?

**Comment by calexandre** [comment]
I have the same issue. Also using `1.3.1`

**Comment by albertogeniola** [comment]
That's intended behavior. The DND switch commands the "do-not-disturb-led" on the switches. It's like the "LED" option you find on the APP. If you want to disable/hide them, you can do it via HA
