### ISSUE TITLE
Event is not serializable

### ISSUE THREAD

**Issue by soberstadt** [albertogeniola/meross-homeassistant#5]
I installed your component today and it gave me this warning on first startup:
>Log Details (WARNING)
Fri Jun 28 2019 00:07:31 GMT-0400 (Eastern Daylight Time)
Event is not JSON serializable: <Event platform_discovered[L]: service=load_platform.switch, platform=meross_cloud, discovered=None: meross 1 (mss110, HW 1.0.0, FW 1.1.16): 
Channels: 0 = OFF>

It found the two devices on the network and registered them, but I don't know what this error means.

**Comment by albertogeniola** [comment]
Fixed by 018d60422ba6b6d99437bee87a8880132bf7550f
Can you confirm?

**Comment by v-marinkov** [comment]
It's gone for me. Thanks!

**Comment by daniel-stockhausen** [comment]
I got two of those `not JSON serializable` errors:

> Event is not JSON serializable: <Event platform_discovered[L]: service=load_platform.**sensor**, platform=meross_cloud, discovered=None: Washing machine (mss310, HW 1.0.0, FW 1.1.18): 
> Channels: 0 = OFF>

> Event is not JSON serializable: <Event platform_discovered[L]: service=load_platform.**switch**, platform=meross_cloud, discovered=None: Washing machine (mss310, HW 1.0.0, FW 1.1.18): 
> Channels: 0 = OFF>

It's one smart plug and it seems to be working just fine with your custom component - only those two errors show up in the log at every restart

Thanks for making this component btw :)

**Comment by daniel-stockhausen** [comment]
Sorry, my fault - I thought I was using the latest version of your component, but somehow HACS did actually use an older version. I reinstalled it (over hacs) and it's the latest version now and seems to be working without producing those warnings :)
