### ISSUE TITLE
Current and voltage values meross mss310 to Grafana

### ISSUE THREAD

**Issue by enrutador** [albertogeniola/meross-homeassistant#52]
Hi Alberto
Fantastic job. I'm testing the hassio pluguin. I observe the Power data correctly in hassio and in the Grafana instance. But we need monitor Current and Voltage too.

I have two questions:

1) Is it possible to also graph the current and voltage of the sensor?

2) I have an external current meter and the external meter and meross data differ greatly. You think it could be from my meter or the formula used in the script.

Thanks for your time & Work

**Comment by SuperSpe** [comment]
I notice that too.The power consumption in the plugin is not correctly calculated.
I opened an issue but without response.

**Comment by enrutador** [comment]
> I notice that too.The power consumption in the plugin is not correctly calculated.
> I opened an issue but without response.

Hi SuperSpe

It is practically double the value it sends you. I think the problem is not the formula, I think it is possible that it is the device.
I have solved it in the sensor.py (line 127) file:


        data = sensor_data.get('power')
        if data is not None:
           data = str(float(data*2)/1000)
        return data
