### ISSUE TITLE
Support for sensor MS100 (Temperature / Humidity)

### ISSUE THREAD

**Issue by stefano-orlandini** [albertogeniola/meross-homeassistant#57]
Hello,
it seems that the component does not support the MS100 sensors (Temperature and humidity in radio frequency through the hub)

I installed the library and tried the sample script and I see the sensors correctly (I have four)

I took a look at the component code and if I understand correctly the management of these sensors is missing

Is the integration of these sensors planned?

Thank you

**Comment by pavel-vrba1** [comment]
Hi,
I am also missing support for the temperature and humidity sensor MS100, which is integrated through the Meross Smart Hub (https://amzn.to/3ay6Q8Y).

I would really appreciate adding the support for it. Thx :-)

**Comment by albertogeniola** [comment]
Hi guys, 
unfortunately, I have no meross smart temeprature sensor in my test setup, so it's hard for me to provide an implementation for that. As soon as I get one I'll implement the needed HA wrappers.

**Comment by Ninescita** [comment]
You can enter your data in this Meross webpage and they will send you the product. They sent it to me to Spain... https://www.meross.com/free/products

**Comment by destaben** [comment]
I also need support for MS100, can I help you @albertogeniola? I have one here to do tests if it's needed.

**Comment by albertogeniola** [comment]
Implemented with the latest version of the component!
Please update to the latest version (v1.0.0) and follow update instructions [here](https://github.com/albertogeniola/meross-homeassistant#updating-from-legacy-versions).

**Comment by pavel-vrba1** [comment]
Hi Alberto,

I confirm the humidit and temperature sensor works well in the latest version. Many thanks. Pavel

**Comment by Ninescita** [comment]
Thank you, it works very well
