### ISSUE TITLE
MSS420F - Smart Wi-Fi strip becoming unavailable

### ISSUE THREAD

**Issue by PabloTheNinja** [albertogeniola/meross-homeassistant#58]
I have 2 Meross MSS420F multi strips 1 has automation to switch one socket on and then off some hrs later no automation on the other as yet. Both devices show as availalable for some hrs with one becoming unavailable and the other also going unavailable a short time later; both unavailable for circa an hour and a half and with no intervention available again.

The log:

2020-03-23 10:32:03 ERROR (Thread-5) [meross.connection] Failed to process message.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 273, in _on_message
    self._push_message_callback(message, from_myself=from_myself)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 162, in _dispatch_push_notification
    device.handle_push_notification(namespace, payload, from_myself=from_myself)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 70, in handle_push_notification
    l.error("Unknown online status has been reported from the device: %d" % status)
TypeError: %d format: a number is required, not str

Both units have IP address assigned in the router and are connected with no issues on any other device.

![meross](https://user-images.githubusercontent.com/23261530/77311708-88247000-6cf8-11ea-80d4-45ce40f2785b.png)

**Comment by wduderude** [comment]
> I have 2 Meross MSS420F multi strips 1 has automation to switch one socket on and then off some hrs later no automation on the other as yet. Both devices show as availalable for some hrs with one becoming unavailable and the other also going unavailable a short time later; both unavailable for circa an hour and a half and with no intervention available again.
> 
> 
> 
> The log:
> 
> 
> 
> 2020-03-23 10:32:03 ERROR (Thread-5) [meross.connection] Failed to process message.
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 273, in _on_message
> 
>     self._push_message_callback(message, from_myself=from_myself)
> 
>   File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 162, in _dispatch_push_notification
> 
>     device.handle_push_notification(namespace, payload, from_myself=from_myself)
> 
>   File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 70, in handle_push_notification
> 
>     l.error("Unknown online status has been reported from the device: %d" % status)
> 
> TypeError: %d format: a number is required, not str
> 
> 
> 
> Both units have IP address assigned in the router and are connected with no issues on any other device.
> 
> 
> 
> ![meross](https://user-images.githubusercontent.com/23261530/77311708-88247000-6cf8-11ea-80d4-45ce40f2785b.png)
> 
> 
> 
>

**Comment by wduderude** [comment]
> I have 2 Meross MSS420F multi strips 1 has automation to switch one socket on and then off some hrs later no automation on the other as yet. Both devices show as availalable for some hrs with one becoming unavailable and the other also going unavailable a short time later; both unavailable for circa an hour and a half and with no intervention available again.
> 
> 
> 
> The log:
> 
> 
> 
> 2020-03-23 10:32:03 ERROR (Thread-5) [meross.connection] Failed to process message.
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 273, in _on_message
> 
>     self._push_message_callback(message, from_myself=from_myself)
> 
>   File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 162, in _dispatch_push_notification
> 
>     device.handle_push_notification(namespace, payload, from_myself=from_myself)
> 
>   File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 70, in handle_push_notification
> 
>     l.error("Unknown online status has been reported from the device: %d" % status)
> 
> TypeError: %d format: a number is required, not str
> 
> 
> 
> Both units have IP address assigned in the router and are connected with no issues on any other device.
> 
> 
> 
> ![meross](https://user-images.githubusercontent.com/23261530/77311708-88247000-6cf8-11ea-80d4-45ce40f2785b.png)
> 
> 
> 
>

**Comment by PabloTheNinja** [comment]
This issue has been fixed and not related to the component, 
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache,
Locate the Start registry key and change its value from 4 (Disabled) to 2 (Automatic)
