### ISSUE TITLE
View voltage and current as sensor

### ISSUE THREAD

**Issue by Foglix** [albertogeniola/meross-homeassistant#59]
Hi,
in the past, before HACS and Meross_Cloud, I had install manually the following in my configuration.yaml:

"meross:
  username: xxx
  password: xxx
  scan_interval: 10
  meross_devices_scan_interval: 900
"

this showed me a lot of problem like abnormal restart of hassio and so on but I liked it because I could create some card that contain also voltage and current:
![Meross_OLD](https://user-images.githubusercontent.com/62595117/78561126-7cb46700-7817-11ea-8d34-541681f75536.png)

Can I do the same with new package? Seems I can see voltage and power but only if I open the card

**Comment by albertogeniola** [comment]
Hi @Foglix ,

the integration you are referring to is an old one. Some devices, as MSS310 should provide power/voltage/current meterings out of the box.
