### ISSUE TITLE
When using Home assistant to open/close garage door, status is incorrect

### ISSUE THREAD

**Issue by beone0088** [albertogeniola/meross-homeassistant#6]
I use an automation to open the garage door when I arrive home. The status turns to 'opening' and never switches to 'open'. When I manually push the wall button to close the garage door it still stays as 'opening'. When in Home Assistant and I push the down arrow button on the garage entity, it switches to 'closing', but never switches to 'closed'.  Only after rebooting Home  Assistant does the status change to 'closed'. If I use the Meross app or I use the original remotes to open/close the door, the status is updated correctly to 'open' or 'closed' that is if HA has not been used at any point.  But when using Home assistant to control the garage door either through an automation or script, the status does not update correctly and as such any subsequent automation does not work until HA has been rebooted. Since it seems to think the door is in the process of transition?

![merossOpening](https://user-images.githubusercontent.com/44935700/60391264-cf563b00-9aaf-11e9-8914-d7643de96e34.png)

**Comment by albertogeniola** [comment]
Hi @beone0088 and thank you for taking the time to report this issue. 
Indeed, there was a nasty misalignment between the device state and the meross custom component. 
I've just fixed the error and released a new version of the component. If you've hacs, you should be able to upgrade it directly from there. Otherwise, just install the latest version you find on this repository.

I'd ask you to repeat the tests with the newer version of this component and report back here the outcome of the test.

Thank you,
Alberto.

**Comment by beone0088** [comment]
The automation and scripts are now updating the status correctly. The only issue is when HA is rebooted, the status is 'open' even though the door is closed. 

Thanks for the quick turn around, Donna

**Comment by albertogeniola** [comment]
Hi @beone0088 ,

you're absolutely right. I've fixed the error ad updated the code. Try it now and let me know if your automation works as expected. Thank you again for your precious contribution!

**Comment by beone0088** [comment]
Status is now correct on reboot and automations are working. Thanks!

**Comment by albertogeniola** [comment]
Glad to hear that. Thanks!

**Comment by jdeaton83** [comment]
I see this is an older thread but I am experiencing the same thing. When I open or close the garage with the wall button, remote or homelink the status does not change on HA which in turn does not allow my automation to work properly. is there a correction for this?
