### ISSUE TITLE
Garage Cover state only "Opening" or "Closing" but never "Open" or "Closed"

### ISSUE THREAD

**Issue by Skyhog** [albertogeniola/meross-homeassistant#63]
If I trigger Open or Close actions from the Meross app, the state immediately changes to Open when the sensor breaks contact, and stays that way until the garage is completely closed again and the contact is intact.

Up until recently, this integration did the same thing, so I had a workaround to impute status.  That broke today, but while troubleshooting, I learned that the status is now only showing "Closing" or "Opening" but never switches to "open" or "closed."  I can build a workaround to that too, but in looking at the code, it looks like you're trying to impute the interim values as well, but it is not working.

Not sure what additional details you need to track it down, but I'd love to help you test this if you're working on it.

**Comment by Florian-Schmidt** [comment]
Same for me as I changed to 20200419.2 this morning because of another issue when updating to newest firmware.

I just saw that there's an issue for beta testers wanted for dev branch and test's are actually running. Perhaps the newest release fixes this issue (didn't compare dev yet)

Actually HA stays in closing:
![IMG_4527](https://user-images.githubusercontent.com/62351739/79789991-5af4cd00-834b-11ea-8905-210554a5fce8.jpeg)

In earlier version closing state didn't appear but open/closed were correct.

**Comment by Florian-Schmidt** [comment]
I just tried developer's beta version and my garage door works with that version. The cover state still stays in closing/opening. I think the moving stages are important to see if HA regonized pushing the button.

As a workaround I just created an automation triggered after specific delay when cover stays in one of these moving states.

Trigger actions:
![IMG_4529](https://user-images.githubusercontent.com/62351739/79906534-3f0b2d00-8418-11ea-88d7-e07e126a61a4.jpeg)

Action:
![IMG_4530](https://user-images.githubusercontent.com/62351739/79906597-6235dc80-8418-11ea-87d8-2a3c2d69501e.jpeg)

Actually enough for me to see my garage door's actual state.

**Comment by tek0011** [comment]
Same issue here.  Get stuck in Closing/Opening state basically forever.

**Comment by xalex75** [comment]
Hi. Same proble here, started few versions ago.
I f I open using meross app or garage remote, everything ok.
If I open it using HA, manuallyu or using an automation, status gets stuck to opening or closing, my automations stop working (because of this "middle" states) and many times I can't control it anymore from HA, I must use meross app.
When it's stuck in opening or closing, rebooting HA switches the state back to open or closed.
It' like this since about 2 months, I hope it will get fixed...

**Comment by Florian-Schmidt** [comment]
@xalex75 You‘re welcome! Just let me know if you need more details or it‘s not working for you. Actually in my case it works perfect.

**Comment by xalex75** [comment]
> @xalex75 You‘re welcome! Just let me know if you need more details or it‘s not working for you. Actually in my case it works perfect.

It's quite a simple automation, but it looks like I can't intercept the state.
Since at the moment my door is actually in "opening" state, I added a pattern automation:

> - alias: reset_state
    trigger:
      platform: time_pattern
      minutes: '/01'
      seconds: 00
    condition:
      - condition: state
        entity_id: cover.portone_box
        state: opening
      - condition: state
        entity_id: cover.portone_box
        state: closing
    action:
      - service: homeassistant.update_entity
        data:
          entity_id: cover.portone_box
      
But the state stays on "opening".
I also tried to put opening and closing into '' ('opening' and 'closing')

**Comment by Florian-Schmidt** [comment]
Yes, it‘s an easy automation. 😂

Which states are present in which situation of your door?

During the last days I saw that my door changed to „moving“ as it reached physical closed state.

**Comment by xalex75** [comment]
![image](https://user-images.githubusercontent.com/52346449/81505562-64d97280-92f0-11ea-9dad-8e4624c883e6.png)

I can't understand why it does not change

**Comment by Florian-Schmidt** [comment]
When you close the door it also stay‘s in opening!?

**Comment by xalex75** [comment]
It changes to closing.
I only saw:
-open
-closed
-opening
-closing

**Comment by Florian-Schmidt** [comment]
I‘m confused... If you can see closed/open in correct physical situation, everything would be fine.

This issue concerns that door stay in opening/closing. My automation checks for this situation for an existing time period over 1 minute and „corrects“ to closed/open to show correct icons.

Perhaps you need to achieve a necessary state manually?

**Comment by xalex75** [comment]
I tried to open and close it manually, your automations work perfectly.
Mine doesn't but it should not be needed normally, so it doesn't care.
Thanks again for your idea while waiting official fix, it will make my smart life easier :-)

**Comment by Florian-Schmidt** [comment]
Stupid question: Your automation works with only one of the conditions?

I've got some strange situations with combination of and/or conditions during the last weeks and then switched to templates as workaround. For your automation I would expect that this will behave as an "or" conditions but I'm unsure at the moment.

**Comment by Skyhog** [comment]
So, here's where I discovered the issue.  If I use the Merosd App, the
state of the sensor goes from Closed to Open immediately. When closing, it
stays open until it has closed, then changes to closed.  There is no
reported interim state.

In Home Assistant using this plugin, it goes from Closed to Opening and
stays in opening forever. When closing, it goes to closing immediately and
does not become "closed" even when it has closed. To fix it I can either
manually set the state or go and press the physical button on the garage
which correctly sets the state.

I have worked around this in my automation by using a python script to
change the state.  When closed, I set the state to "open" when contact is
broken and leave it there.  When open and a closed signal is received, I
temporarily set the state to closed immediately, then set it back to open
until the state updates normally because the contact of the sensor closed
again. (This is a work around to make it work in Google assistant because
the state of "opening" and "closing" confuses Google).

It works.  But I have to check it Everytime there is an update because my
work around is easily broken.

**Comment by Florian-Schmidt** [comment]
> So, here's where I discovered the issue.  If I use the Merosd App, the
state of the sensor goes from Closed to Open immediately. When closing, it
stays open until it has closed, then changes to closed.  There is no
reported interim state

My Meross (eHomeLife) App shows an animated icon which should simulate a moving door. Seems as there's an interim state existing. I guess final closed and opened states are measured by magnetic contacts only.

> In Home Assistant using this plugin, it goes from Closed to Opening and
stays in opening forever. When closing, it goes to closing immediately and
does not become "closed" even when it has closed. To fix it I can either
manually set the state or go and press the physical button on the garage
which correctly sets the state

This is what I expected since updating to newer versions (when you opened the issue). During last days I had the impression that "moving" state has been set when door achieved final state (open/closed). Tomorrow I could test this again.

However, it would be great to have a fix in HA.

**Comment by xalex75** [comment]
> Stupid question: Your automation works with only one of the conditions?
> 
> I've got some strange situations with combination of and/or conditions during the last weeks and then switched to templates as workaround. For your automation I would expect that this will behave as an "and" conditions but I'm unsure at the moment.

Ok, I feel stupid, by deafault conditions are in AND, my mistake :-(

**Comment by tek0011** [comment]
One way to force it in this state is to click OPEN in HA.  Then before the door is actually all the way open, click the OPEN/CLOSE button again.  The garage door will stop halfway open and you wont be able to OPEN/CLOSE it in HA.  I havent tried a reboot of HA, Ill try that now to see if it fixes it.

**Comment by GHSTUDIO1** [comment]
I have the identical problem....using HA to open or close the door, the state switches between opening and closing.  Using the meross application or my garage remotes, the HA state switches between open and closed.  They should, obviously, be the same.  

I'm terrible at coding...I'd really appreciate if someone would post a simple automation that triggers on state: "open or opening"  (or state: closed or closing).

**Comment by Florian-Schmidt** [comment]
@GHSTUDIO1: What do you want to achieve with an automation? If you want to be able to use garage door opener in HA again, it's enough to use my automation. When entity stays in such state over one minute, it updates cover entity. Afterwards everything’s fine again

**Comment by GHSTUDIO1** [comment]
My log shows the state of the garage door as “closing” from 9:45AM to 6:45PM and then changing to “open” when I opened the door to leave using a push button.  The state should not have been “closing” when the door is closed for 9 hours…it should say “closed”.

 

I am using the state change to trigger a TTS through an Amazon Echo (alexa)….a verbal statement that I have left.  The way it’s implemented means I have to compare state change from closed to open AND closing to Open.    If I decide to let HA open the door using an automation, then I have to check state changes from closed to open; closing to open; close to opening….three compares.

**Comment by Florian-Schmidt** [comment]
> My log shows the state of the garage door as “closing” from 9:45AM to 6:45PM and then changing to “open” when I opened the door to leave using a push button.  The state should not have been “closing” when the door is closed for 9 hours…it should say “closed”.

This was my problem also.

> I am using the state change to trigger a TTS through an Amazon Echo (alexa)….a verbal statement that I have left.  The way it’s implemented means I have to compare state change from closed to open AND closing to Open.    If I decide to let HA open the door using an automation, then I have to check state changes from closed to open; closing to open; close to opening….three compares.

I‘m using Home Kit (Siri) and HA automations to open and close garage. 

As it stays in „moving“ states, it was enough to check these to states. You can see that I‘m using two triggers.
I guess for normal open/close it‘s enough. Only interrupting the garage door could lead to a wrong state.

**Comment by albertogeniola** [comment]
Please update to the latest version (v1.0.0) which fixes the problem and introduces various improvements. Please follow update instructions [here](https://github.com/albertogeniola/meross-homeassistant#updating-from-legacy-versions).

**Comment by Skyhog** [comment]
I can say it's better, but still broken.  Right now, when opening, it changes state to opening, which is perfect since there is no way to tell when it is open (although I could argue that if it's not closed, it's open).  When closing, it changes state to closing, but then stays there even when closed.  Never actually changes state to closed unless using the Meross app.

My old workaround was to change the state to "closed" for a moment upon triggering the close command, then back to closing until the sensor reports closed 

As a test, right now the gate is closed, and is in "closing" status. I issue the open command with Home Assistant at 11:52:58 and it went into "opening" status and stayed there.  I issue the close command at 11:54:37, and the state changed to "closing.". The gate closed approximately 25 seconds later, and it stays in "closing" status.

11:52:58 - Opening
11:54:37 - Closing

From the Meross App, I do the same.  At 11:57:03, immediately upon trigger the open command, it goes into a state of "open," and stays there. When I trigger close, the status does not change at all until it completely closed at 11:58:31, when the sensor makes contact and it reports closed.

11:57:03 - Open
11:58:31 - Closed

My recommendation - immediately upon breaking contact, the status should go into "open" status.  Immediately upon triggering a close event, it should go into "closed" status momentarily, then to "closing" status about 2 seconds later.  Then when closed, it should report "closed."

**Comment by Florian-Schmidt** [comment]
Same behavior. I only reach „opening“ and „closed“.

**Comment by tek0011** [comment]
I still have the same issue as well.  My cheap/quick fix was to add a zigbee door sensor to the garage door.  Now I just check the zigbee device.  If its open, then I reset the state of the meross garage to open, and vice-versa for closed.

**Comment by zappy16** [comment]
Wanted to provide an update on this since the re-written libraries. It's been very stable for me and only reports "open" or "closed" states. There is no more "opening" or "closing" states. Been running it for over a month with no issues.

**Comment by albertogeniola** [comment]
Thanks for sharing!
