### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by Florian-Schmidt** [albertogeniola/meross-homeassistant#74]
Hi guys,

Just tried to use HA beta version as there are some nice changes included. Seems to work with my meross garage door opener.

As there seem to be some technical changes in 0.109 an warning occurs after reboot:
```

Logger: homeassistant.util.async_
Source: util/async_.py:120 
First occurred: 8:15:43 (1 occurrences) 
Last logged: 8:15:43

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for meross_cloud doing I/O at custom_components/meross_cloud/__init__.py, line 75: logout_on_stop=False)
```

Another warning says, that hidden .translation folder will be moved to visible translation folder in future:
```

Logger: homeassistant.helpers.translation
Source: helpers/translation.py:206 
First occurred: 8:17:06 (16 occurrences) 
Last logged: 8:17:07

meross_cloud: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this

```

**Comment by Scialla** [comment]
same here..

**Comment by userMak** [comment]
same here too

**Comment by THATDONFC** [comment]
Same issue here.
```Log Details (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 10:53:21 PM (2 occurrences)
Last logged: 10:53:22 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for meross_cloud doing I/O at custom_components/meross_cloud/__init__.py, line 55: http_client = MerossHttpClient.from_user_password(email=email, password=password)
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for meross_cloud doing I/O at custom_components/meross_cloud/__init__.py, line 60: http_devices = http_client.list_devices()
```

**Comment by ollo69** [comment]
Also for me. This is probably also causing block during startup with new version.
Not async method inside async should be executed using helper function like "async_add_executor_job"!!!

**Comment by DarwinData** [comment]
I am getting the same two log errors as the original poster. I am running HA Supervised on 109.3.

**Comment by silviudc** [comment]
So how do we fix this? Still happening on 0.109.6

**Comment by userMak** [comment]
Have we got any news ?

**Comment by albertogeniola** [comment]
Hi Guys, 
The new version of the component (now in development), will handle this as expected. Just be patient until it comes out.

**Comment by scannifn** [comment]
up

**Comment by maxcanna** [comment]
@scannifn this is not a forum, you should avoid posting messages like this. It's just spam and doesn't help the dev or other users. Thank you

**Comment by scannifn** [comment]
> @scannifn this is not a forum, you should avoid posting messages like this. It's just spam and doesn't help the dev or other users. Thank you

I'm sorry... I'm pretty new in this world... W l'Italia!
