### ISSUE TITLE
WARNING (MainThread) [homeassistant.helpers.translation]

### ISSUE THREAD

**Issue by silviudc** [albertogeniola/meross-homeassistant#80]
I keep getting this warning in my logs:

`2020-05-07 18:12:35 WARNING (MainThread) [homeassistant.helpers.translation] meross_cloud: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this `

I am on HA 109.4
How do I fix it?

**Comment by albertogeniola** [comment]
Duplicate https://github.com/albertogeniola/meross-homeassistant/issues/74
