### ISSUE TITLE
Increase power sensor polling interval (scan_interval)

### ISSUE THREAD

**Issue by horego** [albertogeniola/meross-homeassistant#83]
Hey there,

first of all i really like your project. But i got stuck increasing the polling interval for the meross power sensor. The current polling interval (default hass vm installation) is 30sec. I want to increase the interval to 5 sek for all the sensors.

Can anyone help me? I tried to set scan_interval in different section inside the configuration.yaml. But nothing changed the polling interval. I found a line of code which says
`def should_poll(self) -> bool:
        # Power sensors must be polled manually. We leave this task to the HomeAssistant engine
        return True
`
Is there a way to define a polling interval?
Best regards

**Comment by albertogeniola** [comment]
Currently, the library does not support that. You need to change the SCAN_INTERVAL constant within the sensor.py platform file.
