### ISSUE TITLE
Deprecated warnings in HA log after installing 0.110

### ISSUE THREAD

**Issue by coolguymatt** [albertogeniola/meross-homeassistant#84]
After updating to 0.110, I started seeing these errors in my HA log:

`ClimateDevice is deprecated, modify ValveEntityWrapper to extend ClimateEntity`
`SwitchDevice is deprecated, modify SwitchEntityWrapper to extend SwitchEntity`
`Light is deprecated, modify LightEntityWrapper to extend LightEntity`
`CoverDevice is deprecated, modify OpenGarageCover to extend CoverEntity`

After checking my other custom components, I believe the issue is meross-homeassistant.

**Comment by coolguymatt** [comment]
I opened https://github.com/albertogeniola/meross-homeassistant/pull/85 to fix this.

**Comment by Florian-Schmidt** [comment]
Am I right that there's no beta version available at the moment or is there a bug in actual HACS version?

**Comment by albertogeniola** [comment]
Please update to the latest version (v1.0.0) which fixes the problem and introduces various improvements. Please follow update instructions [here](https://github.com/albertogeniola/meross-homeassistant#updating-from-legacy-versions).
