### ISSUE TITLE
Translation folder issue

### ISSUE THREAD

**Issue by faberix76** [albertogeniola/meross-homeassistant#91]
Hi, are you planning to fix this: meross_cloud: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this

Best Regards,
Fabio

**Comment by silviudc** [comment]
Same here, the log is being spammed with.
```
2020-05-30 11:04:21 WARNING (MainThread) [homeassistant.helpers.translation] meross_cloud: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this
```

**Comment by antro31** [comment]
+1
We are at version 0.110.6, so 0.111 is not far.

**Comment by silgit** [comment]
@albertogeniola is working on the fix for #92 so I assume both of these will be fixed together :)

**Comment by faberix76** [comment]
> That's because #78 hasn't been merged yet

If It Is not jet merged, the issue Is not jet solved.

**Comment by albertogeniola** [comment]
Please update to the latest version (v1.0.0) which fixes the problem and introduces various improvements. Please follow update instructions [here](https://github.com/albertogeniola/meross-homeassistant#updating-from-legacy-versions).
