### ISSUE TITLE
ERROR (SyncWorker_7) [meross.connection] The underlying mqtt client is not connected after 0.110.4 Update

### ISSUE THREAD

**Issue by silviudc** [albertogeniola/meross-homeassistant#92]
The following error happens on all my meross devices after I updated to 0.110.4
```
2020-05-31 09:04:21 ERROR (SyncWorker_7) [meross.connection] The underlying mqtt client is not connected.
2020-05-31 09:04:21 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.garden_lights fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/meross_cloud/switch.py", line 44, in update
    self._device.get_status(force_status_refresh=True)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 134, in get_status
    self._state = self._get_status_impl()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 88, in _get_status_impl
    data = self.get_sys_data()['all']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 119, in get_sys_data
    return self.execute_command("GET", ALL, {}, online_check=False)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 116, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 275, in execute_cmd
    raise ConnectionError()
ConnectionError
```

Once I restart HA it works for a little while then the errors keep coming up

**Comment by tobydriver** [comment]
Same issue for me

**Comment by silviudc** [comment]
Is this integration still being actively supported? It is still broken in the current version of HA 0.110.4 in its current state.

**Comment by albertogeniola** [comment]
Hi, 
yes it is. I'm currently working on the low level python library this plugin is based on: once done, then I will move to refactor this plugin. Just be patiend and stay tuned!

**Comment by silviudc** [comment]
Awesome and good stuff 👍
You need any testing just say the word 😊

**Comment by SebRauSchmidt** [comment]
I get the same errors. My temporary workaround for this: I've disabled all power usage sensors in the integrations menu and now it's working for 36 hours without any problems. I'm thinking it has something to do with the polling rate.

**Comment by silviudc** [comment]
Guessing the fix didn't make it to 110.5 as it still happens

**Comment by userMak** [comment]
> I get the same errors. My temporary workaround for this: I've disabled all power usage sensors in the integrations menu and now it's working for 36 hours without any problems. I'm thinking it has something to do with the polling rate.

Can you explain further what you did please?
It is over a month now that my meross switches aren't working at all. I had to remove the integration and now most of my house lights aren't available in HA :(
I just read the mail from meross support and I am afraid that they won't worl with HA anymore
thanks

**Comment by SebRauSchmidt** [comment]
> > I get the same errors. My temporary workaround for this: I've disabled all power usage sensors in the integrations menu and now it's working for 36 hours without any problems. I'm thinking it has something to do with the polling rate.
> 
> Can you explain further what you did please?
> It is over a month now that my meross switches aren't working at all. I had to remove the integration and now most of my house lights aren't available in HA :(
> I just read the mail from meross support and I am afraid that they won't worl with HA anymore
> thanks

You have to disable the power sensor entities in your enities registry. If you go to the entity settings, you have an option to disable the power sensor entity. I don't have any meross lights, so i don't know if the workaround will work for you.

**Comment by silviudc** [comment]
I may have found the root cause of this and is related to what @SebRauSchmidt mentioned.
I have 2 meross power plugs outside for my outdoor lights and sometimes they drop the connection temporarily as they are a bit far away from the router.
I disabled those 2 power sensors via HA and the integration did not fail for about 1 day now.
Not sure what changed in 0.110.X but the same was happening on 0.109.6 but that never cause it to fail.

**Comment by markuskorbel** [comment]
Can confirm this as well, I got a number of switches with power sensors but
mine are inside the house and close to access points so I don't think
connection quality is causing the problem. I also disabled them as
suggested and it has been running fine for more than 2 days.

**Comment by mansbo** [comment]
Not sure if this forwards the discussion or not, but I have 7 switches, all with power monitors, and my HA instance restarts at 04:37 every day.  I then hit this issue and have to restart again at 12:56 every day.  That's exactly 499 minutes.  My devices seem to update every 30 seconds, so that's suspiciously close to 1000 updates before a failure.  Could it be that Meross has introduced some sort of limit on their cloud?

**Comment by mansbo** [comment]
Just a few seconds after I typed the previous comment, I hit the issue again at 18:56, and that's after a 13:00 restart.  So that blows my theory.  And it also occurs to me that I restarted this morning after 04:37 as I did the HA update to 0.110.6 around mid-morning.  So perhaps it's time related?  What would cause this to happen at 12:56 and 18:56?

**Comment by dervogt** [comment]
I also got some sensing power plugs (MS310) and some which are just switches (MS210). It really seems to be something in the update of the sensing switches which breaks the whole thing. Once I disable the sensors from the MS310, the whole integration just runs stable and rock-solid. Once I start re-enabling the MS310 sensor side, the troubles begin again. Regardsless if I just enable one MS310 or multiple, as soon as it starts reading the sensor values, the error logs just overflows and sooner or later the whole custom integration becomes unrespeinsive till a full restart of my docker container, just re-start in the HomeAssistant console does not make the trick for me...

**Comment by silviudc** [comment]
For me I switched off 3 out 5 power sensors but kept 2 on and I never had any issues since.

**Comment by bwohl** [comment]
Ran into the same problem: Since I am using the power sesor to monitor my wasing maschine disabling it was nit an option.
I setup a nodered automation to reboot hassio when it happens but better than nothing right now...

**Comment by albertogeniola** [comment]
Please update to the latest version (v1.0.0) which fixes the problem and introduces various improvements. Please follow update instructions [here](https://github.com/albertogeniola/meross-homeassistant#updating-from-legacy-versions).
