### ISSUE TITLE
Disconnessione dopo alcune ore

### ISSUE THREAD

**Issue by Marcozza** [albertogeniola/meross-homeassistant#94]
Buongiorno, nell'ultimo periodo noto molto spesso, almeno 2 volte al giorno che tutti i sensori e gli switch smettono di funzionare, e passano allo stato "non disponibile" fino a che non si effettua un riavvio. Così dopo qualche ora ricapita di nuovo e procedo con un ulteriore riavvio.

Ho 6 dispositivi meross, 4 mss310 e 2 mss310r

Uso hassos con home assistant 110.6 che proprio ora aggiorno alla 110.7

Scusi scrivo in italiano visto che dal nome credo sia italiano anche lei.

Grazie

**Comment by albertogeniola** [comment]
Salve, 
sì, è un problema noto e sarà risolto con la nuova versione del componente, che è correntemente in fase di sviluppo.

**Comment by Marcozza** [comment]
Ok grazie, non mi sono accorto di disconnessioni. forse è colpa di una sola presa che è molto al limite della portata del wifi.
