### ISSUE TITLE
MSS420 unavailable approx every 6 hours, for about an hour

### ISSUE THREAD

**Issue by honkerst** [albertogeniola/meross-homeassistant#97]
I've had a MSS420 power strip connected with this integration about 3 months now. 

Every 6 hours (plus/minus 5 minutes) it goes unavailable for 30-60 minutes. I don't see anything relevant in my HA logs, just the regular warnings about 'I/O inside the loop' and 'translations'. 

Here's a screenshot of the last 24 ours. It looks like this every day, without fail 😄 

[https://i.imgur.com/IBVMU50.png](https://i.imgur.com/IBVMU50.png)

Is there a logger level I can increase to find out what's happening?

**Comment by me1337me** [comment]
I have nearly the same problem.

In my setup, I have 4 mss310 (outlet) connected. They also lose connectivity and switch to "unavailable" after some time (cant say if there is a pattern). But they wont reconnect.
I always have to restart HA.

I would say this behavior exists like about 2 month (not sure). But there was a time, when it didnt happen ;)

Are there any information i can debug/log to help solving the issue?

Thanks a lot!

**Comment by honkerst** [comment]
I no longer seem to have this problem. My MSS420 was previously connected to a TP-Link Deco mesh wifi AP. For unrelated reasons I changed the MSS420 to join a different plain old 2.4GHz wifi network (the crappy router my ISP provides). This signal is much weaker than the mesh signal. 

For some reason this seems to have cured the disconnects every 6 hours. It's been about 48 hours so far. I don't know if the MS420 simply doesn't like the mesh 2.4GHz implementation, or it's some weird DHCP issue. FWIW my DHCP lease is 24 hours.
