### ISSUE TITLE
getting error messages

### ISSUE THREAD

**Issue by blaster452** [albertogeniola/meross-homeassistant#98]
not sure what the error message means but here it is:

"Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for meross_cloud doing I/O at custom_components/meross_cloud/__init__.py, line 60: http_devices = http_client.list_devices()
Successfully saved"

**Comment by cnopix** [comment]
i have the same error and i had to remove the meross add-in because my HA has to be restarted every day.

**Comment by maxcanna** [comment]
Please avoid opening duplicate issues. This is already solved in #78

**Comment by albertogeniola** [comment]
As pointed by @maxcanna , this is duplicate. Closing.
